use async_trait::async_trait;
use diesel::prelude::*;
use diesel_async::RunQueryDsl;
use crate::domain::audit::repository::AuditLogRepository;
use crate::domain::shared_kernel::entities::audit::{AuditLogEntry, AuditQuery, AuditAction, ResourceType, AuditResult};
use crate::infrastructure::models::audit::{AuditLogDb, NewAuditLogDb};
use crate::infrastructure::database::diesel_connection_manager::get_analytics_pool;
use crate::schemas::analytics::audit_logs;
use anyhow::{Result, Context};
use crate::domain::shared_kernel::value_objects::UserId;

pub struct DieselAuditLogRepository;

impl Default for DieselAuditLogRepository {
    fn default() -> Self {
        Self::new()
    }
}

impl DieselAuditLogRepository {
    pub fn new() -> Self {
        Self
    }
}

// Helper to map DB model to Domain entity
impl From<AuditLogDb> for AuditLogEntry {
    fn from(db: AuditLogDb) -> Self {
        AuditLogEntry {
            id: db.id.to_string(),
            wallet_address: db.wallet_address.map(UserId::from_string_unchecked),
            action: match db.action.as_str() {
                "Create" => AuditAction::Create,
                "Read" => AuditAction::Read,
                "Update" => AuditAction::Update,
                "Delete" => AuditAction::Delete,
                "Login" => AuditAction::Login,
                "Logout" => AuditAction::Logout,
                "PermissionGranted" => AuditAction::PermissionGranted,
                "PermissionRevoked" => AuditAction::PermissionRevoked,
                "PaymentInitiated" => AuditAction::PaymentInitiated,
                "PaymentCompleted" => AuditAction::PaymentCompleted,
                "Export" => AuditAction::Export,
                 // Default fallback for unknown actions to prevent crash
                _ => AuditAction::Read, 
            },
            resource_type: match db.resource_type.as_str() {
                "User" => ResourceType::User,
                "Session" => ResourceType::Session,
                "Payment" => ResourceType::Payment,
                "Notification" => ResourceType::Notification,
                "Analytics" => ResourceType::Analytics,
                "Admin" => ResourceType::Admin,
                _ => ResourceType::Admin,
            },
            resource_id: db.resource_id,
            result: match db.result.as_str() {
                "Success" => AuditResult::Success,
                "Failed" => AuditResult::Failed,
                "Denied" => AuditResult::Denied,
                _ => AuditResult::Failed,
            },
            ip_address: db.ip_address,
            user_agent: db.user_agent,
            additional_data: db.details,
            timestamp: db.created_at,
        }
    }
}

#[async_trait]
impl AuditLogRepository for DieselAuditLogRepository {
    async fn save(&self, entry: AuditLogEntry) -> Result<AuditLogEntry> {
        let pool = get_analytics_pool().await?;
        let mut conn = pool.get().await.map_err(|e| anyhow::anyhow!("Failed to get DB connection: {:?}", e))?;

        let new_log = NewAuditLogDb {
            wallet_address: entry.wallet_address.map(|w| w.to_string()),
            action: format!("{:?}", entry.action),
            resource_type: format!("{:?}", entry.resource_type),
            resource_id: entry.resource_id.clone(),
            result: format!("{:?}", entry.result),
            ip_address: entry.ip_address.clone(),
            user_agent: entry.user_agent.clone(),
            details: entry.additional_data.clone(),
        };

        // Note: The ID is generated by DB default (gen_random_uuid) or we could set it. 
        // Logic currently ignores entry.id for insertion if we rely on DB default, 
        // OR we can include ID if we want to determine it.
        // But AuditLogEntry::new() creates a UUID string. 
        // For consistency, let's let DB generate it or use the one from entry if we wanted.
        // The NewAuditLogDb struct I defined doesn't have ID field (created_at is default).
        
        // We insert and return the created row to get the timestamp and ID back.
        let inserted: AuditLogDb = diesel::insert_into(audit_logs::table)
            .values(&new_log)
            .get_result(&mut conn)
            .await
            .context("Failed to insert audit log")?;

        Ok(inserted.into())
    }

    async fn find_all(&self, query: AuditQuery) -> Result<(Vec<AuditLogEntry>, i64)> {
        let pool = get_analytics_pool().await?;
        let mut conn = pool.get().await.map_err(|e| anyhow::anyhow!("Failed to get DB connection: {:?}", e))?;

        // Use a local closure to build the query twice to avoid move/clone issues with Diesel's BoxedQuery
        let build_query = || {
            let mut base_query = audit_logs::table.into_boxed();

            if let Some(address) = &query.wallet_address {
                base_query = base_query.filter(audit_logs::wallet_address.eq(address.to_string()));
            }

            if let Some(action) = &query.action {
                base_query = base_query.filter(audit_logs::action.eq(format!("{:?}", action)));
            }

            if let Some(res_type) = &query.resource_type {
                base_query = base_query.filter(audit_logs::resource_type.eq(format!("{:?}", res_type)));
            }
            
            if let Some(from_date) = query.from_date {
                base_query = base_query.filter(audit_logs::created_at.ge(from_date));
            }

            if let Some(to_date) = query.to_date {
                base_query = base_query.filter(audit_logs::created_at.le(to_date));
            }
            
            base_query
        };

        // Count total matching
        let total = build_query()
            .count()
            .get_result::<i64>(&mut conn)
            .await?;

        // Pagination
        let limit = query.limit.unwrap_or(50) as i64;
        let offset = query.offset.unwrap_or(0) as i64;

        let results: Vec<AuditLogDb> = build_query()
            .order(audit_logs::created_at.desc())
            .limit(limit)
            .offset(offset)
            .load(&mut conn)
            .await?;

        let entries = results.into_iter().map(|db| db.into()).collect();

        Ok((entries, total))
    }
}
