// Generated by scripts/audit/dioxus_admin_aliases.py. Do not edit.
use dioxus::prelude::*;

#[component]
pub fn PrefixedAdminWalletListView(query: String) -> Element {
    rsx! { super::AdminWalletListView { query } }
}

#[component]
pub fn PrefixedAdminWalletDetailView(address: String, query: String) -> Element {
    rsx! { super::AdminWalletDetailView { address, query } }
}

#[component]
pub fn PrefixedAdminWalletDetailAliasView(address: String, query: String) -> Element {
    rsx! { super::AdminWalletDetailAliasView { address, query } }
}

#[component]
pub fn PrefixedAdminWalletDisableView(address: String, query: String) -> Element {
    rsx! { super::AdminWalletDisableView { address, query } }
}

#[component]
pub fn PrefixedAdminWalletAccessView(query: String) -> Element {
    rsx! { super::AdminWalletAccessView { query } }
}

#[component]
pub fn PrefixedAdminWalletCreditsView(query: String) -> Element {
    rsx! { super::AdminWalletCreditsView { query } }
}

#[component]
pub fn PrefixedAdminWalletPlansView(query: String) -> Element {
    rsx! { super::AdminWalletPlansView { query } }
}

#[component]
pub fn PrefixedAdminWalletPlanView(id: String, query: String) -> Element {
    rsx! { super::AdminWalletPlanView { id, query } }
}

#[component]
pub fn PrefixedAdminEscrowsView(query: String) -> Element {
    rsx! { super::AdminEscrowsView { query } }
}

#[component]
pub fn PrefixedAdminEscrowDetailView(id: String, query: String) -> Element {
    rsx! { super::AdminEscrowDetailView { id, query } }
}

#[component]
pub fn PrefixedAdminMerchantEscrowsView(query: String) -> Element {
    rsx! { super::AdminMerchantEscrowsView { query } }
}

#[component]
pub fn PrefixedAdminMerchantEscrowDetailView(id: String, query: String) -> Element {
    rsx! { super::AdminMerchantEscrowDetailView { id, query } }
}

#[component]
pub fn PrefixedAdminOrdersView(query: String) -> Element {
    rsx! { super::AdminOrdersView { query } }
}

#[component]
pub fn PrefixedAdminOrderDetailView(id: String) -> Element {
    rsx! { super::AdminOrderDetailView { id } }
}

#[component]
pub fn PrefixedAdminCatalogView() -> Element {
    rsx! { super::AdminCatalogView {  } }
}

#[component]
pub fn PrefixedAdminCatalogDetailView(id: String) -> Element {
    rsx! { super::AdminCatalogDetailView { id } }
}

#[component]
pub fn PrefixedAdminHomeView() -> Element {
    rsx! { super::AdminHomeView {  } }
}

#[component]
pub fn PrefixedAdminIndexView() -> Element {
    rsx! { super::AdminIndexView {  } }
}

#[component]
pub fn PrefixedAdminAuthView(query: String) -> Element {
    rsx! { super::AdminAuthView { query } }
}

#[component]
pub fn PrefixedAdminDashboardView() -> Element {
    rsx! { super::AdminDashboardView {  } }
}

#[component]
pub fn PrefixedAdminAnalyticsView(query: String) -> Element {
    rsx! { super::AdminAnalyticsView { query } }
}

#[component]
pub fn PrefixedAdminUsersView() -> Element {
    rsx! { super::AdminUsersView {  } }
}

#[component]
pub fn PrefixedAdminPaymentsView(query: String) -> Element {
    rsx! { super::AdminPaymentsView { query } }
}

#[component]
pub fn PrefixedAdminNotificationsView() -> Element {
    rsx! { super::AdminNotificationsView {  } }
}

#[component]
pub fn PrefixedAdminNotificationsManageView(query: String) -> Element {
    rsx! { super::AdminNotificationsManageView { query } }
}

#[component]
pub fn PrefixedAdminNotificationsCreateView(query: String) -> Element {
    rsx! { super::AdminNotificationsCreateView { query } }
}

#[component]
pub fn PrefixedAdminNewsView(query: String) -> Element {
    rsx! { super::AdminNewsView { query } }
}

#[component]
pub fn PrefixedAdminNewsCreateView() -> Element {
    rsx! { super::AdminNewsCreateView {  } }
}

#[component]
pub fn PrefixedAdminNewsEditView(id: String) -> Element {
    rsx! { super::AdminNewsEditView { id } }
}

#[component]
pub fn PrefixedAdminChatView(query: String) -> Element {
    rsx! { super::AdminChatView { query } }
}

#[component]
pub fn PrefixedAdminChatDetailView(id: String, query: String) -> Element {
    rsx! { super::AdminChatDetailView { id, query } }
}

#[component]
pub fn PrefixedAdminDeveloperPortalView(query: String) -> Element {
    rsx! { super::AdminDeveloperPortalView { query } }
}

#[component]
pub fn PrefixedAdminDeveloperCreateView() -> Element {
    rsx! { super::AdminDeveloperCreateView {  } }
}

#[component]
pub fn PrefixedAdminMediaView(query: String) -> Element {
    rsx! { super::AdminMediaView { query } }
}

#[component]
pub fn PrefixedAdminSettingsView(query: String) -> Element {
    rsx! { super::AdminSettingsView { query } }
}

#[component]
pub fn PrefixedAdminAuditLogView(query: String) -> Element {
    rsx! { super::AdminAuditLogView { query } }
}

#[component]
pub fn PrefixedAdminAccessDeniedView(query: String) -> Element {
    rsx! { super::AdminAccessDeniedView { query } }
}

#[component]
pub fn PrefixedAdminUnauthorizedView() -> Element {
    rsx! { super::AdminUnauthorizedView {  } }
}
