#!/usr/bin/env python3
"""Keep legacy /admin-prefixed URLs in the same typed Dioxus route tree.

Run normally to regenerate, or --check as a drift gate. These are route aliases,
not HTML adapters or a second router. The original dispatcher accepted one prefix.
"""
from pathlib import Path
import re,sys
ROOT=Path(__file__).resolve().parents[2]
ROUTES=ROOT/'shared/rust/dioxus_ui/src/routes.rs'
ALIASES=ROOT/'shared/rust/dioxus_ui/src/routes/admin_aliases.rs'
START='    // BEGIN GENERATED ADMIN PREFIX ROUTES\n'
END='    // END GENERATED ADMIN PREFIX ROUTES\n'
s=ROUTES.read_text()
s=re.sub(r'\n?'+re.escape(START)+r'.*?'+re.escape(END),'\n',s,flags=re.S)
a=s.index('pub enum AdminRoute {');b=s.index('\n}',a)
variants=[]
functions=['// Generated by scripts/audit/dioxus_admin_aliases.py. Do not edit.\nuse dioxus::prelude::*;\n']
for path,name,fields in re.findall(r'#\[route\("([^"\n]+)"\)\]\s*(\w+)\s*\{([^}]*)\}',s[a:b]):
    if ':..route' in path:continue
    alias='Prefixed'+name
    target='/admin'+(path if path!='/' else '')
    variants.append(f'    #[route("{target}")]\n    {alias} {{ {fields.strip()} }},\n')
    arguments=', '.join(field.split(':',1)[0].strip() for field in fields.split(',') if field.strip())
    functions.append(f'#[component]\npub fn {alias}({fields.strip()}) -> Element {{\n    rsx! {{ super::{name} {{ {arguments} }} }}\n}}\n')
s=s[:b]+'\n'+START+''.join(variants)+END+s[b:]
content='\n'.join(functions)
if '--check' in sys.argv:
    normalize=lambda value: re.sub(r'[\s,]+','',value)
    if normalize(ROUTES.read_text())!=normalize(s) or not ALIASES.exists() or normalize(ALIASES.read_text())!=normalize(content):raise SystemExit('Admin aliases are stale; run scripts/audit/dioxus_admin_aliases.py')
else:
    ROUTES.write_text(s);ALIASES.parent.mkdir(exist_ok=True);ALIASES.write_text(content)
print(f'{len(variants)} Admin routes preserve their /admin aliases through typed components.')
