[application]
name = "epsx-frontend"
public_dir = "public"

[web.app]
title = "EPSX - Analytics Platform"

[web.watcher]
watch_path = ["src", "../../shared/rust/dioxus_ui/src", "../../shared/rust/templates/src"]
