apiVersion: v1
kind: Service
metadata:
  name: epsx-notification
  labels:
    app: epsx-notification
spec:
  type: ClusterIP
  selector:
    app: epsx-notification
  ports:
    - name: http
      port: 8106
      targetPort: 8106
