export enum TokenFeature {
  TRADING = 'TRADING',
  ADMIN_ACCESS = 'ADMIN_ACCESS',
  REAL_TIME_ANALYSIS = 'REAL_TIME_ANALYSIS',
  TRADING_BOT = 'TRADING_BOT',
  AI_ANALYSIS = 'AI_ANALYSIS',
  PORTFOLIO_MANAGEMENT = 'PORTFOLIO_MANAGEMENT',
  ADVANCED_TOOLS = 'ADVANCED_TOOLS',
}
