apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/invoker-iam-disabled: 'true'
    run.googleapis.com/urls: '["https://backend-307278481624.europe-west1.run.app","https://backend-6wjeb6vw2q-ew.a.run.app"]'
  labels:
    cloud.googleapis.com/location: europe-west1
  name: backend
  namespace: '307278481624'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 534.0.0
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: qatiisovsj
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - image: us-central1-docker.pkg.dev/epsx-469400/epsx/backend:latest
        name: backend-1
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: 307278481624-compute@developer.gserviceaccount.com
      timeoutSeconds: 900
  traffic:
  - latestRevision: true
    percent: 100
