apiVersion: apps/v1
kind: Deployment
metadata:
  name: epsx-backend
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epsx-frontend
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epsx-admin
spec:
  replicas: 1
