apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: epsx-prod

resources:
  - ../../base

images:
  - name: registry.jesadakorn.com/jesadakorn/epsx/backend
    newName: epsx-backend
    newTag: prod
  - name: registry.jesadakorn.com/jesadakorn/epsx/frontend
    newName: epsx-frontend
    newTag: prod
  - name: registry.jesadakorn.com/jesadakorn/epsx/admin
    newName: epsx-admin-frontend
    newTag: prod

patches:
  - path: patches/replicas.yaml
  - path: patches/resources.yaml
  - path: patches/services-nodeport.yaml
