apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: epsx-staging

resources:
  - ../../base
  - pvcs.yaml

images:
  - name: registry.epsx.io/jesadakorn/epsx/backend
    newTag: staging-latest
  - name: registry.epsx.io/jesadakorn/epsx/frontend
    newTag: staging-latest
  - name: registry.epsx.io/jesadakorn/epsx/admin
    newTag: staging-latest

patches:
  - path: patches/resources.yaml
  - path: patches/postgres-conf.yaml
  - path: patches/redis-conf.yaml
