apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: epsx-staging

resources:
  - ../../base

images:
  - name: epsx-backend
    newTag: staging
  - name: bff-frontend
    newTag: staging
  - name: bff-admin
    newTag: staging

patches:
  - path: patches/replicas.yaml
  - path: patches/resources.yaml
  - path: patches/services-nodeport.yaml
