// Security Monitoring Service - Centralized security event management and analysis
import { ComprehensiveInputSanitizer } from './input-sanitization'
import { AdvancedXSSCSRFProtection } from './xss-csrf-protection'
import { SecurePermissionContextManager } from './secure-permission-context-guards'
import { DataExposurePreventionManager } from './data-exposure-prevention'

// Comprehensive Security Event Types
export interface SecurityEvent {
  id: string
  timestamp: string
  eventType: 'input_threat' | 'xss_attempt' | 'csrf_violation' | 'permission_breach' | 'data_exposure' | 'authentication_anomaly' | 'system_intrusion' | 'compliance_violation'
  severity: 'low' | 'medium' | 'high' | 'critical'
  source: string
  userId?: string
  userEmail?: string
  component: string
  description: string
  threatVector?: string
  blocked: boolean
  remediationAction?: string
  metadata: Record<string, any>
  ipAddress?: string
  userAgent?: string
  sessionId?: string
  riskScore: number
  complianceImpact: string[]
  remediated: boolean
  rawData?: any
}

export interface SecurityAlert {
  id: string
  type: 'critical_threat' | 'compliance_violation' | 'system_anomaly' | 'user_behavior_anomaly' | 'coordinated_attack'
  priority: 'urgent' | 'high' | 'medium' | 'low'
  title: string
  description: string
  timestamp: string
  acknowledged: boolean
  resolved: boolean
  assignedTo?: string
  relatedEvents: string[]
  autoGenerated: boolean
  confidenceScore: number
}

export interface ThreatMetrics {
  totalThreats: number
  blockedThreats: number
  activeIncidents: number
  riskScore: number
  complianceScore: number
  lastThreatTime?: string
  threatTrends: Array<{
    period: string
    count: number
    severity: string
    blocked: number
  }>
  topThreats: Array<{
    type: string
    count: number
    severity: string
  }>
}

export interface SecurityPattern {
  id: string
  name: string
  description: string
  pattern: RegExp | string
  severity: 'low' | 'medium' | 'high' | 'critical'
  category: 'malware' | 'injection' | 'xss' | 'csrf' | 'permission' | 'data_leak' | 'behavioral'
  enabled: boolean
  createdAt: string
  lastMatch?: string
  matchCount: number
}

export interface ComplianceRule {
  id: string
  regulation: 'gdpr' | 'pci' | 'sox' | 'hipaa' | 'ccpa'
  name: string
  description: string
  severity: 'low' | 'medium' | 'high' | 'critical'
  enabled: boolean
  lastViolation?: string
  violationCount: number
  autoRemediate: boolean
}

export interface SecurityReport {
  id: string
  type: 'daily' | 'weekly' | 'monthly' | 'incident'
  title: string
  generatedAt: string
  period: {
    startDate: string
    endDate: string
  }
  summary: {
    totalEvents: number
    criticalEvents: number
    blockedThreats: number
    complianceScore: number
    riskScore: number
  }
  events: SecurityEvent[]
  alerts: SecurityAlert[]
  recommendations: string[]
  complianceStatus: Record<string, 'compliant' | 'warning' | 'violation'>
}

// Advanced Security Monitoring Configuration
export interface SecurityMonitoringConfig {
  realTimeMonitoring: boolean
  autoAlertGeneration: boolean
  complianceMode: 'strict' | 'balanced' | 'permissive'
  riskTolerance: 'low' | 'medium' | 'high'
  retentionPeriod: number // days
  alertThresholds: {
    criticalEventRate: number // events per minute
    failedAttemptsThreshold: number
    riskScoreThreshold: number
  }
  integrations: {
    email: boolean
    slack: boolean
    webhook: boolean
    siem: boolean
  }
  reportingSchedule: {
    daily: boolean
    weekly: boolean
    monthly: boolean
  }
}

// Centralized Security Monitoring Service
export class SecurityMonitoringService {
  private events: Map<string, SecurityEvent> = new Map()
  private alerts: Map<string, SecurityAlert> = new Map()
  private patterns: Map<string, SecurityPattern> = new Map()
  private complianceRules: Map<string, ComplianceRule> = new Map()
  private eventListeners: Map<string, Array<(event: SecurityEvent) => void>> = new Map()
  private alertListeners: Array<(alert: SecurityAlert) => void> = []
  
  private inputSanitizer: ComprehensiveInputSanitizer
  private xssCSRFProtection: AdvancedXSSCSRFProtection
  private permissionContextManager: SecurePermissionContextManager
  private dataExposurePrevention: DataExposurePreventionManager
  
  private config: SecurityMonitoringConfig = {
    realTimeMonitoring: true,
    autoAlertGeneration: true,
    complianceMode: 'balanced',
    riskTolerance: 'medium',
    retentionPeriod: 90,
    alertThresholds: {
      criticalEventRate: 5,
      failedAttemptsThreshold: 10,
      riskScoreThreshold: 70
    },
    integrations: {
      email: true,
      slack: false,
      webhook: false,
      siem: false
    },
    reportingSchedule: {
      daily: true,
      weekly: true,
      monthly: true
    }
  }

  constructor(config?: Partial<SecurityMonitoringConfig>) {
    if (config) {
      this.config = { ...this.config, ...config }
    }
    
    this.inputSanitizer = new ComprehensiveInputSanitizer()
    this.xssCSRFProtection = new AdvancedXSSCSRFProtection()
    this.permissionContextManager = new SecurePermissionContextManager()
    this.dataExposurePrevention = new DataExposurePreventionManager()
    
    this.initializeSecurityPatterns()
    this.initializeComplianceRules()
    this.setupSecurityIntegrations()
    
    if (this.config.realTimeMonitoring) {
      this.startRealTimeMonitoring()
    }
  }

  // Initialize security patterns for threat detection
  private initializeSecurityPatterns(): void {
    const patterns: SecurityPattern[] = [
      {
        id: 'sql_injection_pattern',
        name: 'SQL Injection Detection',
        description: 'Detects SQL injection attempts',
        pattern: /(\bUNION\b|\bSELECT\b|\bINSERT\b|\bUPDATE\b|\bDELETE\b|\bDROP\b).*(\bFROM\b|\bINTO\b|\bWHERE\b)/i,
        severity: 'critical',
        category: 'injection',
        enabled: true,
        createdAt: new Date().toISOString(),
        matchCount: 0
      },
      {
        id: 'xss_script_pattern',
        name: 'XSS Script Tag Detection',
        description: 'Detects XSS attempts with script tags',
        pattern: /<script[\s\S]*?>[\s\S]*?<\/script>/i,
        severity: 'critical',
        category: 'xss',
        enabled: true,
        createdAt: new Date().toISOString(),
        matchCount: 0
      },
      {
        id: 'csrf_token_missing',
        name: 'Missing CSRF Token',
        description: 'Detects requests without valid CSRF tokens',
        pattern: 'CSRF_TOKEN_MISSING',
        severity: 'high',
        category: 'csrf',
        enabled: true,
        createdAt: new Date().toISOString(),
        matchCount: 0
      },
      {
        id: 'privilege_escalation',
        name: 'Privilege Escalation Attempt',
        description: 'Detects unauthorized permission elevation attempts',
        pattern: 'PRIVILEGE_ESCALATION',
        severity: 'high',
        category: 'permission',
        enabled: true,
        createdAt: new Date().toISOString(),
        matchCount: 0
      },
      {
        id: 'sensitive_data_leak',
        name: 'Sensitive Data Exposure',
        description: 'Detects potential sensitive data leakage',
        pattern: 'SENSITIVE_DATA_EXPOSURE',
        severity: 'medium',
        category: 'data_leak',
        enabled: true,
        createdAt: new Date().toISOString(),
        matchCount: 0
      }
    ]

    patterns.forEach(pattern => this.patterns.set(pattern.id, pattern))
  }

  // Initialize compliance rules
  private initializeComplianceRules(): void {
    const rules: ComplianceRule[] = [
      {
        id: 'gdpr_data_retention',
        regulation: 'gdpr',
        name: 'Data Retention Compliance',
        description: 'Ensures personal data is not retained beyond necessary period',
        severity: 'high',
        enabled: true,
        violationCount: 0,
        autoRemediate: false
      },
      {
        id: 'pci_data_encryption',
        regulation: 'pci',
        name: 'Payment Data Encryption',
        description: 'Ensures payment card data is properly encrypted',
        severity: 'critical',
        enabled: true,
        violationCount: 0,
        autoRemediate: true
      },
      {
        id: 'sox_audit_trail',
        regulation: 'sox',
        name: 'Audit Trail Integrity',
        description: 'Ensures financial data access is properly logged',
        severity: 'high',
        enabled: true,
        violationCount: 0,
        autoRemediate: false
      },
      {
        id: 'hipaa_access_control',
        regulation: 'hipaa',
        name: 'Healthcare Data Access Control',
        description: 'Ensures healthcare data access is restricted and logged',
        severity: 'critical',
        enabled: true,
        violationCount: 0,
        autoRemediate: true
      }
    ]

    rules.forEach(rule => this.complianceRules.set(rule.id, rule))
  }

  // Setup integrations with security systems
  private setupSecurityIntegrations(): void {
    // Integration with input sanitizer
    this.addEventListener('input_sanitization', (event) => {
      this.recordSecurityEvent({
        ...event,
        source: 'ComprehensiveInputSanitizer',
        eventType: 'input_threat'
      })
    })

    // Integration with XSS/CSRF protection
    this.addEventListener('xss_csrf_protection', (event) => {
      this.recordSecurityEvent({
        ...event,
        source: 'AdvancedXSSCSRFProtection',
        eventType: event.threatVector?.includes('xss') ? 'xss_attempt' : 'csrf_violation'
      })
    })

    // Integration with permission context manager
    this.addEventListener('permission_context', (event) => {
      this.recordSecurityEvent({
        ...event,
        source: 'SecurePermissionContextManager',
        eventType: 'permission_breach'
      })
    })

    // Integration with data exposure prevention
    this.addEventListener('data_exposure_prevention', (event) => {
      this.recordSecurityEvent({
        ...event,
        source: 'DataExposurePreventionManager',
        eventType: 'data_exposure'
      })
    })
  }

  // Start real-time monitoring
  private startRealTimeMonitoring(): void {
    // Monitor threat patterns every 30 seconds
    setInterval(() => {
      this.analyzeSecurityTrends()
      this.generateAutoAlerts()
    }, 30000)

    // Cleanup old events every hour
    setInterval(() => {
      this.cleanupOldEvents()
    }, 3600000)

    // Generate periodic reports
    if (this.config.reportingSchedule.daily) {
      setInterval(() => {
        this.generateSecurityReport('daily')
      }, 86400000) // 24 hours
    }
  }

  // Record security event
  public recordSecurityEvent(eventData: Partial<SecurityEvent>): SecurityEvent {
    const event: SecurityEvent = {
      id: `evt_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
      timestamp: new Date().toISOString(),
      eventType: eventData.eventType || 'system_intrusion',
      severity: eventData.severity || 'medium',
      source: eventData.source || 'Unknown',
      userId: eventData.userId,
      userEmail: eventData.userEmail,
      component: eventData.component || 'Unknown',
      description: eventData.description || 'Security event detected',
      threatVector: eventData.threatVector,
      blocked: eventData.blocked || false,
      remediationAction: eventData.remediationAction,
      metadata: eventData.metadata || {},
      ipAddress: eventData.ipAddress,
      userAgent: eventData.userAgent,
      sessionId: eventData.sessionId,
      riskScore: eventData.riskScore || this.calculateRiskScore(eventData),
      complianceImpact: eventData.complianceImpact || [],
      remediated: eventData.remediated || false,
      rawData: eventData.rawData
    }

    // Store the event
    this.events.set(event.id, event)

    // Pattern matching and analysis
    this.analyzeEventPatterns(event)
    
    // Compliance checking
    this.checkComplianceViolations(event)
    
    // Auto-generate alerts if configured
    if (this.config.autoAlertGeneration) {
      this.evaluateForAutoAlert(event)
    }

    // Notify listeners
    this.notifyEventListeners(event)

    // Log to console in development
    if (process.env.NODE_ENV === 'development') {
      console.log(`[SecurityMonitoring] Event recorded:`, {
        id: event.id,
        type: event.eventType,
        severity: event.severity,
        riskScore: event.riskScore,
        component: event.component
      })
    }

    return event
  }

  // Calculate risk score based on event properties
  private calculateRiskScore(eventData: Partial<SecurityEvent>): number {
    let riskScore = 0

    // Base severity score
    switch (eventData.severity) {
      case 'critical': riskScore += 40; break
      case 'high': riskScore += 30; break
      case 'medium': riskScore += 20; break
      case 'low': riskScore += 10; break
      default: riskScore += 15; break
    }

    // Event type multiplier
    const typeMultipliers: Record<string, number> = {
      'input_threat': 1.5,
      'xss_attempt': 2.0,
      'csrf_violation': 1.8,
      'permission_breach': 2.2,
      'data_exposure': 1.9,
      'authentication_anomaly': 1.7,
      'system_intrusion': 2.5
    }

    const multiplier = typeMultipliers[eventData.eventType || ''] || 1.0
    riskScore *= multiplier

    // Blocked vs unblocked
    if (!eventData.blocked) {
      riskScore *= 1.8
    }

    // Compliance impact
    if (eventData.complianceImpact && eventData.complianceImpact.length > 0) {
      riskScore += eventData.complianceImpact.length * 5
    }

    // Normalize to 0-100 scale
    return Math.min(Math.round(riskScore), 100)
  }

  // Analyze event patterns for threat detection
  private analyzeEventPatterns(event: SecurityEvent): void {
    this.patterns.forEach(pattern => {
      if (!pattern.enabled) return

      let matches = false
      const searchText = `${event.description} ${event.threatVector || ''} ${JSON.stringify(event.metadata)}`

      if (pattern.pattern instanceof RegExp) {
        matches = pattern.pattern.test(searchText)
      } else if (typeof pattern.pattern === 'string') {
        matches = searchText.includes(pattern.pattern)
      }

      if (matches) {
        pattern.matchCount++
        pattern.lastMatch = new Date().toISOString()
        
        // Enhance event with pattern information
        event.metadata.matchedPatterns = event.metadata.matchedPatterns || []
        event.metadata.matchedPatterns.push({
          patternId: pattern.id,
          patternName: pattern.name,
          severity: pattern.severity,
          category: pattern.category
        })
      }
    })
  }

  // Check for compliance violations
  private checkComplianceViolations(event: SecurityEvent): void {
    this.complianceRules.forEach(rule => {
      if (!rule.enabled) return

      let violationDetected = false

      // Rule-specific violation detection logic
      switch (rule.id) {
        case 'gdpr_data_retention':
          violationDetected = event.eventType === 'data_exposure' && 
                           event.metadata.sensitiveData?.includes('personal')
          break
        case 'pci_data_encryption':
          violationDetected = event.eventType === 'data_exposure' && 
                           event.metadata.sensitiveData?.includes('payment')
          break
        case 'sox_audit_trail':
          violationDetected = event.eventType === 'permission_breach' && 
                           event.metadata.financialDataAccess
          break
        case 'hipaa_access_control':
          violationDetected = event.eventType === 'data_exposure' && 
                           event.metadata.sensitiveData?.includes('health')
          break
      }

      if (violationDetected) {
        rule.violationCount++
        rule.lastViolation = new Date().toISOString()
        
        // Add compliance violation to event
        if (!event.complianceImpact.includes(rule.regulation)) {
          event.complianceImpact.push(rule.regulation)
        }
        
        // Generate compliance alert
        this.generateComplianceAlert(rule, event)
      }
    })
  }

  // Generate compliance-specific alert
  private generateComplianceAlert(rule: ComplianceRule, event: SecurityEvent): void {
    const alert: SecurityAlert = {
      id: `alert_compliance_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
      type: 'compliance_violation',
      priority: rule.severity === 'critical' ? 'urgent' : rule.severity as 'high' | 'medium' | 'low',
      title: `${rule.regulation.toUpperCase()} Compliance Violation`,
      description: `${rule.name}: ${rule.description}`,
      timestamp: new Date().toISOString(),
      acknowledged: false,
      resolved: false,
      relatedEvents: [event.id],
      autoGenerated: true,
      confidenceScore: 0.9
    }

    this.alerts.set(alert.id, alert)
    this.notifyAlertListeners(alert)
  }

  // Evaluate event for auto-alert generation
  private evaluateForAutoAlert(event: SecurityEvent): void {
    const shouldGenerateAlert = 
      event.severity === 'critical' ||
      (event.severity === 'high' && !event.blocked) ||
      event.riskScore > this.config.alertThresholds.riskScoreThreshold ||
      event.complianceImpact.length > 0

    if (shouldGenerateAlert) {
      const alert: SecurityAlert = {
        id: `alert_auto_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
        type: 'critical_threat',
        priority: event.severity === 'critical' ? 'urgent' : 'high',
        title: `Security Threat Detected: ${event.eventType}`,
        description: event.description,
        timestamp: new Date().toISOString(),
        acknowledged: false,
        resolved: false,
        relatedEvents: [event.id],
        autoGenerated: true,
        confidenceScore: 0.8
      }

      this.alerts.set(alert.id, alert)
      this.notifyAlertListeners(alert)
    }
  }

  // Analyze security trends
  private analyzeSecurityTrends(): void {
    const recentEvents = Array.from(this.events.values())
      .filter(event => {
        const eventTime = new Date(event.timestamp).getTime()
        const hourAgo = Date.now() - 3600000
        return eventTime > hourAgo
      })

    // Check for coordinated attacks
    const attacksByIP = new Map<string, SecurityEvent[]>()
    recentEvents.forEach(event => {
      if (event.ipAddress) {
        if (!attacksByIP.has(event.ipAddress)) {
          attacksByIP.set(event.ipAddress, [])
        }
        attacksByIP.get(event.ipAddress)!.push(event)
      }
    })

    // Generate coordinated attack alerts
    attacksByIP.forEach((events, ipAddress) => {
      if (events.length >= this.config.alertThresholds.criticalEventRate) {
        this.generateCoordinatedAttackAlert(ipAddress, events)
      }
    })
  }

  // Generate coordinated attack alert
  private generateCoordinatedAttackAlert(ipAddress: string, events: SecurityEvent[]): void {
    const alert: SecurityAlert = {
      id: `alert_coordinated_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
      type: 'coordinated_attack',
      priority: 'urgent',
      title: `Coordinated Attack Detected`,
      description: `Multiple security events (${events.length}) detected from IP ${ipAddress} within the last hour`,
      timestamp: new Date().toISOString(),
      acknowledged: false,
      resolved: false,
      relatedEvents: events.map(e => e.id),
      autoGenerated: true,
      confidenceScore: 0.95
    }

    this.alerts.set(alert.id, alert)
    this.notifyAlertListeners(alert)
  }

  // Generate security report
  public generateSecurityReport(type: 'daily' | 'weekly' | 'monthly' | 'incident'): SecurityReport {
    const now = new Date()
    let startDate: Date
    
    switch (type) {
      case 'daily':
        startDate = new Date(now.getTime() - 86400000)
        break
      case 'weekly':
        startDate = new Date(now.getTime() - 604800000)
        break
      case 'monthly':
        startDate = new Date(now.getTime() - 2592000000)
        break
      default:
        startDate = new Date(now.getTime() - 86400000)
    }

    const periodEvents = Array.from(this.events.values())
      .filter(event => new Date(event.timestamp) >= startDate)
    
    const periodAlerts = Array.from(this.alerts.values())
      .filter(alert => new Date(alert.timestamp) >= startDate)

    const criticalEvents = periodEvents.filter(e => e.severity === 'critical')
    const blockedThreats = periodEvents.filter(e => e.blocked)
    
    const riskScore = periodEvents.length > 0 
      ? Math.round(periodEvents.reduce((sum, e) => sum + e.riskScore, 0) / periodEvents.length)
      : 0

    const complianceViolations = periodEvents.filter(e => e.complianceImpact.length > 0)
    const complianceScore = Math.max(0, 100 - (complianceViolations.length * 5))

    const report: SecurityReport = {
      id: `report_${type}_${Date.now()}`,
      type,
      title: `Security Report - ${type.charAt(0).toUpperCase() + type.slice(1)}`,
      generatedAt: new Date().toISOString(),
      period: {
        startDate: startDate.toISOString(),
        endDate: now.toISOString()
      },
      summary: {
        totalEvents: periodEvents.length,
        criticalEvents: criticalEvents.length,
        blockedThreats: blockedThreats.length,
        complianceScore,
        riskScore
      },
      events: periodEvents,
      alerts: periodAlerts,
      recommendations: this.generateRecommendations(periodEvents, periodAlerts),
      complianceStatus: this.getComplianceStatus()
    }

    return report
  }

  // Generate security recommendations
  private generateRecommendations(events: SecurityEvent[], alerts: SecurityAlert[]): string[] {
    const recommendations: string[] = []
    
    const criticalEvents = events.filter(e => e.severity === 'critical')
    const unblockedThreats = events.filter(e => !e.blocked)
    const complianceViolations = events.filter(e => e.complianceImpact.length > 0)

    if (criticalEvents.length > 5) {
      recommendations.push('Consider implementing additional security measures - critical events are occurring frequently')
    }

    if (unblockedThreats.length > 0) {
      recommendations.push('Review security rules - some threats are not being blocked')
    }

    if (complianceViolations.length > 0) {
      recommendations.push('Address compliance violations immediately to avoid regulatory issues')
    }

    if (alerts.filter(a => !a.resolved).length > 10) {
      recommendations.push('Increase security team capacity - unresolved alerts are accumulating')
    }

    return recommendations
  }

  // Get current compliance status
  private getComplianceStatus(): Record<string, 'compliant' | 'warning' | 'violation'> {
    const status: Record<string, 'compliant' | 'warning' | 'violation'> = {}
    
    this.complianceRules.forEach(rule => {
      if (rule.violationCount === 0) {
        status[rule.regulation] = 'compliant'
      } else if (rule.violationCount < 3) {
        status[rule.regulation] = 'warning'
      } else {
        status[rule.regulation] = 'violation'
      }
    })

    return status
  }

  // Get security metrics
  public getSecurityMetrics(): ThreatMetrics {
    const allEvents = Array.from(this.events.values())
    const blockedEvents = allEvents.filter(e => e.blocked)
    const activeIncidents = Array.from(this.alerts.values()).filter(a => !a.resolved).length

    // Calculate average risk score
    const avgRiskScore = allEvents.length > 0
      ? Math.round(allEvents.reduce((sum, e) => sum + e.riskScore, 0) / allEvents.length)
      : 0

    // Calculate compliance score
    const complianceViolations = allEvents.filter(e => e.complianceImpact.length > 0)
    const complianceScore = Math.max(0, 100 - (complianceViolations.length * 2))

    // Generate threat trends (last 24 hours, 6-hour intervals)
    const now = Date.now()
    const threatTrends = []
    
    for (let i = 0; i < 4; i++) {
      const periodStart = now - (86400000 - (i * 21600000))
      const periodEnd = periodStart + 21600000
      const periodEvents = allEvents.filter(e => {
        const eventTime = new Date(e.timestamp).getTime()
        return eventTime >= periodStart && eventTime < periodEnd
      })
      
      threatTrends.push({
        period: new Date(periodStart).toTimeString().substr(0, 5),
        count: periodEvents.length,
        severity: this.getMostCommonSeverity(periodEvents),
        blocked: periodEvents.filter(e => e.blocked).length
      })
    }

    // Get top threat types
    const threatTypeCount = new Map<string, number>()
    allEvents.forEach(event => {
      const count = threatTypeCount.get(event.eventType) || 0
      threatTypeCount.set(event.eventType, count + 1)
    })

    const topThreats = Array.from(threatTypeCount.entries())
      .sort((a, b) => b[1] - a[1])
      .slice(0, 5)
      .map(([type, count]) => ({
        type: type.replace('_', ' '),
        count,
        severity: this.getMostCommonSeverityForType(allEvents, type)
      }))

    return {
      totalThreats: allEvents.length,
      blockedThreats: blockedEvents.length,
      activeIncidents,
      riskScore: avgRiskScore,
      complianceScore,
      lastThreatTime: allEvents.length > 0 ? allEvents[allEvents.length - 1].timestamp : undefined,
      threatTrends,
      topThreats
    }
  }

  private getMostCommonSeverity(events: SecurityEvent[]): string {
    if (events.length === 0) return 'low'
    
    const severityCount = events.reduce((acc, event) => {
      acc[event.severity] = (acc[event.severity] || 0) + 1
      return acc
    }, {} as Record<string, number>)

    return Object.entries(severityCount)
      .sort((a, b) => b[1] - a[1])[0]?.[0] || 'low'
  }

  private getMostCommonSeverityForType(events: SecurityEvent[], eventType: string): string {
    const typeEvents = events.filter(e => e.eventType === eventType)
    return this.getMostCommonSeverity(typeEvents)
  }

  // Event listener management
  public addEventListener(eventType: string, callback: (event: SecurityEvent) => void): void {
    if (!this.eventListeners.has(eventType)) {
      this.eventListeners.set(eventType, [])
    }
    this.eventListeners.get(eventType)!.push(callback)
  }

  public addAlertListener(callback: (alert: SecurityAlert) => void): void {
    this.alertListeners.push(callback)
  }

  private notifyEventListeners(event: SecurityEvent): void {
    // Notify specific event type listeners
    const typeListeners = this.eventListeners.get(event.eventType)
    if (typeListeners) {
      typeListeners.forEach(callback => callback(event))
    }

    // Notify all event listeners
    const allListeners = this.eventListeners.get('*')
    if (allListeners) {
      allListeners.forEach(callback => callback(event))
    }
  }

  private notifyAlertListeners(alert: SecurityAlert): void {
    this.alertListeners.forEach(callback => callback(alert))
  }

  // Cleanup old events based on retention policy
  private cleanupOldEvents(): void {
    const retentionTime = Date.now() - (this.config.retentionPeriod * 86400000)
    
    Array.from(this.events.entries()).forEach(([id, event]) => {
      if (new Date(event.timestamp).getTime() < retentionTime) {
        this.events.delete(id)
      }
    })

    Array.from(this.alerts.entries()).forEach(([id, alert]) => {
      if (alert.resolved && new Date(alert.timestamp).getTime() < retentionTime) {
        this.alerts.delete(id)
      }
    })
  }

  // Get all events with optional filtering
  public getEvents(filter?: {
    eventType?: string
    severity?: string
    timeRange?: { start: string; end: string }
    userId?: string
    component?: string
  }): SecurityEvent[] {
    let events = Array.from(this.events.values())

    if (filter) {
      if (filter.eventType) {
        events = events.filter(e => e.eventType === filter.eventType)
      }
      if (filter.severity) {
        events = events.filter(e => e.severity === filter.severity)
      }
      if (filter.timeRange) {
        const start = new Date(filter.timeRange.start).getTime()
        const end = new Date(filter.timeRange.end).getTime()
        events = events.filter(e => {
          const eventTime = new Date(e.timestamp).getTime()
          return eventTime >= start && eventTime <= end
        })
      }
      if (filter.userId) {
        events = events.filter(e => e.userId === filter.userId)
      }
      if (filter.component) {
        events = events.filter(e => e.component === filter.component)
      }
    }

    return events.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime())
  }

  // Get all alerts with optional filtering
  public getAlerts(filter?: {
    type?: string
    priority?: string
    resolved?: boolean
    acknowledged?: boolean
  }): SecurityAlert[] {
    let alerts = Array.from(this.alerts.values())

    if (filter) {
      if (filter.type) {
        alerts = alerts.filter(a => a.type === filter.type)
      }
      if (filter.priority) {
        alerts = alerts.filter(a => a.priority === filter.priority)
      }
      if (filter.resolved !== undefined) {
        alerts = alerts.filter(a => a.resolved === filter.resolved)
      }
      if (filter.acknowledged !== undefined) {
        alerts = alerts.filter(a => a.acknowledged === filter.acknowledged)
      }
    }

    return alerts.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime())
  }

  // Update configuration
  public updateConfig(config: Partial<SecurityMonitoringConfig>): void {
    this.config = { ...this.config, ...config }
  }

  // Get current configuration
  public getConfig(): SecurityMonitoringConfig {
    return { ...this.config }
  }
}

// Global security monitoring instance
export const globalSecurityMonitoring = new SecurityMonitoringService()