apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: epsx-dev

resources:
  - ../../base
  - pvcs.yaml

images:
  - name: registry.jesadakorn.com/jesadakorn/epsx/backend
    newTag: dev-latest
  - name: registry.jesadakorn.com/jesadakorn/epsx/frontend
    newTag: dev-latest
  - name: registry.jesadakorn.com/jesadakorn/epsx/admin
    newTag: dev-latest

patches:
  - path: patches/resources.yaml
  - path: patches/postgres-conf.yaml
  - path: patches/redis-conf.yaml
