// @generated automatically by Diesel CLI.

diesel::table! {
    use diesel::sql_types::*;

    /// Representation of the `aggregate_snapshots` table.
    ///
    /// (Automatically generated by Diesel.)
    aggregate_snapshots (aggregate_id) {
        /// The `aggregate_id` column of the `aggregate_snapshots` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        aggregate_id -> Varchar,
        /// The `aggregate_type` column of the `aggregate_snapshots` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        aggregate_type -> Varchar,
        /// The `aggregate_version` column of the `aggregate_snapshots` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        aggregate_version -> Int8,
        /// The `snapshot_data` column of the `aggregate_snapshots` table.
        ///
        /// Its SQL type is `Jsonb`.
        ///
        /// (Automatically generated by Diesel.)
        snapshot_data -> Jsonb,
        /// The `created_at` column of the `aggregate_snapshots` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `event_count_at_snapshot` column of the `aggregate_snapshots` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        event_count_at_snapshot -> Int4,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// API usage tracking (partitioned by month) - high write volume
    api_key_usage_logs (id, request_at) {
        /// The `id` column of the `api_key_usage_logs` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `api_key_id` column of the `api_key_usage_logs` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        api_key_id -> Uuid,
        /// The `module_id` column of the `api_key_usage_logs` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        module_id -> Nullable<Uuid>,
        /// The `endpoint` column of the `api_key_usage_logs` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        endpoint -> Varchar,
        /// The `method` column of the `api_key_usage_logs` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 10]
        method -> Varchar,
        /// The `response_status` column of the `api_key_usage_logs` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        response_status -> Nullable<Int4>,
        /// The `response_time_ms` column of the `api_key_usage_logs` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        response_time_ms -> Nullable<Int4>,
        /// The `ip_address` column of the `api_key_usage_logs` table.
        ///
        /// Its SQL type is `Nullable<Inet>`.
        ///
        /// (Automatically generated by Diesel.)
        ip_address -> Nullable<Inet>,
        /// The `user_agent` column of the `api_key_usage_logs` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_agent -> Nullable<Text>,
        /// The `request_at` column of the `api_key_usage_logs` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        request_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Representation of the `api_key_usage_logs_2025_01` table.
    ///
    /// (Automatically generated by Diesel.)
    api_key_usage_logs_2025_01 (id, request_at) {
        /// The `id` column of the `api_key_usage_logs_2025_01` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `api_key_id` column of the `api_key_usage_logs_2025_01` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        api_key_id -> Uuid,
        /// The `module_id` column of the `api_key_usage_logs_2025_01` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        module_id -> Nullable<Uuid>,
        /// The `endpoint` column of the `api_key_usage_logs_2025_01` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        endpoint -> Varchar,
        /// The `method` column of the `api_key_usage_logs_2025_01` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 10]
        method -> Varchar,
        /// The `response_status` column of the `api_key_usage_logs_2025_01` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        response_status -> Nullable<Int4>,
        /// The `response_time_ms` column of the `api_key_usage_logs_2025_01` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        response_time_ms -> Nullable<Int4>,
        /// The `ip_address` column of the `api_key_usage_logs_2025_01` table.
        ///
        /// Its SQL type is `Nullable<Inet>`.
        ///
        /// (Automatically generated by Diesel.)
        ip_address -> Nullable<Inet>,
        /// The `user_agent` column of the `api_key_usage_logs_2025_01` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_agent -> Nullable<Text>,
        /// The `request_at` column of the `api_key_usage_logs_2025_01` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        request_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Representation of the `api_key_usage_logs_2025_02` table.
    ///
    /// (Automatically generated by Diesel.)
    api_key_usage_logs_2025_02 (id, request_at) {
        /// The `id` column of the `api_key_usage_logs_2025_02` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `api_key_id` column of the `api_key_usage_logs_2025_02` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        api_key_id -> Uuid,
        /// The `module_id` column of the `api_key_usage_logs_2025_02` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        module_id -> Nullable<Uuid>,
        /// The `endpoint` column of the `api_key_usage_logs_2025_02` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        endpoint -> Varchar,
        /// The `method` column of the `api_key_usage_logs_2025_02` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 10]
        method -> Varchar,
        /// The `response_status` column of the `api_key_usage_logs_2025_02` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        response_status -> Nullable<Int4>,
        /// The `response_time_ms` column of the `api_key_usage_logs_2025_02` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        response_time_ms -> Nullable<Int4>,
        /// The `ip_address` column of the `api_key_usage_logs_2025_02` table.
        ///
        /// Its SQL type is `Nullable<Inet>`.
        ///
        /// (Automatically generated by Diesel.)
        ip_address -> Nullable<Inet>,
        /// The `user_agent` column of the `api_key_usage_logs_2025_02` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_agent -> Nullable<Text>,
        /// The `request_at` column of the `api_key_usage_logs_2025_02` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        request_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Representation of the `api_key_usage_logs_2025_03` table.
    ///
    /// (Automatically generated by Diesel.)
    api_key_usage_logs_2025_03 (id, request_at) {
        /// The `id` column of the `api_key_usage_logs_2025_03` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `api_key_id` column of the `api_key_usage_logs_2025_03` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        api_key_id -> Uuid,
        /// The `module_id` column of the `api_key_usage_logs_2025_03` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        module_id -> Nullable<Uuid>,
        /// The `endpoint` column of the `api_key_usage_logs_2025_03` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        endpoint -> Varchar,
        /// The `method` column of the `api_key_usage_logs_2025_03` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 10]
        method -> Varchar,
        /// The `response_status` column of the `api_key_usage_logs_2025_03` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        response_status -> Nullable<Int4>,
        /// The `response_time_ms` column of the `api_key_usage_logs_2025_03` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        response_time_ms -> Nullable<Int4>,
        /// The `ip_address` column of the `api_key_usage_logs_2025_03` table.
        ///
        /// Its SQL type is `Nullable<Inet>`.
        ///
        /// (Automatically generated by Diesel.)
        ip_address -> Nullable<Inet>,
        /// The `user_agent` column of the `api_key_usage_logs_2025_03` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_agent -> Nullable<Text>,
        /// The `request_at` column of the `api_key_usage_logs_2025_03` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        request_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Representation of the `api_key_usage_logs_2025_04` table.
    ///
    /// (Automatically generated by Diesel.)
    api_key_usage_logs_2025_04 (id, request_at) {
        /// The `id` column of the `api_key_usage_logs_2025_04` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `api_key_id` column of the `api_key_usage_logs_2025_04` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        api_key_id -> Uuid,
        /// The `module_id` column of the `api_key_usage_logs_2025_04` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        module_id -> Nullable<Uuid>,
        /// The `endpoint` column of the `api_key_usage_logs_2025_04` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        endpoint -> Varchar,
        /// The `method` column of the `api_key_usage_logs_2025_04` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 10]
        method -> Varchar,
        /// The `response_status` column of the `api_key_usage_logs_2025_04` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        response_status -> Nullable<Int4>,
        /// The `response_time_ms` column of the `api_key_usage_logs_2025_04` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        response_time_ms -> Nullable<Int4>,
        /// The `ip_address` column of the `api_key_usage_logs_2025_04` table.
        ///
        /// Its SQL type is `Nullable<Inet>`.
        ///
        /// (Automatically generated by Diesel.)
        ip_address -> Nullable<Inet>,
        /// The `user_agent` column of the `api_key_usage_logs_2025_04` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_agent -> Nullable<Text>,
        /// The `request_at` column of the `api_key_usage_logs_2025_04` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        request_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Representation of the `api_key_usage_logs_2025_05` table.
    ///
    /// (Automatically generated by Diesel.)
    api_key_usage_logs_2025_05 (id, request_at) {
        /// The `id` column of the `api_key_usage_logs_2025_05` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `api_key_id` column of the `api_key_usage_logs_2025_05` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        api_key_id -> Uuid,
        /// The `module_id` column of the `api_key_usage_logs_2025_05` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        module_id -> Nullable<Uuid>,
        /// The `endpoint` column of the `api_key_usage_logs_2025_05` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        endpoint -> Varchar,
        /// The `method` column of the `api_key_usage_logs_2025_05` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 10]
        method -> Varchar,
        /// The `response_status` column of the `api_key_usage_logs_2025_05` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        response_status -> Nullable<Int4>,
        /// The `response_time_ms` column of the `api_key_usage_logs_2025_05` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        response_time_ms -> Nullable<Int4>,
        /// The `ip_address` column of the `api_key_usage_logs_2025_05` table.
        ///
        /// Its SQL type is `Nullable<Inet>`.
        ///
        /// (Automatically generated by Diesel.)
        ip_address -> Nullable<Inet>,
        /// The `user_agent` column of the `api_key_usage_logs_2025_05` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_agent -> Nullable<Text>,
        /// The `request_at` column of the `api_key_usage_logs_2025_05` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        request_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Representation of the `api_key_usage_logs_2025_06` table.
    ///
    /// (Automatically generated by Diesel.)
    api_key_usage_logs_2025_06 (id, request_at) {
        /// The `id` column of the `api_key_usage_logs_2025_06` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `api_key_id` column of the `api_key_usage_logs_2025_06` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        api_key_id -> Uuid,
        /// The `module_id` column of the `api_key_usage_logs_2025_06` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        module_id -> Nullable<Uuid>,
        /// The `endpoint` column of the `api_key_usage_logs_2025_06` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        endpoint -> Varchar,
        /// The `method` column of the `api_key_usage_logs_2025_06` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 10]
        method -> Varchar,
        /// The `response_status` column of the `api_key_usage_logs_2025_06` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        response_status -> Nullable<Int4>,
        /// The `response_time_ms` column of the `api_key_usage_logs_2025_06` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        response_time_ms -> Nullable<Int4>,
        /// The `ip_address` column of the `api_key_usage_logs_2025_06` table.
        ///
        /// Its SQL type is `Nullable<Inet>`.
        ///
        /// (Automatically generated by Diesel.)
        ip_address -> Nullable<Inet>,
        /// The `user_agent` column of the `api_key_usage_logs_2025_06` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_agent -> Nullable<Text>,
        /// The `request_at` column of the `api_key_usage_logs_2025_06` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        request_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Representation of the `api_key_usage_logs_2025_07` table.
    ///
    /// (Automatically generated by Diesel.)
    api_key_usage_logs_2025_07 (id, request_at) {
        /// The `id` column of the `api_key_usage_logs_2025_07` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `api_key_id` column of the `api_key_usage_logs_2025_07` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        api_key_id -> Uuid,
        /// The `module_id` column of the `api_key_usage_logs_2025_07` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        module_id -> Nullable<Uuid>,
        /// The `endpoint` column of the `api_key_usage_logs_2025_07` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        endpoint -> Varchar,
        /// The `method` column of the `api_key_usage_logs_2025_07` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 10]
        method -> Varchar,
        /// The `response_status` column of the `api_key_usage_logs_2025_07` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        response_status -> Nullable<Int4>,
        /// The `response_time_ms` column of the `api_key_usage_logs_2025_07` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        response_time_ms -> Nullable<Int4>,
        /// The `ip_address` column of the `api_key_usage_logs_2025_07` table.
        ///
        /// Its SQL type is `Nullable<Inet>`.
        ///
        /// (Automatically generated by Diesel.)
        ip_address -> Nullable<Inet>,
        /// The `user_agent` column of the `api_key_usage_logs_2025_07` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_agent -> Nullable<Text>,
        /// The `request_at` column of the `api_key_usage_logs_2025_07` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        request_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Representation of the `api_key_usage_logs_2025_08` table.
    ///
    /// (Automatically generated by Diesel.)
    api_key_usage_logs_2025_08 (id, request_at) {
        /// The `id` column of the `api_key_usage_logs_2025_08` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `api_key_id` column of the `api_key_usage_logs_2025_08` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        api_key_id -> Uuid,
        /// The `module_id` column of the `api_key_usage_logs_2025_08` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        module_id -> Nullable<Uuid>,
        /// The `endpoint` column of the `api_key_usage_logs_2025_08` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        endpoint -> Varchar,
        /// The `method` column of the `api_key_usage_logs_2025_08` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 10]
        method -> Varchar,
        /// The `response_status` column of the `api_key_usage_logs_2025_08` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        response_status -> Nullable<Int4>,
        /// The `response_time_ms` column of the `api_key_usage_logs_2025_08` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        response_time_ms -> Nullable<Int4>,
        /// The `ip_address` column of the `api_key_usage_logs_2025_08` table.
        ///
        /// Its SQL type is `Nullable<Inet>`.
        ///
        /// (Automatically generated by Diesel.)
        ip_address -> Nullable<Inet>,
        /// The `user_agent` column of the `api_key_usage_logs_2025_08` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_agent -> Nullable<Text>,
        /// The `request_at` column of the `api_key_usage_logs_2025_08` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        request_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Representation of the `api_key_usage_logs_2025_09` table.
    ///
    /// (Automatically generated by Diesel.)
    api_key_usage_logs_2025_09 (id, request_at) {
        /// The `id` column of the `api_key_usage_logs_2025_09` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `api_key_id` column of the `api_key_usage_logs_2025_09` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        api_key_id -> Uuid,
        /// The `module_id` column of the `api_key_usage_logs_2025_09` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        module_id -> Nullable<Uuid>,
        /// The `endpoint` column of the `api_key_usage_logs_2025_09` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        endpoint -> Varchar,
        /// The `method` column of the `api_key_usage_logs_2025_09` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 10]
        method -> Varchar,
        /// The `response_status` column of the `api_key_usage_logs_2025_09` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        response_status -> Nullable<Int4>,
        /// The `response_time_ms` column of the `api_key_usage_logs_2025_09` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        response_time_ms -> Nullable<Int4>,
        /// The `ip_address` column of the `api_key_usage_logs_2025_09` table.
        ///
        /// Its SQL type is `Nullable<Inet>`.
        ///
        /// (Automatically generated by Diesel.)
        ip_address -> Nullable<Inet>,
        /// The `user_agent` column of the `api_key_usage_logs_2025_09` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_agent -> Nullable<Text>,
        /// The `request_at` column of the `api_key_usage_logs_2025_09` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        request_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Representation of the `api_key_usage_logs_2025_10` table.
    ///
    /// (Automatically generated by Diesel.)
    api_key_usage_logs_2025_10 (id, request_at) {
        /// The `id` column of the `api_key_usage_logs_2025_10` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `api_key_id` column of the `api_key_usage_logs_2025_10` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        api_key_id -> Uuid,
        /// The `module_id` column of the `api_key_usage_logs_2025_10` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        module_id -> Nullable<Uuid>,
        /// The `endpoint` column of the `api_key_usage_logs_2025_10` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        endpoint -> Varchar,
        /// The `method` column of the `api_key_usage_logs_2025_10` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 10]
        method -> Varchar,
        /// The `response_status` column of the `api_key_usage_logs_2025_10` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        response_status -> Nullable<Int4>,
        /// The `response_time_ms` column of the `api_key_usage_logs_2025_10` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        response_time_ms -> Nullable<Int4>,
        /// The `ip_address` column of the `api_key_usage_logs_2025_10` table.
        ///
        /// Its SQL type is `Nullable<Inet>`.
        ///
        /// (Automatically generated by Diesel.)
        ip_address -> Nullable<Inet>,
        /// The `user_agent` column of the `api_key_usage_logs_2025_10` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_agent -> Nullable<Text>,
        /// The `request_at` column of the `api_key_usage_logs_2025_10` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        request_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Representation of the `api_key_usage_logs_2025_11` table.
    ///
    /// (Automatically generated by Diesel.)
    api_key_usage_logs_2025_11 (id, request_at) {
        /// The `id` column of the `api_key_usage_logs_2025_11` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `api_key_id` column of the `api_key_usage_logs_2025_11` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        api_key_id -> Uuid,
        /// The `module_id` column of the `api_key_usage_logs_2025_11` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        module_id -> Nullable<Uuid>,
        /// The `endpoint` column of the `api_key_usage_logs_2025_11` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        endpoint -> Varchar,
        /// The `method` column of the `api_key_usage_logs_2025_11` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 10]
        method -> Varchar,
        /// The `response_status` column of the `api_key_usage_logs_2025_11` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        response_status -> Nullable<Int4>,
        /// The `response_time_ms` column of the `api_key_usage_logs_2025_11` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        response_time_ms -> Nullable<Int4>,
        /// The `ip_address` column of the `api_key_usage_logs_2025_11` table.
        ///
        /// Its SQL type is `Nullable<Inet>`.
        ///
        /// (Automatically generated by Diesel.)
        ip_address -> Nullable<Inet>,
        /// The `user_agent` column of the `api_key_usage_logs_2025_11` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_agent -> Nullable<Text>,
        /// The `request_at` column of the `api_key_usage_logs_2025_11` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        request_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Representation of the `api_key_usage_logs_2025_12` table.
    ///
    /// (Automatically generated by Diesel.)
    api_key_usage_logs_2025_12 (id, request_at) {
        /// The `id` column of the `api_key_usage_logs_2025_12` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `api_key_id` column of the `api_key_usage_logs_2025_12` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        api_key_id -> Uuid,
        /// The `module_id` column of the `api_key_usage_logs_2025_12` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        module_id -> Nullable<Uuid>,
        /// The `endpoint` column of the `api_key_usage_logs_2025_12` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        endpoint -> Varchar,
        /// The `method` column of the `api_key_usage_logs_2025_12` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 10]
        method -> Varchar,
        /// The `response_status` column of the `api_key_usage_logs_2025_12` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        response_status -> Nullable<Int4>,
        /// The `response_time_ms` column of the `api_key_usage_logs_2025_12` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        response_time_ms -> Nullable<Int4>,
        /// The `ip_address` column of the `api_key_usage_logs_2025_12` table.
        ///
        /// Its SQL type is `Nullable<Inet>`.
        ///
        /// (Automatically generated by Diesel.)
        ip_address -> Nullable<Inet>,
        /// The `user_agent` column of the `api_key_usage_logs_2025_12` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_agent -> Nullable<Text>,
        /// The `request_at` column of the `api_key_usage_logs_2025_12` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        request_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Audit trail for subscription/assignment modifications
    assignment_audit_log (id) {
        /// The `id` column of the `assignment_audit_log` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `assignment_id` column of the `assignment_audit_log` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        assignment_id -> Uuid,
        /// The `action` column of the `assignment_audit_log` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        action -> Varchar,
        /// The `old_value` column of the `assignment_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        old_value -> Nullable<Text>,
        /// The `new_value` column of the `assignment_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        new_value -> Nullable<Text>,
        /// The `reason` column of the `assignment_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        reason -> Nullable<Text>,
        /// The `performed_by` column of the `assignment_audit_log` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        performed_by -> Varchar,
        /// The `performed_at` column of the `assignment_audit_log` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        performed_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Immutable event log for event sourcing
    event_store (event_id) {
        /// The `event_id` column of the `event_store` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        event_id -> Uuid,
        /// The `aggregate_id` column of the `event_store` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        aggregate_id -> Varchar,
        /// The `aggregate_type` column of the `event_store` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        aggregate_type -> Varchar,
        /// The `aggregate_version` column of the `event_store` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        aggregate_version -> Int8,
        /// The `event_type` column of the `event_store` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        event_type -> Varchar,
        /// The `event_data` column of the `event_store` table.
        ///
        /// Its SQL type is `Jsonb`.
        ///
        /// (Automatically generated by Diesel.)
        event_data -> Jsonb,
        /// The `metadata` column of the `event_store` table.
        ///
        /// Its SQL type is `Jsonb`.
        ///
        /// (Automatically generated by Diesel.)
        metadata -> Jsonb,
        /// The `occurred_at` column of the `event_store` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        occurred_at -> Timestamptz,
        /// The `causation_id` column of the `event_store` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        causation_id -> Nullable<Uuid>,
        /// The `correlation_id` column of the `event_store` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        correlation_id -> Nullable<Uuid>,
        /// The `user_id` column of the `event_store` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        user_id -> Nullable<Varchar>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Transactional outbox for reliable event publishing
    outbox_events (id) {
        /// The `id` column of the `outbox_events` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int8,
        /// The `event_id` column of the `outbox_events` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        event_id -> Uuid,
        /// The `aggregate_id` column of the `outbox_events` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        aggregate_id -> Varchar,
        /// The `aggregate_type` column of the `outbox_events` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        aggregate_type -> Varchar,
        /// The `event_type` column of the `outbox_events` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        event_type -> Varchar,
        /// The `event_payload` column of the `outbox_events` table.
        ///
        /// Its SQL type is `Jsonb`.
        ///
        /// (Automatically generated by Diesel.)
        event_payload -> Jsonb,
        /// The `processed` column of the `outbox_events` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        processed -> Bool,
        /// The `processed_at` column of the `outbox_events` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        processed_at -> Nullable<Timestamptz>,
        /// The `retry_count` column of the `outbox_events` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        retry_count -> Int4,
        /// The `last_error` column of the `outbox_events` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        last_error -> Nullable<Text>,
        /// The `next_retry_at` column of the `outbox_events` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        next_retry_at -> Nullable<Timestamptz>,
        /// The `created_at` column of the `outbox_events` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `sequence_number` column of the `outbox_events` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        sequence_number -> Int8,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Audit trail for payment status changes
    payment_audit_log (id) {
        /// The `id` column of the `payment_audit_log` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `payment_id` column of the `payment_audit_log` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        payment_id -> Uuid,
        /// The `action` column of the `payment_audit_log` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        action -> Varchar,
        /// The `old_status` column of the `payment_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        old_status -> Nullable<Varchar>,
        /// The `new_status` column of the `payment_audit_log` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        new_status -> Varchar,
        /// The `reason` column of the `payment_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        reason -> Nullable<Text>,
        /// The `performed_by` column of the `payment_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        performed_by -> Nullable<Varchar>,
        /// The `performed_at` column of the `payment_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        performed_at -> Nullable<Timestamptz>,
        /// The `metadata` column of the `payment_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        metadata -> Nullable<Jsonb>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Audit trail for permission changes
    permission_audit_log (id) {
        /// The `id` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `event_type` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        event_type -> Varchar,
        /// The `event_timestamp` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        event_timestamp -> Timestamptz,
        /// The `event_source` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        event_source -> Varchar,
        /// The `wallet_address` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        wallet_address -> Varchar,
        /// The `permission_string` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        permission_string -> Nullable<Varchar>,
        /// The `permission_id` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        permission_id -> Nullable<Uuid>,
        /// The `group_id` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        group_id -> Nullable<Uuid>,
        /// The `group_name` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        group_name -> Nullable<Varchar>,
        /// The `performed_by` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        performed_by -> Nullable<Varchar>,
        /// The `performed_by_name` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        performed_by_name -> Nullable<Varchar>,
        /// The `reason` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        reason -> Nullable<Text>,
        /// The `request_id` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 36]
        request_id -> Nullable<Varchar>,
        /// The `ip_address` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Inet>`.
        ///
        /// (Automatically generated by Diesel.)
        ip_address -> Nullable<Inet>,
        /// The `user_agent` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_agent -> Nullable<Text>,
        /// The `previous_state` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        previous_state -> Nullable<Jsonb>,
        /// The `new_state` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        new_state -> Nullable<Jsonb>,
        /// The `expires_at` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Nullable<Timestamptz>,
        /// The `valid_from` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        valid_from -> Nullable<Timestamptz>,
        /// The `valid_until` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        valid_until -> Nullable<Timestamptz>,
        /// The `metadata` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        metadata -> Nullable<Jsonb>,
    }
}

diesel::joinable!(outbox_events -> event_store (event_id));

diesel::allow_tables_to_appear_in_same_query!(
    aggregate_snapshots,
    api_key_usage_logs,
    api_key_usage_logs_2025_01,
    api_key_usage_logs_2025_02,
    api_key_usage_logs_2025_03,
    api_key_usage_logs_2025_04,
    api_key_usage_logs_2025_05,
    api_key_usage_logs_2025_06,
    api_key_usage_logs_2025_07,
    api_key_usage_logs_2025_08,
    api_key_usage_logs_2025_09,
    api_key_usage_logs_2025_10,
    api_key_usage_logs_2025_11,
    api_key_usage_logs_2025_12,
    assignment_audit_log,
    event_store,
    outbox_events,
    payment_audit_log,
    permission_audit_log,
);
