// @generated automatically by Diesel CLI.

diesel::table! {
    use diesel::sql_types::*;

    /// Representation of the `notifications` table.
    ///
    /// (Automatically generated by Diesel.)
    notifications (id) {
        /// The `id` column of the `notifications` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 66]
        id -> Varchar,
        /// The `user_id` column of the `notifications` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 66]
        user_id -> Nullable<Varchar>,
        /// The `channel` column of the `notifications` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        channel -> Varchar,
        /// The `recipient` column of the `notifications` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        recipient -> Varchar,
        /// The `template_id` column of the `notifications` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 66]
        template_id -> Nullable<Varchar>,
        /// The `subject` column of the `notifications` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        subject -> Nullable<Text>,
        /// The `body` column of the `notifications` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        body -> Text,
        /// The `data` column of the `notifications` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        data -> Nullable<Jsonb>,
        /// The `status` column of the `notifications` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        status -> Varchar,
        /// The `error` column of the `notifications` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        error -> Nullable<Text>,
        /// The `sent_at` column of the `notifications` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        sent_at -> Nullable<Timestamptz>,
        /// The `created_at` column of the `notifications` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `read_at` column of the `notifications` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        read_at -> Nullable<Timestamptz>,
        /// The `title` column of the `notifications` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        title -> Nullable<Text>,
        /// The `notification_type` column of the `notifications` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        notification_type -> Nullable<Varchar>,
        /// The `priority` column of the `notifications` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        priority -> Nullable<Varchar>,
        /// The `action_url` column of the `notifications` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        action_url -> Nullable<Text>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Notifications for wallet users with multi-channel delivery tracking
    wallet_notifications (id) {
        /// The `id` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `recipient_wallet_address` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        recipient_wallet_address -> Nullable<Varchar>,
        /// The `topic_name` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        topic_name -> Nullable<Varchar>,
        /// The `title` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        title -> Text,
        /// The `body` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        body -> Text,
        /// The `urgency` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        urgency -> Varchar,
        /// The `notification_type` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        notification_type -> Varchar,
        /// The `priority` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        priority -> Varchar,
        /// The `channels` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Jsonb`.
        ///
        /// (Automatically generated by Diesel.)
        channels -> Jsonb,
        /// The `schedule_type` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        schedule_type -> Varchar,
        /// The `scheduled_at` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        scheduled_at -> Nullable<Timestamptz>,
        /// The `expires_at` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Nullable<Timestamptz>,
        /// The `status` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        status -> Varchar,
        /// The `send_started_at` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        send_started_at -> Nullable<Timestamptz>,
        /// The `channel_status` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Jsonb`.
        ///
        /// (Automatically generated by Diesel.)
        channel_status -> Jsonb,
        /// The `total_attempts` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        total_attempts -> Int4,
        /// The `created_by` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        created_by -> Nullable<Varchar>,
        /// The `image_url` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        image_url -> Nullable<Text>,
        /// The `action_url` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        action_url -> Nullable<Text>,
        /// The `data_payload` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        data_payload -> Nullable<Jsonb>,
        /// The `tags` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Array<Nullable<Text>>>`.
        ///
        /// (Automatically generated by Diesel.)
        tags -> Nullable<Array<Nullable<Text>>>,
        /// The `notes` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        notes -> Nullable<Text>,
        /// The `version` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        version -> Int4,
        /// The `created_at` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
    }
}

diesel::allow_tables_to_appear_in_same_query!(notifications, wallet_notifications,);
