// @generated automatically by Diesel CLI.

diesel::table! {
    use diesel::sql_types::*;

    /// Tracks active SSE connections for multi-instance Redis pub/sub
    notification_subscriptions (id) {
        /// The `id` column of the `notification_subscriptions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `wallet_address` column of the `notification_subscriptions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        wallet_address -> Varchar,
        /// The `instance_id` column of the `notification_subscriptions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        instance_id -> Varchar,
        /// The `connection_id` column of the `notification_subscriptions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        connection_id -> Varchar,
        /// The `connected_at` column of the `notification_subscriptions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        connected_at -> Timestamptz,
        /// The `last_ping_at` column of the `notification_subscriptions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        last_ping_at -> Timestamptz,
        /// The `disconnected_at` column of the `notification_subscriptions` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        disconnected_at -> Nullable<Timestamptz>,
        /// The `user_agent` column of the `notification_subscriptions` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_agent -> Nullable<Text>,
        /// The `ip_address` column of the `notification_subscriptions` table.
        ///
        /// Its SQL type is `Nullable<Inet>`.
        ///
        /// (Automatically generated by Diesel.)
        ip_address -> Nullable<Inet>,
        /// The `redis_channel` column of the `notification_subscriptions` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 200]
        redis_channel -> Nullable<Varchar>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Real-time notifications with SSE delivery tracking
    wallet_notifications (id) {
        /// The `id` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `wallet_address` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        wallet_address -> Varchar,
        /// The `notification_type` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        notification_type -> Varchar,
        /// The `title` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        title -> Varchar,
        /// The `message` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        message -> Text,
        /// The `data` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        data -> Nullable<Jsonb>,
        /// The `priority` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        priority -> Varchar,
        /// The `timestamp` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        timestamp -> Timestamptz,
        /// The `expires_at` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Nullable<Timestamptz>,
        /// The `read_at` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        read_at -> Nullable<Timestamptz>,
        /// The `clicked_at` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        clicked_at -> Nullable<Timestamptz>,
        /// The `delivered_at` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        delivered_at -> Nullable<Timestamptz>,
        /// The `action_url` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 500]
        action_url -> Nullable<Varchar>,
        /// The `image_url` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 500]
        image_url -> Nullable<Varchar>,
        /// The `created_at` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// The `queued_at` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        queued_at -> Nullable<Timestamptz>,
        /// The `delivery_attempts` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        delivery_attempts -> Nullable<Int4>,
        /// The `last_delivery_attempt_at` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        last_delivery_attempt_at -> Nullable<Timestamptz>,
        /// The `delivery_error` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        delivery_error -> Nullable<Text>,
        /// The `acknowledged_at` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        acknowledged_at -> Nullable<Timestamptz>,
        /// The `deleted_at` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        deleted_at -> Nullable<Timestamptz>,
    }
}

diesel::allow_tables_to_appear_in_same_query!(notification_subscriptions, wallet_notifications,);
