// @generated automatically by Diesel CLI.

diesel::table! {
    use diesel::sql_types::*;

    /// Credit transaction history with full audit trail
    credit_transactions (id) {
        /// The `id` column of the `credit_transactions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `wallet_address` column of the `credit_transactions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        wallet_address -> Varchar,
        /// The `amount` column of the `credit_transactions` table.
        ///
        /// Its SQL type is `Numeric`.
        ///
        /// (Automatically generated by Diesel.)
        amount -> Numeric,
        /// The `balance_after` column of the `credit_transactions` table.
        ///
        /// Its SQL type is `Numeric`.
        ///
        /// (Automatically generated by Diesel.)
        balance_after -> Numeric,
        /// The `tx_type` column of the `credit_transactions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 30]
        tx_type -> Varchar,
        /// The `reference_id` column of the `credit_transactions` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        reference_id -> Nullable<Uuid>,
        /// The `reference_type` column of the `credit_transactions` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 30]
        reference_type -> Nullable<Varchar>,
        /// The `reason` column of the `credit_transactions` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        reason -> Nullable<Text>,
        /// The `granted_by` column of the `credit_transactions` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        granted_by -> Nullable<Varchar>,
        /// The `expires_at` column of the `credit_transactions` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Nullable<Timestamptz>,
        /// The `metadata` column of the `credit_transactions` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        metadata -> Nullable<Jsonb>,
        /// The `created_at` column of the `credit_transactions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Audit trail of payment status changes
    payment_audit_log (id) {
        /// The `id` column of the `payment_audit_log` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `payment_id` column of the `payment_audit_log` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        payment_id -> Uuid,
        /// The `action` column of the `payment_audit_log` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        action -> Varchar,
        /// The `old_status` column of the `payment_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        old_status -> Nullable<Varchar>,
        /// The `new_status` column of the `payment_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        new_status -> Nullable<Varchar>,
        /// The `reason` column of the `payment_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        reason -> Nullable<Text>,
        /// The `performed_by` column of the `payment_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        performed_by -> Nullable<Varchar>,
        /// The `metadata` column of the `payment_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        metadata -> Nullable<Jsonb>,
        /// The `created_at` column of the `payment_audit_log` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Dynamic payment links for context-based purchases (V2 payment system)
    payment_contexts (id) {
        /// The `id` column of the `payment_contexts` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `context_type` column of the `payment_contexts` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        context_type -> Varchar,
        /// The `context_id` column of the `payment_contexts` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        context_id -> Nullable<Uuid>,
        /// The `slug` column of the `payment_contexts` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        slug -> Varchar,
        /// The `name` column of the `payment_contexts` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        name -> Varchar,
        /// The `description` column of the `payment_contexts` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Nullable<Text>,
        /// The `amount` column of the `payment_contexts` table.
        ///
        /// Its SQL type is `Numeric`.
        ///
        /// (Automatically generated by Diesel.)
        amount -> Numeric,
        /// The `currency` column of the `payment_contexts` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 10]
        currency -> Varchar,
        /// The `expires_at` column of the `payment_contexts` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Nullable<Timestamptz>,
        /// The `max_uses` column of the `payment_contexts` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        max_uses -> Nullable<Int4>,
        /// The `current_uses` column of the `payment_contexts` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        current_uses -> Int4,
        /// The `is_active` column of the `payment_contexts` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_active -> Bool,
        /// The `created_by` column of the `payment_contexts` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        created_by -> Varchar,
        /// The `metadata` column of the `payment_contexts` table.
        ///
        /// Its SQL type is `Jsonb`.
        ///
        /// (Automatically generated by Diesel.)
        metadata -> Jsonb,
        /// The `version` column of the `payment_contexts` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        version -> Int8,
        /// The `created_at` column of the `payment_contexts` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `payment_contexts` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Core payment tracking for blockchain transactions
    payments (id) {
        /// The `id` column of the `payments` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `payment_reference` column of the `payments` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        payment_reference -> Varchar,
        /// The `transaction_hash` column of the `payments` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 66]
        transaction_hash -> Nullable<Varchar>,
        /// The `wallet_address` column of the `payments` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        wallet_address -> Varchar,
        /// The `amount` column of the `payments` table.
        ///
        /// Its SQL type is `Numeric`.
        ///
        /// (Automatically generated by Diesel.)
        amount -> Numeric,
        /// The `currency` column of the `payments` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 10]
        currency -> Varchar,
        /// The `method` column of the `payments` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        method -> Varchar,
        /// The `status` column of the `payments` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        status -> Varchar,
        /// The `plan_id` column of the `payments` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        plan_id -> Uuid,
        /// The `contract_address` column of the `payments` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        contract_address -> Nullable<Varchar>,
        /// The `token_address` column of the `payments` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        token_address -> Nullable<Varchar>,
        /// The `block_number` column of the `payments` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        block_number -> Nullable<Int8>,
        /// The `confirmations` column of the `payments` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        confirmations -> Nullable<Int4>,
        /// The `created_at` column of the `payments` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Nullable<Timestamptz>,
        /// The `updated_at` column of the `payments` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Nullable<Timestamptz>,
        /// The `expires_at` column of the `payments` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Nullable<Timestamptz>,
        /// The `completed_at` column of the `payments` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        completed_at -> Nullable<Timestamptz>,
        /// The `metadata` column of the `payments` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        metadata -> Nullable<Jsonb>,
        /// The `last_checked_at` column of the `payments` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        last_checked_at -> Nullable<Timestamptz>,
        /// The `error_message` column of the `payments` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        error_message -> Nullable<Text>,
        /// The `network` column of the `payments` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        network -> Nullable<Varchar>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Stock ranking package assignments with access levels
    stock_ranking_assignments (assignment_id) {
        /// The `assignment_id` column of the `stock_ranking_assignments` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        assignment_id -> Uuid,
        /// The `wallet_address` column of the `stock_ranking_assignments` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        wallet_address -> Varchar,
        /// The `package_id` column of the `stock_ranking_assignments` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        package_id -> Varchar,
        /// The `package_name` column of the `stock_ranking_assignments` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        package_name -> Varchar,
        /// The `rank_access_level` column of the `stock_ranking_assignments` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        rank_access_level -> Int4,
        /// The `assigned_at` column of the `stock_ranking_assignments` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        assigned_at -> Timestamptz,
        /// The `expires_at` column of the `stock_ranking_assignments` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Nullable<Timestamptz>,
        /// The `is_active` column of the `stock_ranking_assignments` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_active -> Bool,
        /// The `assignment_source` column of the `stock_ranking_assignments` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        assignment_source -> Varchar,
        /// The `auto_renew` column of the `stock_ranking_assignments` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        auto_renew -> Bool,
        /// The `payment_reference` column of the `stock_ranking_assignments` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        payment_reference -> Nullable<Varchar>,
        /// The `created_at` column of the `stock_ranking_assignments` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `stock_ranking_assignments` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Active subscription management with lifecycle tracking
    subscriptions (id) {
        /// The `id` column of the `subscriptions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `wallet_address` column of the `subscriptions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        wallet_address -> Varchar,
        /// The `plan_id` column of the `subscriptions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        plan_id -> Uuid,
        /// The `payment_id` column of the `subscriptions` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        payment_id -> Nullable<Uuid>,
        /// The `status` column of the `subscriptions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        status -> Varchar,
        /// The `started_at` column of the `subscriptions` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        started_at -> Nullable<Timestamptz>,
        /// The `expires_at` column of the `subscriptions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Timestamptz,
        /// The `cancelled_at` column of the `subscriptions` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        cancelled_at -> Nullable<Timestamptz>,
        /// The `auto_renew` column of the `subscriptions` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        auto_renew -> Nullable<Bool>,
        /// The `metadata` column of the `subscriptions` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        metadata -> Nullable<Jsonb>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// User credit balances for payment system
    wallet_credits (wallet_address) {
        /// The `wallet_address` column of the `wallet_credits` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        wallet_address -> Varchar,
        /// The `balance` column of the `wallet_credits` table.
        ///
        /// Its SQL type is `Numeric`.
        ///
        /// (Automatically generated by Diesel.)
        balance -> Numeric,
        /// The `pending_balance` column of the `wallet_credits` table.
        ///
        /// Its SQL type is `Numeric`.
        ///
        /// (Automatically generated by Diesel.)
        pending_balance -> Numeric,
        /// The `lifetime_earned` column of the `wallet_credits` table.
        ///
        /// Its SQL type is `Numeric`.
        ///
        /// (Automatically generated by Diesel.)
        lifetime_earned -> Numeric,
        /// The `lifetime_spent` column of the `wallet_credits` table.
        ///
        /// Its SQL type is `Numeric`.
        ///
        /// (Automatically generated by Diesel.)
        lifetime_spent -> Numeric,
        /// The `last_transaction_at` column of the `wallet_credits` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        last_transaction_at -> Nullable<Timestamptz>,
        /// The `created_at` column of the `wallet_credits` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `wallet_credits` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
    }
}

diesel::joinable!(payment_audit_log -> payments (payment_id));
diesel::joinable!(subscriptions -> payments (payment_id));

diesel::allow_tables_to_appear_in_same_query!(
    credit_transactions,
    payment_audit_log,
    payment_contexts,
    payments,
    stock_ranking_assignments,
    subscriptions,
    wallet_credits,
);
