// @generated automatically by Diesel CLI.

diesel::table! {
    use diesel::sql_types::*;

    /// Representation of the `analytics_events` table.
    ///
    /// (Automatically generated by Diesel.)
    analytics_events (id) {
        /// The `id` column of the `analytics_events` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `event_type` column of the `analytics_events` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        event_type -> Varchar,
        /// The `wallet_address` column of the `analytics_events` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        wallet_address -> Nullable<Varchar>,
        /// The `resource_path` column of the `analytics_events` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        resource_path -> Varchar,
        /// The `method` column of the `analytics_events` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 10]
        method -> Varchar,
        /// The `status_code` column of the `analytics_events` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        status_code -> Int4,
        /// The `duration_ms` column of the `analytics_events` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        duration_ms -> Int4,
        /// The `metadata` column of the `analytics_events` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        metadata -> Nullable<Jsonb>,
        /// The `created_at` column of the `analytics_events` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Representation of the `api_key_module_access` table.
    ///
    /// (Automatically generated by Diesel.)
    api_key_module_access (id) {
        /// The `id` column of the `api_key_module_access` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `api_key_id` column of the `api_key_module_access` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        api_key_id -> Uuid,
        /// The `module_id` column of the `api_key_module_access` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        module_id -> Uuid,
        /// The `access_level` column of the `api_key_module_access` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        access_level -> Varchar,
        /// The `custom_rate_limit` column of the `api_key_module_access` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        custom_rate_limit -> Nullable<Int4>,
        /// The `custom_quotas` column of the `api_key_module_access` table.
        ///
        /// Its SQL type is `Jsonb`.
        ///
        /// (Automatically generated by Diesel.)
        custom_quotas -> Jsonb,
        /// The `granted_at` column of the `api_key_module_access` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        granted_at -> Timestamptz,
        /// The `granted_by` column of the `api_key_module_access` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        granted_by -> Nullable<Varchar>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Links API keys to permission groups for group-based permissions
    api_key_permissions (id) {
        /// The `id` column of the `api_key_permissions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `api_key_id` column of the `api_key_permissions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        api_key_id -> Uuid,
        /// The `permission_group_id` column of the `api_key_permissions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        permission_group_id -> Uuid,
        /// The `granted_at` column of the `api_key_permissions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        granted_at -> Timestamptz,
        /// The `granted_by` column of the `api_key_permissions` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        granted_by -> Nullable<Varchar>,
        /// The `expires_at` column of the `api_key_permissions` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Nullable<Timestamptz>,
        /// The `is_active` column of the `api_key_permissions` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_active -> Bool,
        /// The `metadata` column of the `api_key_permissions` table.
        ///
        /// Its SQL type is `Jsonb`.
        ///
        /// (Automatically generated by Diesel.)
        metadata -> Jsonb,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Developer API keys
    api_keys (id) {
        /// The `id` column of the `api_keys` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `key_hash` column of the `api_keys` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 256]
        key_hash -> Varchar,
        /// The `key_prefix` column of the `api_keys` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 16]
        key_prefix -> Varchar,
        /// The `full_key` column of the `api_keys` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 128]
        full_key -> Nullable<Varchar>,
        /// The `client_name` column of the `api_keys` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        client_name -> Varchar,
        /// The `client_description` column of the `api_keys` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        client_description -> Nullable<Text>,
        /// The `client_contact_email` column of the `api_keys` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        client_contact_email -> Nullable<Varchar>,
        /// The `wallet_address` column of the `api_keys` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        wallet_address -> Varchar,
        /// The `status` column of the `api_keys` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        status -> Varchar,
        /// The `total_requests` column of the `api_keys` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        total_requests -> Int8,
        /// The `ip_restrictions` column of the `api_keys` table.
        ///
        /// Its SQL type is `Nullable<Array<Nullable<Text>>>`.
        ///
        /// (Automatically generated by Diesel.)
        ip_restrictions -> Nullable<Array<Nullable<Text>>>,
        /// The `rate_limit_per_minute` column of the `api_keys` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        rate_limit_per_minute -> Int4,
        /// The `rate_limit_per_day` column of the `api_keys` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        rate_limit_per_day -> Int4,
        /// The `selected_permissions` column of the `api_keys` table.
        ///
        /// Its SQL type is `Array<Nullable<Text>>`.
        ///
        /// (Automatically generated by Diesel.)
        selected_permissions -> Array<Nullable<Text>>,
        /// The `expires_at` column of the `api_keys` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Nullable<Timestamptz>,
        /// The `last_used_at` column of the `api_keys` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        last_used_at -> Nullable<Timestamptz>,
        /// The `revoked_at` column of the `api_keys` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        revoked_at -> Nullable<Timestamptz>,
        /// The `revoked_by` column of the `api_keys` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        revoked_by -> Nullable<Varchar>,
        /// The `revocation_reason` column of the `api_keys` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        revocation_reason -> Nullable<Text>,
        /// The `created_at` column of the `api_keys` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `created_by` column of the `api_keys` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        created_by -> Varchar,
        /// The `updated_at` column of the `api_keys` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Representation of the `api_modules` table.
    ///
    /// (Automatically generated by Diesel.)
    api_modules (id) {
        /// The `id` column of the `api_modules` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `name` column of the `api_modules` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        name -> Varchar,
        /// The `display_name` column of the `api_modules` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        display_name -> Varchar,
        /// The `description` column of the `api_modules` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Nullable<Text>,
        /// The `category` column of the `api_modules` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        category -> Varchar,
        /// The `status` column of the `api_modules` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        status -> Varchar,
        /// The `base_path` column of the `api_modules` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        base_path -> Varchar,
        /// The `default_rate_limit` column of the `api_modules` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        default_rate_limit -> Int4,
        /// The `access_levels` column of the `api_modules` table.
        ///
        /// Its SQL type is `Jsonb`.
        ///
        /// (Automatically generated by Diesel.)
        access_levels -> Jsonb,
        /// The `endpoints` column of the `api_modules` table.
        ///
        /// Its SQL type is `Jsonb`.
        ///
        /// (Automatically generated by Diesel.)
        endpoints -> Jsonb,
        /// The `created_at` column of the `api_modules` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `api_modules` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Representation of the `audit_logs` table.
    ///
    /// (Automatically generated by Diesel.)
    audit_logs (id) {
        /// The `id` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `wallet_address` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        wallet_address -> Nullable<Varchar>,
        /// The `action` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        action -> Varchar,
        /// The `resource_type` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        resource_type -> Varchar,
        /// The `resource_id` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        resource_id -> Nullable<Varchar>,
        /// The `result` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        result -> Varchar,
        /// The `ip_address` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 45]
        ip_address -> Nullable<Varchar>,
        /// The `user_agent` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_agent -> Nullable<Text>,
        /// The `details` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        details -> Nullable<Jsonb>,
        /// The `created_at` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Maps permissions to groups
    group_permissions (id) {
        /// The `id` column of the `group_permissions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `group_id` column of the `group_permissions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        group_id -> Uuid,
        /// The `permission_id` column of the `group_permissions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        permission_id -> Uuid,
        /// The `granted_at` column of the `group_permissions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        granted_at -> Timestamptz,
        /// The `granted_by` column of the `group_permissions` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        granted_by -> Nullable<Varchar>,
        /// The `grant_reason` column of the `group_permissions` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        grant_reason -> Nullable<Text>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Permission groups for subscription plans
    groups (id) {
        /// The `id` column of the `groups` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `name` column of the `groups` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        name -> Varchar,
        /// The `slug` column of the `groups` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        slug -> Varchar,
        /// The `description` column of the `groups` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Text,
        /// The `group_type` column of the `groups` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        group_type -> Varchar,
        /// The `group_metadata` column of the `groups` table.
        ///
        /// Its SQL type is `Jsonb`.
        ///
        /// (Automatically generated by Diesel.)
        group_metadata -> Jsonb,
        /// The `price` column of the `groups` table.
        ///
        /// Its SQL type is `Nullable<Numeric>`.
        ///
        /// (Automatically generated by Diesel.)
        price -> Nullable<Numeric>,
        /// The `currency` column of the `groups` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 3]
        currency -> Nullable<Varchar>,
        /// The `billing_cycle` column of the `groups` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        billing_cycle -> Nullable<Varchar>,
        /// The `is_active` column of the `groups` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_active -> Bool,
        /// The `is_promoted` column of the `groups` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_promoted -> Bool,
        /// The `display_order` column of the `groups` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        display_order -> Nullable<Int4>,
        /// The `max_members` column of the `groups` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        max_members -> Nullable<Int4>,
        /// The `auto_assign_enabled` column of the `groups` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        auto_assign_enabled -> Nullable<Bool>,
        /// The `assignment_rules` column of the `groups` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        assignment_rules -> Nullable<Jsonb>,
        /// The `rate_limit_per_minute` column of the `groups` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        rate_limit_per_minute -> Int4,
        /// The `rate_limit_per_hour` column of the `groups` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        rate_limit_per_hour -> Int4,
        /// The `rate_limit_per_day` column of the `groups` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        rate_limit_per_day -> Int4,
        /// The `burst_capacity` column of the `groups` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        burst_capacity -> Int4,
        /// The `created_at` column of the `groups` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `groups` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// The `created_by` column of the `groups` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        created_by -> Nullable<Varchar>,
        /// The `last_modified_by` column of the `groups` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        last_modified_by -> Nullable<Varchar>,
        /// Plan tier level for upgrade/downgrade logic. Higher = better plan. 0 = free tier.
        tier_level -> Int4,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Representation of the `openid_refresh_tokens` table.
    ///
    /// (Automatically generated by Diesel.)
    openid_refresh_tokens (token_id) {
        /// The `token_id` column of the `openid_refresh_tokens` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 36]
        token_id -> Varchar,
        /// The `wallet_address` column of the `openid_refresh_tokens` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        wallet_address -> Varchar,
        /// The `expires_at` column of the `openid_refresh_tokens` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Timestamptz,
        /// The `created_at` column of the `openid_refresh_tokens` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `is_revoked` column of the `openid_refresh_tokens` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_revoked -> Bool,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Permission definitions catalog
    permissions (id) {
        /// The `id` column of the `permissions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `permission_string` column of the `permissions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        permission_string -> Varchar,
        /// The `platform` column of the `permissions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        platform -> Varchar,
        /// The `resource` column of the `permissions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        resource -> Varchar,
        /// The `action` column of the `permissions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        action -> Varchar,
        /// The `description` column of the `permissions` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Nullable<Text>,
        /// The `permission_type` column of the `permissions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        permission_type -> Varchar,
        /// The `name` column of the `permissions` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        name -> Nullable<Varchar>,
        /// The `category` column of the `permissions` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        category -> Nullable<Varchar>,
        /// The `is_system` column of the `permissions` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_system -> Bool,
        /// The `is_active` column of the `permissions` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_active -> Bool,
        /// The `created_at` column of the `permissions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `permissions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// The `created_by` column of the `permissions` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        created_by -> Nullable<Varchar>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Representation of the `route_permissions` table.
    ///
    /// (Automatically generated by Diesel.)
    route_permissions (id) {
        /// The `id` column of the `route_permissions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `route_pattern` column of the `route_permissions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 500]
        route_pattern -> Varchar,
        /// The `http_method` column of the `route_permissions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 10]
        http_method -> Varchar,
        /// The `required_permission` column of the `route_permissions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        required_permission -> Varchar,
        /// The `priority` column of the `route_permissions` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        priority -> Int4,
        /// The `is_active` column of the `route_permissions` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_active -> Bool,
        /// The `is_public` column of the `route_permissions` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_public -> Bool,
        /// The `description` column of the `route_permissions` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Nullable<Text>,
        /// The `route_category` column of the `route_permissions` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        route_category -> Nullable<Varchar>,
        /// The `created_at` column of the `route_permissions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `route_permissions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// The `created_by` column of the `route_permissions` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        created_by -> Nullable<Varchar>,
        /// The `last_modified_by` column of the `route_permissions` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        last_modified_by -> Nullable<Varchar>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Global admin console settings
    system_settings (id) {
        /// The `id` column of the `system_settings` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `category` column of the `system_settings` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        category -> Varchar,
        /// The `key` column of the `system_settings` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        key -> Varchar,
        /// The `value` column of the `system_settings` table.
        ///
        /// Its SQL type is `Jsonb`.
        ///
        /// (Automatically generated by Diesel.)
        value -> Jsonb,
        /// The `description` column of the `system_settings` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Nullable<Text>,
        /// The `created_at` column of the `system_settings` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `system_settings` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Wallet activity tracking
    wallet_activity_logs (id) {
        /// The `id` column of the `wallet_activity_logs` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `wallet_address` column of the `wallet_activity_logs` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        wallet_address -> Varchar,
        /// The `event_type` column of the `wallet_activity_logs` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        event_type -> Varchar,
        /// The `description` column of the `wallet_activity_logs` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Text,
        /// The `performed_by` column of the `wallet_activity_logs` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        performed_by -> Nullable<Varchar>,
        /// The `metadata` column of the `wallet_activity_logs` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        metadata -> Nullable<Jsonb>,
        /// The `created_at` column of the `wallet_activity_logs` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Direct permission grants to wallets
    wallet_direct_permissions (id) {
        /// The `id` column of the `wallet_direct_permissions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `wallet_address` column of the `wallet_direct_permissions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        wallet_address -> Varchar,
        /// The `permission_id` column of the `wallet_direct_permissions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        permission_id -> Uuid,
        /// The `granted_at` column of the `wallet_direct_permissions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        granted_at -> Timestamptz,
        /// The `expires_at` column of the `wallet_direct_permissions` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Nullable<Timestamptz>,
        /// The `granted_by` column of the `wallet_direct_permissions` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        granted_by -> Nullable<Varchar>,
        /// The `grant_reason` column of the `wallet_direct_permissions` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        grant_reason -> Nullable<Text>,
        /// The `is_active` column of the `wallet_direct_permissions` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_active -> Bool,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Assigns wallets to permission groups
    wallet_group_assignments (id) {
        /// The `id` column of the `wallet_group_assignments` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `wallet_address` column of the `wallet_group_assignments` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        wallet_address -> Varchar,
        /// The `group_id` column of the `wallet_group_assignments` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        group_id -> Uuid,
        /// The `assigned_at` column of the `wallet_group_assignments` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        assigned_at -> Timestamptz,
        /// The `expires_at` column of the `wallet_group_assignments` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Nullable<Timestamptz>,
        /// The `assigned_by` column of the `wallet_group_assignments` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        assigned_by -> Nullable<Varchar>,
        /// The `assignment_reason` column of the `wallet_group_assignments` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        assignment_reason -> Nullable<Text>,
        /// The `is_active` column of the `wallet_group_assignments` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_active -> Bool,
        /// The `assignment_source` column of the `wallet_group_assignments` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        assignment_source -> Varchar,
        /// The `payment_reference` column of the `wallet_group_assignments` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        payment_reference -> Nullable<Varchar>,
        /// The `subscription_id` column of the `wallet_group_assignments` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        subscription_id -> Nullable<Varchar>,
        /// The `auto_renew` column of the `wallet_group_assignments` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        auto_renew -> Bool,
        /// The `next_billing_date` column of the `wallet_group_assignments` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        next_billing_date -> Nullable<Timestamptz>,
        /// The `assignment_metadata` column of the `wallet_group_assignments` table.
        ///
        /// Its SQL type is `Jsonb`.
        ///
        /// (Automatically generated by Diesel.)
        assignment_metadata -> Jsonb,
        /// The `updated_at` column of the `wallet_group_assignments` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Wallet user accounts - core identity table
    wallet_users (wallet_address) {
        /// The `wallet_address` column of the `wallet_users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        wallet_address -> Varchar,
        /// The `is_active` column of the `wallet_users` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_active -> Bool,
        /// The `tier_level` column of the `wallet_users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        tier_level -> Varchar,
        /// The `wallet_metadata` column of the `wallet_users` table.
        ///
        /// Its SQL type is `Jsonb`.
        ///
        /// (Automatically generated by Diesel.)
        wallet_metadata -> Jsonb,
        /// The `permission_groups` column of the `wallet_users` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        permission_groups -> Nullable<Jsonb>,
        /// The `disable_info` column of the `wallet_users` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        disable_info -> Nullable<Jsonb>,
        /// The `plan_expires_at` column of the `wallet_users` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        plan_expires_at -> Nullable<Timestamptz>,
        /// The `current_plan_id` column of the `wallet_users` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        current_plan_id -> Nullable<Int4>,
        /// The `created_at` column of the `wallet_users` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `wallet_users` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// The `last_auth_at` column of the `wallet_users` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        last_auth_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Representation of the `web3_auth_nonces` table.
    ///
    /// (Automatically generated by Diesel.)
    web3_auth_nonces (wallet_address) {
        /// The `wallet_address` column of the `web3_auth_nonces` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        wallet_address -> Varchar,
        /// The `nonce` column of the `web3_auth_nonces` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 64]
        nonce -> Varchar,
        /// The `message` column of the `web3_auth_nonces` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        message -> Text,
        /// The `expires_at` column of the `web3_auth_nonces` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Timestamptz,
        /// The `created_at` column of the `web3_auth_nonces` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
    }
}

diesel::joinable!(api_key_module_access -> api_keys (api_key_id));
diesel::joinable!(api_key_module_access -> api_modules (module_id));
diesel::joinable!(api_key_permissions -> api_keys (api_key_id));
diesel::joinable!(api_key_permissions -> groups (permission_group_id));
diesel::joinable!(api_keys -> wallet_users (wallet_address));
diesel::joinable!(group_permissions -> groups (group_id));
diesel::joinable!(group_permissions -> permissions (permission_id));
diesel::joinable!(openid_refresh_tokens -> wallet_users (wallet_address));
diesel::joinable!(wallet_direct_permissions -> permissions (permission_id));
diesel::joinable!(wallet_direct_permissions -> wallet_users (wallet_address));
diesel::joinable!(wallet_group_assignments -> groups (group_id));
diesel::joinable!(wallet_group_assignments -> wallet_users (wallet_address));

diesel::allow_tables_to_appear_in_same_query!(
    analytics_events,
    api_key_module_access,
    api_key_permissions,
    api_keys,
    api_modules,
    audit_logs,
    group_permissions,
    groups,
    openid_refresh_tokens,
    permissions,
    route_permissions,
    system_settings,
    wallet_activity_logs,
    wallet_direct_permissions,
    wallet_group_assignments,
    wallet_users,
    web3_auth_nonces,
);
