// @generated automatically by Diesel CLI.

diesel::table! {
    use diesel::sql_types::*;

    /// Audit trail for all assignment modifications (extend, revoke, etc.)
    assignment_audit_log (id) {
        /// The `id` column of the `assignment_audit_log` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `assignment_id` column of the `assignment_audit_log` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        assignment_id -> Uuid,
        /// The `action` column of the `assignment_audit_log` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        action -> Varchar,
        /// The `old_value` column of the `assignment_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        old_value -> Nullable<Text>,
        /// The `new_value` column of the `assignment_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        new_value -> Nullable<Text>,
        /// The `reason` column of the `assignment_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        reason -> Nullable<Text>,
        /// The `performed_by` column of the `assignment_audit_log` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        performed_by -> Varchar,
        /// The `performed_at` column of the `assignment_audit_log` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        performed_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Tracks active SSE connections across multiple backend instances for Redis pub/sub
    notification_subscriptions (id) {
        /// The `id` column of the `notification_subscriptions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `wallet_address` column of the `notification_subscriptions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        wallet_address -> Varchar,
        /// The `instance_id` column of the `notification_subscriptions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        instance_id -> Varchar,
        /// The `connection_id` column of the `notification_subscriptions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        connection_id -> Varchar,
        /// The `connected_at` column of the `notification_subscriptions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        connected_at -> Timestamptz,
        /// The `last_ping_at` column of the `notification_subscriptions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        last_ping_at -> Timestamptz,
        /// The `disconnected_at` column of the `notification_subscriptions` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        disconnected_at -> Nullable<Timestamptz>,
        /// The `user_agent` column of the `notification_subscriptions` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_agent -> Nullable<Text>,
        /// The `ip_address` column of the `notification_subscriptions` table.
        ///
        /// Its SQL type is `Nullable<Inet>`.
        ///
        /// (Automatically generated by Diesel.)
        ip_address -> Nullable<Inet>,
        /// The `redis_channel` column of the `notification_subscriptions` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 200]
        redis_channel -> Nullable<Varchar>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// OpenID Connect refresh tokens for Web3-authenticated users
    openid_refresh_tokens (token_id) {
        /// The `token_id` column of the `openid_refresh_tokens` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 36]
        token_id -> Varchar,
        /// The `wallet_address` column of the `openid_refresh_tokens` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        wallet_address -> Varchar,
        /// The `expires_at` column of the `openid_refresh_tokens` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Timestamptz,
        /// The `created_at` column of the `openid_refresh_tokens` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `is_revoked` column of the `openid_refresh_tokens` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_revoked -> Bool,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Complete audit trail of all permission-related events
    permission_audit_log (id) {
        /// The `id` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `event_type` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        event_type -> Varchar,
        /// The `event_timestamp` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        event_timestamp -> Timestamptz,
        /// The `event_source` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        event_source -> Varchar,
        /// The `wallet_address` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        wallet_address -> Varchar,
        /// The `permission_string` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        permission_string -> Nullable<Varchar>,
        /// The `permission_id` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        permission_id -> Nullable<Uuid>,
        /// The `group_id` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        group_id -> Nullable<Uuid>,
        /// The `group_name` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        group_name -> Nullable<Varchar>,
        /// The `performed_by` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        performed_by -> Nullable<Varchar>,
        /// The `performed_by_name` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        performed_by_name -> Nullable<Varchar>,
        /// The `reason` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        reason -> Nullable<Text>,
        /// The `request_id` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 36]
        request_id -> Nullable<Varchar>,
        /// The `ip_address` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Inet>`.
        ///
        /// (Automatically generated by Diesel.)
        ip_address -> Nullable<Inet>,
        /// The `user_agent` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_agent -> Nullable<Text>,
        /// The `previous_state` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        previous_state -> Nullable<Jsonb>,
        /// The `new_state` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        new_state -> Nullable<Jsonb>,
        /// The `expires_at` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Nullable<Timestamptz>,
        /// The `valid_from` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        valid_from -> Nullable<Timestamptz>,
        /// The `valid_until` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        valid_until -> Nullable<Timestamptz>,
        /// The `metadata` column of the `permission_audit_log` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        metadata -> Nullable<Jsonb>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Maps permission groups to individual permissions - enables permission group inheritance
    permission_group_memberships (id) {
        /// The `id` column of the `permission_group_memberships` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `group_id` column of the `permission_group_memberships` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        group_id -> Uuid,
        /// The `permission_id` column of the `permission_group_memberships` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        permission_id -> Uuid,
        /// The `granted_at` column of the `permission_group_memberships` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        granted_at -> Timestamptz,
        /// The `granted_by` column of the `permission_group_memberships` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        granted_by -> Nullable<Varchar>,
        /// The `grant_reason` column of the `permission_group_memberships` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        grant_reason -> Nullable<Text>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Enhanced permission group definitions with pay-per-use billing support
    permission_groups (id) {
        /// The `id` column of the `permission_groups` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `name` column of the `permission_groups` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        name -> Varchar,
        /// The `slug` column of the `permission_groups` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        slug -> Varchar,
        /// The `description` column of the `permission_groups` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Text,
        /// The `group_type` column of the `permission_groups` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        group_type -> Varchar,
        /// The `group_metadata` column of the `permission_groups` table.
        ///
        /// Its SQL type is `Jsonb`.
        ///
        /// (Automatically generated by Diesel.)
        group_metadata -> Jsonb,
        /// The `price` column of the `permission_groups` table.
        ///
        /// Its SQL type is `Nullable<Numeric>`.
        ///
        /// (Automatically generated by Diesel.)
        price -> Nullable<Numeric>,
        /// The `currency` column of the `permission_groups` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 3]
        currency -> Nullable<Varchar>,
        /// The `billing_cycle` column of the `permission_groups` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        billing_cycle -> Nullable<Varchar>,
        /// The `is_active` column of the `permission_groups` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_active -> Bool,
        /// The `is_promoted` column of the `permission_groups` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_promoted -> Bool,
        /// The `display_order` column of the `permission_groups` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        display_order -> Nullable<Int4>,
        /// The `max_members` column of the `permission_groups` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        max_members -> Nullable<Int4>,
        /// The `auto_assign_enabled` column of the `permission_groups` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        auto_assign_enabled -> Nullable<Bool>,
        /// The `assignment_rules` column of the `permission_groups` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        assignment_rules -> Nullable<Jsonb>,
        /// The `created_at` column of the `permission_groups` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `permission_groups` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// The `created_by` column of the `permission_groups` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        created_by -> Nullable<Varchar>,
        /// The `last_modified_by` column of the `permission_groups` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        last_modified_by -> Nullable<Varchar>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Enhanced unified permissions table with Web3-first support and direct wallet assignments
    permissions (id) {
        /// The `id` column of the `permissions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `permission_string` column of the `permissions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        permission_string -> Varchar,
        /// The `platform` column of the `permissions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        platform -> Varchar,
        /// The `resource` column of the `permissions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        resource -> Varchar,
        /// The `action` column of the `permissions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        action -> Varchar,
        /// The `description` column of the `permissions` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Nullable<Text>,
        /// The `permission_type` column of the `permissions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        permission_type -> Varchar,
        /// The `web3_contract_address` column of the `permissions` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        web3_contract_address -> Nullable<Varchar>,
        /// The `web3_chain_id` column of the `permissions` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        web3_chain_id -> Nullable<Int8>,
        /// The `web3_min_balance` column of the `permissions` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 78]
        web3_min_balance -> Nullable<Varchar>,
        /// The `web3_token_ids` column of the `permissions` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        web3_token_ids -> Nullable<Jsonb>,
        /// The `web3_metadata` column of the `permissions` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        web3_metadata -> Nullable<Jsonb>,
        /// The `wallet_address` column of the `permissions` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        wallet_address -> Nullable<Varchar>,
        /// The `source_type` column of the `permissions` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        source_type -> Nullable<Varchar>,
        /// The `source_id` column of the `permissions` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        source_id -> Nullable<Uuid>,
        /// The `granted_at` column of the `permissions` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        granted_at -> Nullable<Timestamptz>,
        /// The `expires_at` column of the `permissions` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Nullable<Timestamptz>,
        /// The `granted_by` column of the `permissions` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        granted_by -> Nullable<Varchar>,
        /// The `grant_reason` column of the `permissions` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        grant_reason -> Nullable<Text>,
        /// The `is_active` column of the `permissions` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_active -> Bool,
        /// The `created_at` column of the `permissions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `permissions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// The `created_by` column of the `permissions` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        created_by -> Nullable<Varchar>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Enhanced API route protection with permission requirements and category support
    route_permissions (id) {
        /// The `id` column of the `route_permissions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `route_pattern` column of the `route_permissions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 500]
        route_pattern -> Varchar,
        /// The `http_method` column of the `route_permissions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 10]
        http_method -> Varchar,
        /// The `required_permission` column of the `route_permissions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        required_permission -> Varchar,
        /// The `priority` column of the `route_permissions` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        priority -> Int4,
        /// The `is_active` column of the `route_permissions` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_active -> Bool,
        /// The `is_public` column of the `route_permissions` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_public -> Bool,
        /// The `description` column of the `route_permissions` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Nullable<Text>,
        /// The `route_category` column of the `route_permissions` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        route_category -> Nullable<Varchar>,
        /// The `created_at` column of the `route_permissions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `route_permissions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// The `created_by` column of the `route_permissions` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        created_by -> Nullable<Varchar>,
        /// The `last_modified_by` column of the `route_permissions` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        last_modified_by -> Nullable<Varchar>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Active user sessions for Web3-authenticated wallets with token management and security tracking
    sessions (id) {
        /// The `id` column of the `sessions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `wallet_address` column of the `sessions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        wallet_address -> Varchar,
        /// The `access_token` column of the `sessions` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        access_token -> Text,
        /// The `refresh_token` column of the `sessions` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        refresh_token -> Nullable<Text>,
        /// The `created_at` column of the `sessions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `sessions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// The `expires_at` column of the `sessions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Timestamptz,
        /// The `last_accessed_at` column of the `sessions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        last_accessed_at -> Timestamptz,
        /// The `ip_address` column of the `sessions` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 45]
        ip_address -> Nullable<Varchar>,
        /// The `user_agent` column of the `sessions` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_agent -> Nullable<Text>,
        /// The `is_revoked` column of the `sessions` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_revoked -> Bool,
        /// The `version` column of the `sessions` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        version -> Int8,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Tracks stock ranking package assignments to wallet users with expiration and access levels
    stock_ranking_assignments (assignment_id) {
        /// The `assignment_id` column of the `stock_ranking_assignments` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        assignment_id -> Uuid,
        /// The `wallet_address` column of the `stock_ranking_assignments` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        wallet_address -> Varchar,
        /// The `package_id` column of the `stock_ranking_assignments` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        package_id -> Varchar,
        /// The `package_name` column of the `stock_ranking_assignments` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        package_name -> Varchar,
        /// Maximum rank position user can access (e.g., 1000 = top 1000 stocks)
        rank_access_level -> Int4,
        /// The `assigned_at` column of the `stock_ranking_assignments` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        assigned_at -> Timestamptz,
        /// The `expires_at` column of the `stock_ranking_assignments` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Nullable<Timestamptz>,
        /// The `is_active` column of the `stock_ranking_assignments` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_active -> Bool,
        /// Source of assignment: "purchase", "promotion", "manual", "trial"
        #[max_length = 50]
        assignment_source -> Varchar,
        /// The `auto_renew` column of the `stock_ranking_assignments` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        auto_renew -> Bool,
        /// The `payment_reference` column of the `stock_ranking_assignments` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        payment_reference -> Nullable<Varchar>,
        /// The `created_at` column of the `stock_ranking_assignments` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `stock_ranking_assignments` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Direct permission grants to wallets (exceptions, temporary access)
    wallet_direct_permissions (id) {
        /// The `id` column of the `wallet_direct_permissions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `wallet_address` column of the `wallet_direct_permissions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        wallet_address -> Varchar,
        /// The `permission_id` column of the `wallet_direct_permissions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        permission_id -> Uuid,
        /// The `granted_at` column of the `wallet_direct_permissions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        granted_at -> Timestamptz,
        /// The `expires_at` column of the `wallet_direct_permissions` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Nullable<Timestamptz>,
        /// The `granted_by` column of the `wallet_direct_permissions` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        granted_by -> Nullable<Varchar>,
        /// The `grant_reason` column of the `wallet_direct_permissions` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        grant_reason -> Nullable<Text>,
        /// The `is_active` column of the `wallet_direct_permissions` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_active -> Bool,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Assigns wallets to permission groups with optional expiration
    wallet_group_assignments (id) {
        /// The `id` column of the `wallet_group_assignments` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `wallet_address` column of the `wallet_group_assignments` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        wallet_address -> Varchar,
        /// The `group_id` column of the `wallet_group_assignments` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        group_id -> Uuid,
        /// The `assigned_at` column of the `wallet_group_assignments` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        assigned_at -> Timestamptz,
        /// The `expires_at` column of the `wallet_group_assignments` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Nullable<Timestamptz>,
        /// The `assigned_by` column of the `wallet_group_assignments` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        assigned_by -> Nullable<Varchar>,
        /// The `assignment_reason` column of the `wallet_group_assignments` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        assignment_reason -> Nullable<Text>,
        /// The `is_active` column of the `wallet_group_assignments` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_active -> Bool,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Enhanced notifications system with performance indexes and delivery tracking
    wallet_notifications (id) {
        /// The `id` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `wallet_address` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        wallet_address -> Varchar,
        /// The `notification_type` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        notification_type -> Varchar,
        /// The `title` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        title -> Varchar,
        /// The `message` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        message -> Text,
        /// The `data` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        data -> Nullable<Jsonb>,
        /// The `priority` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        priority -> Varchar,
        /// The `timestamp` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        timestamp -> Timestamptz,
        /// The `expires_at` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Nullable<Timestamptz>,
        /// The `read_at` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        read_at -> Nullable<Timestamptz>,
        /// The `clicked_at` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        clicked_at -> Nullable<Timestamptz>,
        /// The `delivered_at` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        delivered_at -> Nullable<Timestamptz>,
        /// The `action_url` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 500]
        action_url -> Nullable<Varchar>,
        /// The `image_url` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 500]
        image_url -> Nullable<Varchar>,
        /// The `created_at` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// The `queued_at` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        queued_at -> Nullable<Timestamptz>,
        /// The `delivery_attempts` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        delivery_attempts -> Nullable<Int4>,
        /// The `last_delivery_attempt_at` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        last_delivery_attempt_at -> Nullable<Timestamptz>,
        /// The `delivery_error` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        delivery_error -> Nullable<Text>,
        /// The `acknowledged_at` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        acknowledged_at -> Nullable<Timestamptz>,
        /// The `deleted_at` column of the `wallet_notifications` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        deleted_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Wallet user accounts - permissions granted via wallet_group_assignments and wallet_direct_permissions
    wallet_users (wallet_address) {
        /// The `wallet_address` column of the `wallet_users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        wallet_address -> Varchar,
        /// The `is_active` column of the `wallet_users` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_active -> Bool,
        /// The `tier_level` column of the `wallet_users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        tier_level -> Varchar,
        /// The `wallet_metadata` column of the `wallet_users` table.
        ///
        /// Its SQL type is `Jsonb`.
        ///
        /// (Automatically generated by Diesel.)
        wallet_metadata -> Jsonb,
        /// The `created_at` column of the `wallet_users` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `wallet_users` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// The `last_auth_at` column of the `wallet_users` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        last_auth_at -> Nullable<Timestamptz>,
        /// The `permission_groups` column of the `wallet_users` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        permission_groups -> Nullable<Jsonb>,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Temporary nonces for Web3 SIWE authentication challenges
    web3_auth_nonces (wallet_address) {
        /// The `wallet_address` column of the `web3_auth_nonces` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 42]
        wallet_address -> Varchar,
        /// The `nonce` column of the `web3_auth_nonces` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 64]
        nonce -> Varchar,
        /// The `message` column of the `web3_auth_nonces` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        message -> Text,
        /// The `expires_at` column of the `web3_auth_nonces` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Timestamptz,
        /// The `created_at` column of the `web3_auth_nonces` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
    }
}

diesel::joinable!(assignment_audit_log -> stock_ranking_assignments (assignment_id));
diesel::joinable!(openid_refresh_tokens -> wallet_users (wallet_address));
diesel::joinable!(permission_group_memberships -> permission_groups (group_id));
diesel::joinable!(permission_group_memberships -> permissions (permission_id));
diesel::joinable!(sessions -> wallet_users (wallet_address));
diesel::joinable!(wallet_direct_permissions -> permissions (permission_id));
diesel::joinable!(wallet_direct_permissions -> wallet_users (wallet_address));
diesel::joinable!(wallet_group_assignments -> permission_groups (group_id));
diesel::joinable!(wallet_group_assignments -> wallet_users (wallet_address));

diesel::allow_tables_to_appear_in_same_query!(
    assignment_audit_log,
    notification_subscriptions,
    openid_refresh_tokens,
    permission_audit_log,
    permission_group_memberships,
    permission_groups,
    permissions,
    route_permissions,
    sessions,
    stock_ranking_assignments,
    wallet_direct_permissions,
    wallet_group_assignments,
    wallet_notifications,
    wallet_users,
    web3_auth_nonces,
);
