// @generated automatically by Diesel CLI.

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Representation of the `refresh_tokens` table.
    ///
    /// (Automatically generated by Diesel.)
    refresh_tokens (id) {
        /// The `id` column of the `refresh_tokens` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `user_id` column of the `refresh_tokens` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Text,
        /// The `token_hash` column of the `refresh_tokens` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        token_hash -> Text,
        /// The `family_id` column of the `refresh_tokens` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        family_id -> Uuid,
        /// The `expires_at` column of the `refresh_tokens` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Timestamptz,
        /// The `created_at` column of the `refresh_tokens` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `refresh_tokens` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// The `last_used_at` column of the `refresh_tokens` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        last_used_at -> Nullable<Timestamptz>,
        /// The `device_info` column of the `refresh_tokens` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        device_info -> Nullable<Jsonb>,
        /// The `ip_address` column of the `refresh_tokens` table.
        ///
        /// Its SQL type is `Nullable<Inet>`.
        ///
        /// (Automatically generated by Diesel.)
        ip_address -> Nullable<Inet>,
        /// The `user_agent` column of the `refresh_tokens` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_agent -> Nullable<Text>,
        /// The `is_revoked` column of the `refresh_tokens` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_revoked -> Bool,
        /// The `revoked_at` column of the `refresh_tokens` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        revoked_at -> Nullable<Timestamptz>,
        /// The `revoked_reason` column of the `refresh_tokens` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        revoked_reason -> Nullable<Text>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Representation of the `revoked_tokens` table.
    ///
    /// (Automatically generated by Diesel.)
    revoked_tokens (id) {
        /// The `id` column of the `revoked_tokens` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `jti` column of the `revoked_tokens` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        jti -> Text,
        /// The `user_id` column of the `revoked_tokens` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Text,
        /// The `token_type` column of the `revoked_tokens` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        token_type -> Text,
        /// The `expires_at` column of the `revoked_tokens` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Timestamptz,
        /// The `revoked_at` column of the `revoked_tokens` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        revoked_at -> Timestamptz,
        /// The `revoked_by` column of the `revoked_tokens` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        revoked_by -> Nullable<Text>,
        /// The `revoked_reason` column of the `revoked_tokens` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        revoked_reason -> Text,
        /// The `created_at` column of the `revoked_tokens` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Representation of the `sessions` table.
    ///
    /// (Automatically generated by Diesel.)
    sessions (id) {
        /// The `id` column of the `sessions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `user_id` column of the `sessions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `access_token` column of the `sessions` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        access_token -> Text,
        /// The `expires_at` column of the `sessions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Timestamptz,
        /// The `provider` column of the `sessions` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        provider -> Nullable<Varchar>,
        /// The `session_token` column of the `sessions` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        session_token -> Nullable<Text>,
        /// The `user_agent` column of the `sessions` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_agent -> Nullable<Text>,
        /// The `ip_address` column of the `sessions` table.
        ///
        /// Its SQL type is `Nullable<Inet>`.
        ///
        /// (Automatically generated by Diesel.)
        ip_address -> Nullable<Inet>,
        /// The `is_active` column of the `sessions` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_active -> Bool,
        /// The `created_at` column of the `sessions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Individual user permissions - migrated from users.permissions array
    user_permissions (id) {
        /// The `id` column of the `user_permissions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `user_id` column of the `user_permissions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// Permission string in format platform:resource:action
        #[max_length = 255]
        permission -> Varchar,
        /// When the permission was granted
        granted_at -> Nullable<Timestamptz>,
        /// User who granted this permission (nullable for system grants)
        granted_by -> Nullable<Uuid>,
        /// When permission expires (nullable for permanent permissions)
        expires_at -> Nullable<Timestamptz>,
        /// Whether permission is currently active
        is_active -> Nullable<Bool>,
        /// The `created_at` column of the `user_permissions` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Nullable<Timestamptz>,
        /// The `updated_at` column of the `user_permissions` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Representation of the `users` table.
    ///
    /// (Automatically generated by Diesel.)
    users (id) {
        /// The `id` column of the `users` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `firebase_uid` column of the `users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 128]
        firebase_uid -> Varchar,
        /// The `email` column of the `users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        email -> Varchar,
        /// The `display_name` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        display_name -> Nullable<Varchar>,
        /// The `name` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        name -> Nullable<Varchar>,
        /// The `avatar_url` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        avatar_url -> Nullable<Text>,
        /// The `package_tier` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        package_tier -> Nullable<Varchar>,
        /// The `email_verified` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        email_verified -> Nullable<Bool>,
        /// The `is_active` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        is_active -> Nullable<Bool>,
        /// The `last_login_at` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        last_login_at -> Nullable<Timestamptz>,
        /// The `created_at` column of the `users` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `users` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// The `primary_platform_id` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        primary_platform_id -> Nullable<Uuid>,
    }
}

diesel::joinable!(sessions -> users (user_id));

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    pricing_plans (id) {
        id -> Int4,
        name -> Varchar,
        plan_type -> Varchar,
        base_price -> Numeric,
        current_price -> Numeric,
        currency -> Varchar,
        features -> Jsonb,
        affiliate_commission_rate -> Nullable<Numeric>,
        display_order -> Nullable<Int4>,
        is_active -> Nullable<Bool>,
        is_highlighted -> Nullable<Bool>,
        created_at -> Nullable<Timestamptz>,
        updated_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    promotional_campaigns (id) {
        id -> Int4,
        name -> Varchar,
        description -> Nullable<Text>,
        campaign_type -> Varchar,
        is_active -> Nullable<Bool>,
        start_date -> Timestamptz,
        end_date -> Nullable<Timestamptz>,
        priority -> Nullable<Int4>,
        affiliate_eligible -> Nullable<Bool>,
        created_at -> Nullable<Timestamptz>,
        updated_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    plan_promotions (id) {
        id -> Int4,
        campaign_id -> Nullable<Int4>,
        plan_id -> Nullable<Int4>,
        discount_type -> Varchar,
        discount_value -> Numeric,
        max_discount_amount -> Nullable<Numeric>,
        promotional_badge -> Nullable<Text>,
        promotional_message -> Nullable<Text>,
        affects_affiliate_commission -> Nullable<Bool>,
        created_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    discount_codes (id) {
        id -> Int4,
        code -> Varchar,
        campaign_id -> Nullable<Int4>,
        created_by_affiliate_id -> Nullable<Int4>,
        discount_type -> Varchar,
        discount_value -> Numeric,
        max_uses -> Nullable<Int4>,
        current_uses -> Nullable<Int4>,
        user_limit -> Nullable<Int4>,
        is_active -> Nullable<Bool>,
        valid_from -> Timestamptz,
        valid_until -> Nullable<Timestamptz>,
        applicable_plans -> Nullable<Jsonb>,
        affiliate_bonus_rate -> Nullable<Numeric>,
        created_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    pricing_experiments (id) {
        id -> Int4,
        name -> Varchar,
        description -> Nullable<Text>,
        plan_id -> Nullable<Int4>,
        variant_a_price -> Numeric,
        variant_b_price -> Numeric,
        traffic_split -> Nullable<Int4>,
        is_active -> Nullable<Bool>,
        start_date -> Nullable<Timestamptz>,
        end_date -> Nullable<Timestamptz>,
        created_at -> Nullable<Timestamptz>,
        updated_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    affiliates (id) {
        id -> Int4,
        user_id -> Nullable<Int4>,
        affiliate_code -> Varchar,
        status -> Nullable<Varchar>,
        commission_rate -> Nullable<Numeric>,
        payment_method -> Nullable<Varchar>,
        payment_details -> Nullable<Jsonb>,
        tax_id -> Nullable<Varchar>,
        company_name -> Nullable<Varchar>,
        website -> Nullable<Varchar>,
        social_media -> Nullable<Jsonb>,
        marketing_materials -> Nullable<Jsonb>,
        total_referrals -> Nullable<Int4>,
        total_sales -> Nullable<Numeric>,
        total_commissions -> Nullable<Numeric>,
        lifetime_earnings -> Nullable<Numeric>,
        approved_at -> Nullable<Timestamptz>,
        last_activity -> Nullable<Timestamptz>,
        created_at -> Nullable<Timestamptz>,
        updated_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    referrals (id) {
        id -> Int4,
        affiliate_id -> Nullable<Int4>,
        referreduser_id -> Nullable<Int4>,
        referral_source -> Nullable<Varchar>,
        referral_medium -> Nullable<Varchar>,
        referral_campaign -> Nullable<Varchar>,
        ip_address -> Nullable<Inet>,
        user_agent -> Nullable<Text>,
        conversion_status -> Nullable<Varchar>,
        converted_at -> Nullable<Timestamptz>,
        attribution_window -> Nullable<Int4>,
        expires_at -> Nullable<Timestamptz>,
        created_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    commissions (id) {
        id -> Int4,
        affiliate_id -> Nullable<Int4>,
        referral_id -> Nullable<Int4>,
        order_id -> Nullable<Varchar>,
        plan_id -> Nullable<Int4>,
        commission_type -> Nullable<Varchar>,
        gross_amount -> Numeric,
        commission_rate -> Numeric,
        commission_amount -> Numeric,
        currency -> Nullable<Varchar>,
        status -> Nullable<Varchar>,
        approved_at -> Nullable<Timestamptz>,
        paid_at -> Nullable<Timestamptz>,
        payment_reference -> Nullable<Varchar>,
        notes -> Nullable<Text>,
        created_at -> Nullable<Timestamptz>,
        updated_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    affiliate_payouts (id) {
        id -> Int4,
        affiliate_id -> Nullable<Int4>,
        payout_period_start -> Timestamptz,
        payout_period_end -> Timestamptz,
        total_commissions -> Numeric,
        payout_amount -> Numeric,
        currency -> Nullable<Varchar>,
        payment_method -> Nullable<Varchar>,
        payment_details -> Nullable<Jsonb>,
        status -> Nullable<Varchar>,
        transaction_reference -> Nullable<Varchar>,
        processed_at -> Nullable<Timestamptz>,
        created_at -> Nullable<Timestamptz>,
        updated_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    affiliate_materials (id) {
        id -> Int4,
        name -> Varchar,
        #[sql_name = "type"]
        material_type -> Varchar,
        category -> Nullable<Varchar>,
        content -> Nullable<Text>,
        image_url -> Nullable<Varchar>,
        dimensions -> Nullable<Varchar>,
        target_plan_id -> Nullable<Int4>,
        click_tracking -> Nullable<Bool>,
        is_active -> Nullable<Bool>,
        usage_count -> Nullable<Int4>,
        conversion_rate -> Nullable<Numeric>,
        created_at -> Nullable<Timestamptz>,
        updated_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    affiliate_tiers (id) {
        id -> Int4,
        name -> Varchar,
        min_referrals -> Nullable<Int4>,
        min_sales -> Nullable<Numeric>,
        commission_rate -> Numeric,
        bonus_rate -> Nullable<Numeric>,
        perks -> Nullable<Jsonb>,
        created_at -> Nullable<Timestamptz>,
        updated_at -> Nullable<Timestamptz>,
    }
}

diesel::joinable!(plan_promotions -> promotional_campaigns (campaign_id));
diesel::joinable!(plan_promotions -> pricing_plans (plan_id));
diesel::joinable!(discount_codes -> promotional_campaigns (campaign_id));
diesel::joinable!(discount_codes -> affiliates (created_by_affiliate_id));
diesel::joinable!(pricing_experiments -> pricing_plans (plan_id));
diesel::joinable!(referrals -> affiliates (affiliate_id));
diesel::joinable!(commissions -> affiliates (affiliate_id));
diesel::joinable!(commissions -> referrals (referral_id));
diesel::joinable!(commissions -> pricing_plans (plan_id));
diesel::joinable!(affiliate_payouts -> affiliates (affiliate_id));
diesel::joinable!(affiliate_materials -> pricing_plans (target_plan_id));

diesel::allow_tables_to_appear_in_same_query!(
    refresh_tokens,
    revoked_tokens,
    sessions,
    user_permissions,
    users,
    pricing_plans,
    promotional_campaigns,
    plan_promotions,
    discount_codes,
    pricing_experiments,
    affiliates,
    referrals,
    commissions,
    affiliate_payouts,
    affiliate_materials,
    affiliate_tiers,
);
