apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: epsx-production

bases:
  - ../../base

namespace: epsx

patchesStrategicMerge:
  - patches/backend-hpa.yaml
  - patches/frontend-hpa.yaml
  - patches/security-hardening.yaml
  - patches/production-storage.yaml

configMapGenerator:
  - name: epsx-env
    envs:
      - ../../../environments/production.env

secretGenerator:
  - name: epsx-secrets
    envs:
      - ../../../environments/.secrets.production

images:
  - name: epsx-backend
    newName: epsx-backend
    newTag: latest
  - name: epsx-frontend
    newName: epsx-frontend
    newTag: latest
  - name: epsx-admin-frontend
    newName: epsx-admin-frontend
    newTag: latest

replicas:
  - name: backend
    count: 3
  - name: frontend
    count: 3
  - name: admin-frontend
    count: 2