import { createDatabase, createLocalDatabase } from '@tinacms/datalayer';

const isLocal = process.env.TINA_PUBLIC_IS_LOCAL === 'true';

export const database = isLocal
  ? createLocalDatabase()
  : createDatabase({
      namespace: process.env.TINA_CLIENT_ID!,
      token: process.env.TINA_TOKEN!,
      gitProvider: {
        repo: process.env.CONTENT_GITHUB_REPO!,
        branch: process.env.NEXT_PUBLIC_TINA_BRANCH || 'main'
      }
    });

export { tinaField, useTina } from 'tinacms/dist/react';

// Types will be generated by TinaCMS
export type { NewsQuery, NewsConnectionQuery } from '../../tina/__generated__/types';