// @generated automatically by Diesel CLI.

/// A module containing custom SQL type definitions
///
/// (Automatically generated by Diesel.)
pub mod sql_types {
    /// The `admin_module` SQL type
    ///
    /// (Automatically generated by Diesel.)
    #[derive(diesel::query_builder::QueryId, Clone, Debug, PartialEq, Eq, diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "admin_module"))]
    pub struct AdminModule;

    /// The `delivery_channel` SQL type
    ///
    /// (Automatically generated by Diesel.)
    #[derive(diesel::query_builder::QueryId, Clone, Debug, PartialEq, Eq, diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "delivery_channel"))]
    pub struct DeliveryChannel;

    /// The `delivery_status` SQL type
    ///
    /// (Automatically generated by Diesel.)
    #[derive(diesel::query_builder::QueryId, Clone, Debug, PartialEq, Eq, diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "delivery_status"))]
    pub struct DeliveryStatus;

    /// The `notification_priority` SQL type
    ///
    /// (Automatically generated by Diesel.)
    #[derive(diesel::query_builder::QueryId, Clone, Debug, PartialEq, Eq, diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "notification_priority"))]
    pub struct NotificationPriority;

    /// The `notification_type` SQL type
    ///
    /// (Automatically generated by Diesel.)
    #[derive(diesel::query_builder::QueryId, Clone, Debug, PartialEq, Eq, diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "notification_type"))]
    pub struct NotificationType;
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;
    use super::sql_types::AdminModule;

    /// Representation of the `admin_modules` table.
    ///
    /// (Automatically generated by Diesel.)
    admin_modules (id) {
        /// The `id` column of the `admin_modules` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `module_code` column of the `admin_modules` table.
        ///
        /// Its SQL type is `AdminModule`.
        ///
        /// (Automatically generated by Diesel.)
        module_code -> AdminModule,
        /// The `module_name` column of the `admin_modules` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        module_name -> Varchar,
        /// The `description` column of the `admin_modules` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Text,
        /// The `icon` column of the `admin_modules` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        icon -> Nullable<Varchar>,
        /// The `color` column of the `admin_modules` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        color -> Nullable<Varchar>,
        /// The `is_active` column of the `admin_modules` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        is_active -> Nullable<Bool>,
        /// The `created_at` column of the `admin_modules` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Nullable<Timestamptz>,
        /// The `updated_at` column of the `admin_modules` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;
    use super::sql_types::AdminModule;

    /// Representation of the `admin_role_audit` table.
    ///
    /// (Automatically generated by Diesel.)
    admin_role_audit (id) {
        /// The `id` column of the `admin_role_audit` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `firebase_uid` column of the `admin_role_audit` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 128]
        firebase_uid -> Varchar,
        /// The `module_code` column of the `admin_role_audit` table.
        ///
        /// Its SQL type is `AdminModule`.
        ///
        /// (Automatically generated by Diesel.)
        module_code -> AdminModule,
        /// The `action` column of the `admin_role_audit` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        action -> Varchar,
        /// The `performed_by` column of the `admin_role_audit` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 128]
        performed_by -> Nullable<Varchar>,
        /// The `reason` column of the `admin_role_audit` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        reason -> Nullable<Text>,
        /// The `metadata` column of the `admin_role_audit` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        metadata -> Nullable<Jsonb>,
        /// The `timestamp` column of the `admin_role_audit` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        timestamp -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Representation of the `audit_logs` table.
    ///
    /// (Automatically generated by Diesel.)
    audit_logs (id) {
        /// The `id` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `actor_id` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        actor_id -> Nullable<Uuid>,
        /// The `user_id` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Nullable<Uuid>,
        /// The `action` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        action -> Varchar,
        /// The `resource_type` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        resource_type -> Varchar,
        /// The `resource_id` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        resource_id -> Nullable<Varchar>,
        /// The `result` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        result -> Nullable<Varchar>,
        /// The `severity` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        severity -> Nullable<Varchar>,
        /// The `details` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        details -> Nullable<Jsonb>,
        /// The `ip_address` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Inet>`.
        ///
        /// (Automatically generated by Diesel.)
        ip_address -> Nullable<Inet>,
        /// The `user_agent` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_agent -> Nullable<Text>,
        /// The `timestamp` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        timestamp -> Timestamptz,
        /// The `session_id` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        session_id -> Nullable<Uuid>,
        /// The `platform_id` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        platform_id -> Nullable<Uuid>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Representation of the `eps_growth_analytics` table.
    ///
    /// (Automatically generated by Diesel.)
    eps_growth_analytics (id) {
        /// The `id` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `symbol` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 10]
        symbol -> Varchar,
        /// The `name` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        name -> Varchar,
        /// The `country` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        country -> Varchar,
        /// The `sector` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        sector -> Nullable<Varchar>,
        /// The `exchange` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        exchange -> Nullable<Varchar>,
        /// The `current_eps` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Nullable<Numeric>`.
        ///
        /// (Automatically generated by Diesel.)
        current_eps -> Nullable<Numeric>,
        /// The `qoq_growth_rate` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Nullable<Numeric>`.
        ///
        /// (Automatically generated by Diesel.)
        qoq_growth_rate -> Nullable<Numeric>,
        /// The `price_current` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Nullable<Numeric>`.
        ///
        /// (Automatically generated by Diesel.)
        price_current -> Nullable<Numeric>,
        /// The `market_cap` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        market_cap -> Nullable<Int8>,
        /// The `volume` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        volume -> Nullable<Int8>,
        /// The `ranking_score` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Nullable<Numeric>`.
        ///
        /// (Automatically generated by Diesel.)
        ranking_score -> Nullable<Numeric>,
        /// The `created_at` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Nullable<Timestamptz>,
        /// The `updated_at` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Representation of the `fcm_tokens` table.
    ///
    /// (Automatically generated by Diesel.)
    fcm_tokens (id) {
        /// The `id` column of the `fcm_tokens` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `user_id` column of the `fcm_tokens` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `token` column of the `fcm_tokens` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        token -> Text,
        /// The `platform` column of the `fcm_tokens` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        platform -> Varchar,
        /// The `device_info` column of the `fcm_tokens` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        device_info -> Nullable<Jsonb>,
        /// The `topics` column of the `fcm_tokens` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        topics -> Nullable<Jsonb>,
        /// The `is_active` column of the `fcm_tokens` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        is_active -> Nullable<Bool>,
        /// The `last_used_at` column of the `fcm_tokens` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        last_used_at -> Nullable<Timestamptz>,
        /// The `created_at` column of the `fcm_tokens` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Nullable<Timestamptz>,
        /// The `updated_at` column of the `fcm_tokens` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Representation of the `fcm_topics` table.
    ///
    /// (Automatically generated by Diesel.)
    fcm_topics (id) {
        /// The `id` column of the `fcm_topics` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `name` column of the `fcm_topics` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        name -> Varchar,
        /// The `display_name` column of the `fcm_topics` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 200]
        display_name -> Varchar,
        /// The `description` column of the `fcm_topics` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Nullable<Text>,
        /// The `target_permissions` column of the `fcm_topics` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        target_permissions -> Nullable<Jsonb>,
        /// The `is_active` column of the `fcm_topics` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        is_active -> Nullable<Bool>,
        /// The `created_by` column of the `fcm_topics` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        created_by -> Nullable<Uuid>,
        /// The `created_at` column of the `fcm_topics` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Nullable<Timestamptz>,
        /// The `updated_at` column of the `fcm_topics` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Representation of the `firebase_sessions` table.
    ///
    /// (Automatically generated by Diesel.)
    firebase_sessions (id) {
        /// The `id` column of the `firebase_sessions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `user_id` column of the `firebase_sessions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `firebase_uid` column of the `firebase_sessions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 128]
        firebase_uid -> Varchar,
        /// The `id_token` column of the `firebase_sessions` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        id_token -> Text,
        /// The `refresh_token` column of the `firebase_sessions` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        refresh_token -> Nullable<Text>,
        /// The `expires_at` column of the `firebase_sessions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Timestamptz,
        /// The `claims` column of the `firebase_sessions` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        claims -> Nullable<Jsonb>,
        /// The `created_at` column of the `firebase_sessions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `firebase_sessions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;
    use super::sql_types::DeliveryChannel;
    use super::sql_types::DeliveryStatus;

    /// Representation of the `notification_deliveries` table.
    ///
    /// (Automatically generated by Diesel.)
    notification_deliveries (id) {
        /// The `id` column of the `notification_deliveries` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `notification_id` column of the `notification_deliveries` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        notification_id -> Uuid,
        /// The `user_id` column of the `notification_deliveries` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `channel` column of the `notification_deliveries` table.
        ///
        /// Its SQL type is `DeliveryChannel`.
        ///
        /// (Automatically generated by Diesel.)
        channel -> DeliveryChannel,
        /// The `status` column of the `notification_deliveries` table.
        ///
        /// Its SQL type is `DeliveryStatus`.
        ///
        /// (Automatically generated by Diesel.)
        status -> DeliveryStatus,
        /// The `fcm_message_id` column of the `notification_deliveries` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        fcm_message_id -> Nullable<Text>,
        /// The `error_message` column of the `notification_deliveries` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        error_message -> Nullable<Text>,
        /// The `delivered_at` column of the `notification_deliveries` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        delivered_at -> Nullable<Timestamptz>,
        /// The `read_at` column of the `notification_deliveries` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        read_at -> Nullable<Timestamptz>,
        /// The `clicked_at` column of the `notification_deliveries` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        clicked_at -> Nullable<Timestamptz>,
        /// The `created_at` column of the `notification_deliveries` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;
    use super::sql_types::NotificationType;
    use super::sql_types::NotificationPriority;
    use super::sql_types::DeliveryChannel;

    /// Representation of the `notifications` table.
    ///
    /// (Automatically generated by Diesel.)
    notifications (id) {
        /// The `id` column of the `notifications` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `recipient_user_id` column of the `notifications` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        recipient_user_id -> Nullable<Uuid>,
        /// The `fcm_topic_id` column of the `notifications` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        fcm_topic_id -> Nullable<Uuid>,
        /// The `title` column of the `notifications` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        title -> Varchar,
        /// The `body` column of the `notifications` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        body -> Text,
        /// The `notification_type` column of the `notifications` table.
        ///
        /// Its SQL type is `NotificationType`.
        ///
        /// (Automatically generated by Diesel.)
        notification_type -> NotificationType,
        /// The `priority` column of the `notifications` table.
        ///
        /// Its SQL type is `NotificationPriority`.
        ///
        /// (Automatically generated by Diesel.)
        priority -> NotificationPriority,
        /// The `channels` column of the `notifications` table.
        ///
        /// Its SQL type is `Array<Nullable<DeliveryChannel>>`.
        ///
        /// (Automatically generated by Diesel.)
        channels -> Array<Nullable<DeliveryChannel>>,
        /// The `data_payload` column of the `notifications` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        data_payload -> Nullable<Jsonb>,
        /// The `image_url` column of the `notifications` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        image_url -> Nullable<Text>,
        /// The `action_url` column of the `notifications` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        action_url -> Nullable<Text>,
        /// The `scheduled_at` column of the `notifications` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        scheduled_at -> Nullable<Timestamptz>,
        /// The `expires_at` column of the `notifications` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Nullable<Timestamptz>,
        /// The `created_by` column of the `notifications` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        created_by -> Nullable<Uuid>,
        /// The `created_at` column of the `notifications` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Representation of the `oidc_refresh_tokens` table.
    ///
    /// (Automatically generated by Diesel.)
    oidc_refresh_tokens (id) {
        /// The `id` column of the `oidc_refresh_tokens` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `jti` column of the `oidc_refresh_tokens` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        jti -> Varchar,
        /// The `user_id` column of the `oidc_refresh_tokens` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        user_id -> Varchar,
        /// The `token_hash` column of the `oidc_refresh_tokens` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        token_hash -> Varchar,
        /// The `expires_at` column of the `oidc_refresh_tokens` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Timestamptz,
        /// The `created_at` column of the `oidc_refresh_tokens` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `last_used_at` column of the `oidc_refresh_tokens` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        last_used_at -> Nullable<Timestamptz>,
        /// The `revoked` column of the `oidc_refresh_tokens` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        revoked -> Bool,
        /// The `revoked_at` column of the `oidc_refresh_tokens` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        revoked_at -> Nullable<Timestamptz>,
        /// The `revoked_reason` column of the `oidc_refresh_tokens` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        revoked_reason -> Nullable<Text>,
        /// The `client_id` column of the `oidc_refresh_tokens` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        client_id -> Nullable<Varchar>,
        /// The `scope` column of the `oidc_refresh_tokens` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        scope -> Nullable<Text>,
        /// The `metadata` column of the `oidc_refresh_tokens` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        metadata -> Nullable<Jsonb>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Representation of the `oidc_token_audit` table.
    ///
    /// (Automatically generated by Diesel.)
    oidc_token_audit (id) {
        /// The `id` column of the `oidc_token_audit` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `operation` column of the `oidc_token_audit` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        operation -> Varchar,
        /// The `table_name` column of the `oidc_token_audit` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        table_name -> Varchar,
        /// The `record_id` column of the `oidc_token_audit` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        record_id -> Nullable<Uuid>,
        /// The `jti` column of the `oidc_token_audit` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        jti -> Nullable<Varchar>,
        /// The `user_id` column of the `oidc_token_audit` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        user_id -> Nullable<Varchar>,
        /// The `old_values` column of the `oidc_token_audit` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        old_values -> Nullable<Jsonb>,
        /// The `new_values` column of the `oidc_token_audit` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        new_values -> Nullable<Jsonb>,
        /// The `changed_by` column of the `oidc_token_audit` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        changed_by -> Nullable<Varchar>,
        /// The `changed_at` column of the `oidc_token_audit` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        changed_at -> Timestamptz,
        /// The `ip_address` column of the `oidc_token_audit` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        ip_address -> Nullable<Text>,
        /// The `user_agent` column of the `oidc_token_audit` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_agent -> Nullable<Text>,
        /// The `session_id` column of the `oidc_token_audit` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        session_id -> Nullable<Varchar>,
        /// The `additional_data` column of the `oidc_token_audit` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        additional_data -> Nullable<Jsonb>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Representation of the `refresh_tokens` table.
    ///
    /// (Automatically generated by Diesel.)
    refresh_tokens (id) {
        /// The `id` column of the `refresh_tokens` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `user_id` column of the `refresh_tokens` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Text,
        /// The `token_hash` column of the `refresh_tokens` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        token_hash -> Text,
        /// The `family_id` column of the `refresh_tokens` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        family_id -> Uuid,
        /// The `expires_at` column of the `refresh_tokens` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Timestamptz,
        /// The `created_at` column of the `refresh_tokens` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `refresh_tokens` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// The `last_used_at` column of the `refresh_tokens` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        last_used_at -> Nullable<Timestamptz>,
        /// The `device_info` column of the `refresh_tokens` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        device_info -> Nullable<Jsonb>,
        /// The `ip_address` column of the `refresh_tokens` table.
        ///
        /// Its SQL type is `Nullable<Inet>`.
        ///
        /// (Automatically generated by Diesel.)
        ip_address -> Nullable<Inet>,
        /// The `user_agent` column of the `refresh_tokens` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_agent -> Nullable<Text>,
        /// The `is_revoked` column of the `refresh_tokens` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_revoked -> Bool,
        /// The `revoked_at` column of the `refresh_tokens` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        revoked_at -> Nullable<Timestamptz>,
        /// The `revoked_reason` column of the `refresh_tokens` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        revoked_reason -> Nullable<Text>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Representation of the `revoked_tokens` table.
    ///
    /// (Automatically generated by Diesel.)
    revoked_tokens (id) {
        /// The `id` column of the `revoked_tokens` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `jti` column of the `revoked_tokens` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        jti -> Text,
        /// The `user_id` column of the `revoked_tokens` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Text,
        /// The `token_type` column of the `revoked_tokens` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        token_type -> Text,
        /// The `expires_at` column of the `revoked_tokens` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Timestamptz,
        /// The `revoked_at` column of the `revoked_tokens` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        revoked_at -> Timestamptz,
        /// The `revoked_by` column of the `revoked_tokens` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        revoked_by -> Nullable<Text>,
        /// The `revoked_reason` column of the `revoked_tokens` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        revoked_reason -> Text,
        /// The `created_at` column of the `revoked_tokens` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Representation of the `security_events` table.
    ///
    /// (Automatically generated by Diesel.)
    security_events (id) {
        /// The `id` column of the `security_events` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `event_type` column of the `security_events` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        event_type -> Varchar,
        /// The `severity` column of the `security_events` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        severity -> Varchar,
        /// The `user_id` column of the `security_events` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        user_id -> Nullable<Varchar>,
        /// The `ip_address` column of the `security_events` table.
        ///
        /// Its SQL type is `Nullable<Inet>`.
        ///
        /// (Automatically generated by Diesel.)
        ip_address -> Nullable<Inet>,
        /// The `request_path` column of the `security_events` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        request_path -> Nullable<Text>,
        /// The `event_data` column of the `security_events` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        event_data -> Nullable<Jsonb>,
        /// The `risk_score` column of the `security_events` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        risk_score -> Nullable<Int4>,
        /// The `blocked` column of the `security_events` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        blocked -> Nullable<Bool>,
        /// The `timestamp` column of the `security_events` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        timestamp -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Representation of the `sessions` table.
    ///
    /// (Automatically generated by Diesel.)
    sessions (id) {
        /// The `id` column of the `sessions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `user_id` column of the `sessions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `access_token` column of the `sessions` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        access_token -> Text,
        /// The `expires_at` column of the `sessions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Timestamptz,
        /// The `provider` column of the `sessions` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        provider -> Nullable<Varchar>,
        /// The `session_token` column of the `sessions` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        session_token -> Nullable<Text>,
        /// The `user_agent` column of the `sessions` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_agent -> Nullable<Text>,
        /// The `ip_address` column of the `sessions` table.
        ///
        /// Its SQL type is `Nullable<Inet>`.
        ///
        /// (Automatically generated by Diesel.)
        ip_address -> Nullable<Inet>,
        /// The `is_active` column of the `sessions` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_active -> Bool,
        /// The `created_at` column of the `sessions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;
    use super::sql_types::AdminModule;

    /// Representation of the `user_admin_roles` table.
    ///
    /// (Automatically generated by Diesel.)
    user_admin_roles (id) {
        /// The `id` column of the `user_admin_roles` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `firebase_uid` column of the `user_admin_roles` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 128]
        firebase_uid -> Varchar,
        /// The `module_code` column of the `user_admin_roles` table.
        ///
        /// Its SQL type is `AdminModule`.
        ///
        /// (Automatically generated by Diesel.)
        module_code -> AdminModule,
        /// The `granted_by` column of the `user_admin_roles` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 128]
        granted_by -> Nullable<Varchar>,
        /// The `expires_at` column of the `user_admin_roles` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Nullable<Timestamptz>,
        /// The `is_active` column of the `user_admin_roles` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        is_active -> Nullable<Bool>,
        /// The `created_at` column of the `user_admin_roles` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Nullable<Timestamptz>,
        /// The `updated_at` column of the `user_admin_roles` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Admin-controlled dynamic limits for stock rankings and API access, replacing fixed tier system
    user_dynamic_limits (id) {
        /// The `id` column of the `user_dynamic_limits` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `user_id` column of the `user_dynamic_limits` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// Number of stock rankings user can access, -1 for unlimited
        ranking_limit -> Nullable<Int4>,
        /// API requests per minute limit, -1 for unlimited
        requests_per_minute -> Nullable<Int4>,
        /// API requests per hour limit, -1 for unlimited
        requests_per_hour -> Nullable<Int4>,
        /// The `requests_per_day` column of the `user_dynamic_limits` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        requests_per_day -> Nullable<Int4>,
        /// Array of API endpoint patterns user can access, e.g. ["enterprise/*"]
        api_endpoints -> Nullable<Array<Nullable<Text>>>,
        /// The `assigned_by` column of the `user_dynamic_limits` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        assigned_by -> Uuid,
        /// The `reason` column of the `user_dynamic_limits` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        reason -> Text,
        /// Priority for resolving conflicts when multiple limits apply (higher wins)
        priority -> Int4,
        /// The `effective_from` column of the `user_dynamic_limits` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        effective_from -> Timestamp,
        /// When this limit assignment expires, NULL for permanent
        expires_at -> Nullable<Timestamp>,
        /// The `created_at` column of the `user_dynamic_limits` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamp,
        /// The `updated_at` column of the `user_dynamic_limits` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamp,
        /// JSON snapshot of previous limits before this change for audit trail
        previous_limits -> Nullable<Jsonb>,
        /// The `change_source` column of the `user_dynamic_limits` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        change_source -> Varchar,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Representation of the `user_notification_preferences` table.
    ///
    /// (Automatically generated by Diesel.)
    user_notification_preferences (user_id) {
        /// The `user_id` column of the `user_notification_preferences` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `fcm_enabled` column of the `user_notification_preferences` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        fcm_enabled -> Nullable<Bool>,
        /// The `in_app_enabled` column of the `user_notification_preferences` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        in_app_enabled -> Nullable<Bool>,
        /// The `email_enabled` column of the `user_notification_preferences` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        email_enabled -> Nullable<Bool>,
        /// The `quiet_hours_start` column of the `user_notification_preferences` table.
        ///
        /// Its SQL type is `Nullable<Time>`.
        ///
        /// (Automatically generated by Diesel.)
        quiet_hours_start -> Nullable<Time>,
        /// The `quiet_hours_end` column of the `user_notification_preferences` table.
        ///
        /// Its SQL type is `Nullable<Time>`.
        ///
        /// (Automatically generated by Diesel.)
        quiet_hours_end -> Nullable<Time>,
        /// The `timezone` column of the `user_notification_preferences` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        timezone -> Nullable<Varchar>,
        /// The `blocked_topics` column of the `user_notification_preferences` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        blocked_topics -> Nullable<Jsonb>,
        /// The `created_at` column of the `user_notification_preferences` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Nullable<Timestamptz>,
        /// The `updated_at` column of the `user_notification_preferences` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Representation of the `user_notifications` table.
    ///
    /// (Automatically generated by Diesel.)
    user_notifications (id) {
        /// The `id` column of the `user_notifications` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `user_id` column of the `user_notifications` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Varchar,
        /// The `notification_id` column of the `user_notifications` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        notification_id -> Uuid,
        /// The `read_at` column of the `user_notifications` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        read_at -> Nullable<Timestamptz>,
        /// The `clicked_at` column of the `user_notifications` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        clicked_at -> Nullable<Timestamptz>,
        /// The `dismissed_at` column of the `user_notifications` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        dismissed_at -> Nullable<Timestamptz>,
        /// The `delivered_at` column of the `user_notifications` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        delivered_at -> Nullable<Timestamptz>,
        /// The `delivery_status` column of the `user_notifications` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        delivery_status -> Nullable<Varchar>,
        /// The `created_at` column of the `user_notifications` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Individual user permissions - migrated from users.permissions array
    user_permissions (id) {
        /// The `id` column of the `user_permissions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `user_id` column of the `user_permissions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// Permission string in format platform:resource:action
        #[max_length = 255]
        permission -> Varchar,
        /// When the permission was granted
        granted_at -> Nullable<Timestamptz>,
        /// User who granted this permission (nullable for system grants)
        granted_by -> Nullable<Uuid>,
        /// When permission expires (nullable for permanent permissions)
        expires_at -> Nullable<Timestamptz>,
        /// Whether permission is currently active
        is_active -> Nullable<Bool>,
        /// The `created_at` column of the `user_permissions` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Nullable<Timestamptz>,
        /// The `updated_at` column of the `user_permissions` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Representation of the `users` table.
    ///
    /// (Automatically generated by Diesel.)
    users (id) {
        /// The `id` column of the `users` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `firebase_uid` column of the `users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 128]
        firebase_uid -> Varchar,
        /// The `email` column of the `users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        email -> Varchar,
        /// The `display_name` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        display_name -> Nullable<Varchar>,
        /// The `name` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        name -> Nullable<Varchar>,
        /// The `avatar_url` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        avatar_url -> Nullable<Text>,
        /// The `package_tier` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        package_tier -> Nullable<Varchar>,
        /// The `email_verified` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        email_verified -> Nullable<Bool>,
        /// The `is_active` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        is_active -> Nullable<Bool>,
        /// The `last_login_at` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        last_login_at -> Nullable<Timestamptz>,
        /// The `created_at` column of the `users` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `users` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// The `primary_platform_id` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        primary_platform_id -> Nullable<Uuid>,
    }
}

diesel::joinable!(audit_logs -> sessions (session_id));
diesel::joinable!(fcm_tokens -> users (user_id));
diesel::joinable!(fcm_topics -> users (created_by));
diesel::joinable!(firebase_sessions -> users (user_id));
diesel::joinable!(notification_deliveries -> notifications (notification_id));
diesel::joinable!(notification_deliveries -> users (user_id));
diesel::joinable!(notifications -> fcm_topics (fcm_topic_id));
diesel::joinable!(sessions -> users (user_id));
diesel::joinable!(user_notification_preferences -> users (user_id));
diesel::joinable!(user_notifications -> notifications (notification_id));

diesel::allow_tables_to_appear_in_same_query!(
    admin_modules,
    admin_role_audit,
    audit_logs,
    eps_growth_analytics,
    fcm_tokens,
    fcm_topics,
    firebase_sessions,
    notification_deliveries,
    notifications,
    oidc_refresh_tokens,
    oidc_token_audit,
    refresh_tokens,
    revoked_tokens,
    security_events,
    sessions,
    user_admin_roles,
    user_dynamic_limits,
    user_notification_preferences,
    user_notifications,
    user_permissions,
    users,
);
