// @generated automatically by Diesel CLI.

/// A module containing custom SQL type definitions
///
/// (Automatically generated by Diesel.)
pub mod sql_types {
    /// The `user_role` SQL type
    ///
    /// (Automatically generated by Diesel.)
    #[derive(diesel::query_builder::QueryId, Clone, Debug, PartialEq, Eq, diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "user_role"))]
    pub struct UserRole;
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Representation of the `_sqlx_migrations` table.
    ///
    /// (Automatically generated by Diesel.)
    _sqlx_migrations (version) {
        /// The `version` column of the `_sqlx_migrations` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        version -> Int8,
        /// The `description` column of the `_sqlx_migrations` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Text,
        /// The `installed_on` column of the `_sqlx_migrations` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        installed_on -> Timestamptz,
        /// The `success` column of the `_sqlx_migrations` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        success -> Bool,
        /// The `checksum` column of the `_sqlx_migrations` table.
        ///
        /// Its SQL type is `Bytea`.
        ///
        /// (Automatically generated by Diesel.)
        checksum -> Bytea,
        /// The `execution_time` column of the `_sqlx_migrations` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        execution_time -> Int8,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Comprehensive audit logging - cleaned of legacy references
    audit_logs (id) {
        /// The `id` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `actor_id` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        actor_id -> Nullable<Uuid>,
        /// The `user_id` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Nullable<Uuid>,
        /// The `action` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        action -> Varchar,
        /// The `resource_type` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        resource_type -> Varchar,
        /// The `resource_id` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        resource_id -> Nullable<Varchar>,
        /// The `result` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        result -> Nullable<Varchar>,
        /// The `event_category` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        event_category -> Nullable<Varchar>,
        /// The `severity` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        severity -> Nullable<Varchar>,
        /// The `success` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        success -> Nullable<Bool>,
        /// The `details` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        details -> Nullable<Jsonb>,
        /// The `metadata` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        metadata -> Nullable<Jsonb>,
        /// The `ip_address` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Inet>`.
        ///
        /// (Automatically generated by Diesel.)
        ip_address -> Nullable<Inet>,
        /// The `user_agent` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_agent -> Nullable<Text>,
        /// The `timestamp` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        timestamp -> Timestamptz,
        /// The `session_id` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        session_id -> Nullable<Uuid>,
        /// IP address of the client making the request
        client_ip -> Nullable<Inet>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Representation of the `eps_growth_analytics` table.
    ///
    /// (Automatically generated by Diesel.)
    eps_growth_analytics (id) {
        /// The `id` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `symbol` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 10]
        symbol -> Varchar,
        /// The `name` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        name -> Varchar,
        /// The `country` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        country -> Varchar,
        /// The `sector` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        sector -> Nullable<Varchar>,
        /// The `exchange` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        exchange -> Nullable<Varchar>,
        /// The `current_eps` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Nullable<Numeric>`.
        ///
        /// (Automatically generated by Diesel.)
        current_eps -> Nullable<Numeric>,
        /// The `qoq_growth_rate` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Nullable<Numeric>`.
        ///
        /// (Automatically generated by Diesel.)
        qoq_growth_rate -> Nullable<Numeric>,
        /// The `price_current` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Nullable<Numeric>`.
        ///
        /// (Automatically generated by Diesel.)
        price_current -> Nullable<Numeric>,
        /// The `market_cap` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        market_cap -> Nullable<Int8>,
        /// The `volume` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        volume -> Nullable<Int8>,
        /// The `ranking_score` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Nullable<Numeric>`.
        ///
        /// (Automatically generated by Diesel.)
        ranking_score -> Nullable<Numeric>,
        /// The `created_at` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Nullable<Timestamp>,
        /// The `updated_at` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Nullable<Timestamp>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Firebase authentication session management
    firebase_sessions (id) {
        /// The `id` column of the `firebase_sessions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `firebase_uid` column of the `firebase_sessions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 128]
        firebase_uid -> Varchar,
        /// The `session_token` column of the `firebase_sessions` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        session_token -> Text,
        /// The `firebase_token_id` column of the `firebase_sessions` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        firebase_token_id -> Nullable<Text>,
        /// The `expires_at` column of the `firebase_sessions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Timestamptz,
        /// The `user_agent` column of the `firebase_sessions` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_agent -> Nullable<Text>,
        /// The `ip_address` column of the `firebase_sessions` table.
        ///
        /// Its SQL type is `Nullable<Inet>`.
        ///
        /// (Automatically generated by Diesel.)
        ip_address -> Nullable<Inet>,
        /// The `is_active` column of the `firebase_sessions` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        is_active -> Nullable<Bool>,
        /// The `created_at` column of the `firebase_sessions` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Nullable<Timestamptz>,
        /// The `last_accessed_at` column of the `firebase_sessions` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        last_accessed_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Representation of the `notifications` table.
    ///
    /// (Automatically generated by Diesel.)
    notifications (id) {
        /// The `id` column of the `notifications` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `user_id` column of the `notifications` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `title` column of the `notifications` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        title -> Varchar,
        /// The `message` column of the `notifications` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        message -> Text,
        /// The `notification_type` column of the `notifications` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        notification_type -> Varchar,
        /// The `priority` column of the `notifications` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        priority -> Varchar,
        /// The `is_read` column of the `notifications` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_read -> Bool,
        /// The `created_at` column of the `notifications` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `expires_at` column of the `notifications` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Nullable<Timestamptz>,
        /// The `metadata` column of the `notifications` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        metadata -> Nullable<Jsonb>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Middleware performance metrics for monitoring and optimization
    performance_metrics (id) {
        /// The `id` column of the `performance_metrics` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `timestamp` column of the `performance_metrics` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        timestamp -> Timestamptz,
        /// The `middleware_execution_time` column of the `performance_metrics` table.
        ///
        /// Its SQL type is `Numeric`.
        ///
        /// (Automatically generated by Diesel.)
        middleware_execution_time -> Numeric,
        /// The `cache_hit_rate` column of the `performance_metrics` table.
        ///
        /// Its SQL type is `Numeric`.
        ///
        /// (Automatically generated by Diesel.)
        cache_hit_rate -> Numeric,
        /// The `session_validation_time` column of the `performance_metrics` table.
        ///
        /// Its SQL type is `Numeric`.
        ///
        /// (Automatically generated by Diesel.)
        session_validation_time -> Numeric,
        /// The `permission_check_time` column of the `performance_metrics` table.
        ///
        /// Its SQL type is `Numeric`.
        ///
        /// (Automatically generated by Diesel.)
        permission_check_time -> Numeric,
        /// The `total_request_time` column of the `performance_metrics` table.
        ///
        /// Its SQL type is `Numeric`.
        ///
        /// (Automatically generated by Diesel.)
        total_request_time -> Numeric,
        /// The `requests_per_minute` column of the `performance_metrics` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        requests_per_minute -> Int4,
        /// The `error_rate` column of the `performance_metrics` table.
        ///
        /// Its SQL type is `Numeric`.
        ///
        /// (Automatically generated by Diesel.)
        error_rate -> Numeric,
        /// The `source` column of the `performance_metrics` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        source -> Varchar,
        /// The `additional_metrics` column of the `performance_metrics` table.
        ///
        /// Its SQL type is `Jsonb`.
        ///
        /// (Automatically generated by Diesel.)
        additional_metrics -> Jsonb,
        /// The `created_at` column of the `performance_metrics` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Representation of the `schema_migrations` table.
    ///
    /// (Automatically generated by Diesel.)
    schema_migrations (version) {
        /// The `version` column of the `schema_migrations` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 14]
        version -> Varchar,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Configuration for automated security alerts and notifications
    security_alerts (id) {
        /// The `id` column of the `security_alerts` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `alert_type` column of the `security_alerts` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        alert_type -> Varchar,
        /// The `condition` column of the `security_alerts` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        condition -> Text,
        /// The `threshold` column of the `security_alerts` table.
        ///
        /// Its SQL type is `Jsonb`.
        ///
        /// (Automatically generated by Diesel.)
        threshold -> Jsonb,
        /// The `webhook_url` column of the `security_alerts` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        webhook_url -> Nullable<Text>,
        /// The `email_recipients` column of the `security_alerts` table.
        ///
        /// Its SQL type is `Nullable<Array<Nullable<Text>>>`.
        ///
        /// (Automatically generated by Diesel.)
        email_recipients -> Nullable<Array<Nullable<Text>>>,
        /// The `is_active` column of the `security_alerts` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_active -> Bool,
        /// The `created_at` column of the `security_alerts` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `security_alerts` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// The `triggered_count` column of the `security_alerts` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        triggered_count -> Int4,
        /// The `last_triggered` column of the `security_alerts` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        last_triggered -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Stores security events from middleware operations across all applications
    security_events (id) {
        /// The `id` column of the `security_events` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// Type of security event (UNAUTHORIZED_ACCESS, PERMISSION_DENIED, etc.)
        #[max_length = 100]
        event_type -> Varchar,
        /// Severity level: LOW, MEDIUM, HIGH, CRITICAL
        #[max_length = 20]
        severity -> Varchar,
        /// The `timestamp` column of the `security_events` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        timestamp -> Timestamptz,
        /// The `user_id` column of the `security_events` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        user_id -> Nullable<Varchar>,
        /// The `session_id` column of the `security_events` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        session_id -> Nullable<Varchar>,
        /// The `ip_address` column of the `security_events` table.
        ///
        /// Its SQL type is `Inet`.
        ///
        /// (Automatically generated by Diesel.)
        ip_address -> Inet,
        /// The `user_agent` column of the `security_events` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_agent -> Nullable<Text>,
        /// The `path` column of the `security_events` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 1000]
        path -> Nullable<Varchar>,
        /// The `method` column of the `security_events` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 10]
        method -> Nullable<Varchar>,
        /// Event-specific details in JSON format
        details -> Jsonb,
        /// Application that generated the event
        #[max_length = 50]
        source -> Varchar,
        /// The `resolved` column of the `security_events` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        resolved -> Bool,
        /// The `resolution_notes` column of the `security_events` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        resolution_notes -> Nullable<Text>,
        /// The `created_at` column of the `security_events` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `security_events` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// Risk score for security analysis (0-100)
        risk_score -> Nullable<Int4>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// JWT-based user sessions - optimized for modern auth
    sessions (id) {
        /// The `id` column of the `sessions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `user_id` column of the `sessions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `access_token` column of the `sessions` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        access_token -> Text,
        /// The `expires_at` column of the `sessions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Timestamptz,
        /// The `provider` column of the `sessions` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        provider -> Nullable<Varchar>,
        /// The `provider_account_id` column of the `sessions` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        provider_account_id -> Nullable<Text>,
        /// The `session_token` column of the `sessions` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        session_token -> Nullable<Text>,
        /// The `jwt_token` column of the `sessions` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        jwt_token -> Nullable<Text>,
        /// The `user_agent` column of the `sessions` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_agent -> Nullable<Text>,
        /// The `ip_address` column of the `sessions` table.
        ///
        /// Its SQL type is `Nullable<Inet>`.
        ///
        /// (Automatically generated by Diesel.)
        ip_address -> Nullable<Inet>,
        /// The `is_active` column of the `sessions` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_active -> Bool,
        /// The `created_at` column of the `sessions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;
    use super::sql_types::UserRole;

    /// Core user table with Firebase authentication - cleaned and optimized
    users (id) {
        /// The `id` column of the `users` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `firebase_uid` column of the `users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 128]
        firebase_uid -> Varchar,
        /// The `email` column of the `users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        email -> Varchar,
        /// The `display_name` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        display_name -> Nullable<Varchar>,
        /// The `name` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        name -> Nullable<Varchar>,
        /// The `avatar_url` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        avatar_url -> Nullable<Text>,
        /// The `is_active` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        is_active -> Nullable<Bool>,
        /// The `last_login_at` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        last_login_at -> Nullable<Timestamptz>,
        /// The `created_at` column of the `users` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `users` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// User role determining feature access: admin, user, or guest
        role -> UserRole,
    }
}

diesel::joinable!(audit_logs -> sessions (session_id));
// ============================================================================
// STUB TABLES FOR REMOVED COMPLEX SECURITY FEATURES
// ============================================================================

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;
    
    /// Stub table for attack attempts (brute force detection removed)
    attack_attempts (id) {
        id -> Uuid,
        ip_address -> Inet,
        user_id -> Nullable<Varchar>,
        attempt_type -> Varchar,
        timestamp -> Timestamptz,
        success -> Nullable<Bool>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;
    
    /// Stub table for IP blacklist (IP blocking removed)
    ip_blacklist (id) {
        id -> Uuid,
        ip_address -> Inet,
        reason -> Text,
        created_at -> Timestamptz,
        expires_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;
    
    /// Stub table for security alert rules (complex alerting removed)
    security_alert_rules (id) {
        id -> Uuid,
        name -> Varchar,
        rule_type -> Varchar,
        condition -> Jsonb,
        is_active -> Bool,
        enabled -> Bool,
        created_at -> Timestamptz,
        last_triggered -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;
    
    /// Stub table for alert notifications (complex notifications removed)
    alert_notifications (id) {
        id -> Uuid,
        alert_id -> Uuid,
        channel -> Varchar,
        sent_at -> Timestamptz,
        status -> Varchar,
        created_at -> Timestamptz,
        delivery_status -> Varchar,
    }
}

diesel::joinable!(sessions -> users (user_id));

diesel::allow_tables_to_appear_in_same_query!(
    _sqlx_migrations,
    alert_notifications,
    attack_attempts,
    audit_logs,
    eps_growth_analytics,
    firebase_sessions,
    ip_blacklist,
    notifications,
    performance_metrics,
    schema_migrations,
    security_alert_rules,
    security_alerts,
    security_events,
    sessions,
    users,
);
