// @generated automatically by Diesel CLI.

/// A module containing custom SQL type definitions
///
/// (Automatically generated by Diesel.)
pub mod sql_types {
    /// The `admin_module` SQL type
    ///
    /// (Automatically generated by Diesel.)
    #[derive(diesel::query_builder::QueryId, Clone, Debug, PartialEq, Eq, diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "admin_module"))]
    pub struct AdminModule;

    /// The `notification_priority` SQL type
    ///
    /// (Automatically generated by Diesel.)
    #[derive(diesel::query_builder::QueryId, Clone, Debug, PartialEq, Eq, diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "notification_priority"))]
    pub struct NotificationPriority;

    /// The `notification_type` SQL type
    ///
    /// (Automatically generated by Diesel.)
    #[derive(diesel::query_builder::QueryId, Clone, Debug, PartialEq, Eq, diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "notification_type"))]
    pub struct NotificationType;

    /// The `package_tier` SQL type
    ///
    /// (Automatically generated by Diesel.)
    #[derive(diesel::query_builder::QueryId, Clone, Debug, PartialEq, Eq, diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "package_tier"))]
    pub struct PackageTier;

    /// The `user_role` SQL type
    ///
    /// (Added for role support)
    #[derive(diesel::query_builder::QueryId, Clone, Debug, PartialEq, Eq, diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "user_role"))]
    pub struct UserRole;
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;
    use super::sql_types::AdminModule;

    /// Representation of the `admin_modules` table.
    ///
    /// (Automatically generated by Diesel.)
    admin_modules (id) {
        /// The `id` column of the `admin_modules` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `module_code` column of the `admin_modules` table.
        ///
        /// Its SQL type is `AdminModule`.
        ///
        /// (Automatically generated by Diesel.)
        module_code -> AdminModule,
        /// The `module_name` column of the `admin_modules` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        module_name -> Varchar,
        /// The `description` column of the `admin_modules` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Text,
        /// The `icon` column of the `admin_modules` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        icon -> Nullable<Varchar>,
        /// The `color` column of the `admin_modules` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        color -> Nullable<Varchar>,
        /// The `is_active` column of the `admin_modules` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        is_active -> Nullable<Bool>,
        /// The `created_at` column of the `admin_modules` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Nullable<Timestamptz>,
        /// The `updated_at` column of the `admin_modules` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;
    use super::sql_types::AdminModule;

    /// Representation of the `admin_role_audit` table.
    ///
    /// (Automatically generated by Diesel.)
    admin_role_audit (id) {
        /// The `id` column of the `admin_role_audit` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `firebase_uid` column of the `admin_role_audit` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 128]
        firebase_uid -> Varchar,
        /// The `module_code` column of the `admin_role_audit` table.
        ///
        /// Its SQL type is `AdminModule`.
        ///
        /// (Automatically generated by Diesel.)
        module_code -> AdminModule,
        /// The `action` column of the `admin_role_audit` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        action -> Varchar,
        /// The `performed_by` column of the `admin_role_audit` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 128]
        performed_by -> Nullable<Varchar>,
        /// The `reason` column of the `admin_role_audit` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        reason -> Nullable<Text>,
        /// The `metadata` column of the `admin_role_audit` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        metadata -> Nullable<Jsonb>,
        /// The `timestamp` column of the `admin_role_audit` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        timestamp -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Representation of the `audit_logs` table.
    ///
    /// (Automatically generated by Diesel.)
    audit_logs (id) {
        /// The `id` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `actor_id` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        actor_id -> Nullable<Uuid>,
        /// The `user_id` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Nullable<Uuid>,
        /// The `action` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        action -> Varchar,
        /// The `resource_type` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        resource_type -> Varchar,
        /// The `resource_id` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        resource_id -> Nullable<Varchar>,
        /// The `result` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        result -> Nullable<Varchar>,
        /// The `severity` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        severity -> Nullable<Varchar>,
        /// The `details` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        details -> Nullable<Jsonb>,
        /// The `ip_address` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Inet>`.
        ///
        /// (Automatically generated by Diesel.)
        ip_address -> Nullable<Inet>,
        /// The `user_agent` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_agent -> Nullable<Text>,
        /// The `timestamp` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        timestamp -> Timestamptz,
        /// The `session_id` column of the `audit_logs` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        session_id -> Nullable<Uuid>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Representation of the `eps_growth_analytics` table.
    ///
    /// (Automatically generated by Diesel.)
    eps_growth_analytics (id) {
        /// The `id` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `symbol` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 10]
        symbol -> Varchar,
        /// The `name` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        name -> Varchar,
        /// The `country` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        country -> Varchar,
        /// The `sector` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        sector -> Nullable<Varchar>,
        /// The `exchange` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        exchange -> Nullable<Varchar>,
        /// The `current_eps` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Nullable<Numeric>`.
        ///
        /// (Automatically generated by Diesel.)
        current_eps -> Nullable<Numeric>,
        /// The `qoq_growth_rate` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Nullable<Numeric>`.
        ///
        /// (Automatically generated by Diesel.)
        qoq_growth_rate -> Nullable<Numeric>,
        /// The `price_current` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Nullable<Numeric>`.
        ///
        /// (Automatically generated by Diesel.)
        price_current -> Nullable<Numeric>,
        /// The `market_cap` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        market_cap -> Nullable<Int8>,
        /// The `volume` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        volume -> Nullable<Int8>,
        /// The `ranking_score` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Nullable<Numeric>`.
        ///
        /// (Automatically generated by Diesel.)
        ranking_score -> Nullable<Numeric>,
        /// The `created_at` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Nullable<Timestamptz>,
        /// The `updated_at` column of the `eps_growth_analytics` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Representation of the `firebase_sessions` table.
    ///
    /// (Automatically generated by Diesel.)
    firebase_sessions (id) {
        /// The `id` column of the `firebase_sessions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `user_id` column of the `firebase_sessions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `firebase_uid` column of the `firebase_sessions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 128]
        firebase_uid -> Varchar,
        /// The `id_token` column of the `firebase_sessions` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        id_token -> Text,
        /// The `refresh_token` column of the `firebase_sessions` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        refresh_token -> Nullable<Text>,
        /// The `expires_at` column of the `firebase_sessions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Timestamptz,
        /// The `claims` column of the `firebase_sessions` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        claims -> Nullable<Jsonb>,
        /// The `created_at` column of the `firebase_sessions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `firebase_sessions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Representation of the `notification_preferences` table.
    ///
    /// (Automatically generated by Diesel.)
    notification_preferences (id) {
        /// The `id` column of the `notification_preferences` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `user_id` column of the `notification_preferences` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `email_enabled` column of the `notification_preferences` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        email_enabled -> Nullable<Bool>,
        /// The `push_enabled` column of the `notification_preferences` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        push_enabled -> Nullable<Bool>,
        /// The `feature_expiration` column of the `notification_preferences` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        feature_expiration -> Nullable<Bool>,
        /// The `security_alerts` column of the `notification_preferences` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        security_alerts -> Nullable<Bool>,
        /// The `account_updates` column of the `notification_preferences` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        account_updates -> Nullable<Bool>,
        /// The `marketing` column of the `notification_preferences` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        marketing -> Nullable<Bool>,
        /// The `created_at` column of the `notification_preferences` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `notification_preferences` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;
    use super::sql_types::NotificationType;
    use super::sql_types::NotificationPriority;

    /// Representation of the `notifications` table.
    ///
    /// (Automatically generated by Diesel.)
    notifications (id) {
        /// The `id` column of the `notifications` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `user_id` column of the `notifications` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `title` column of the `notifications` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        title -> Varchar,
        /// The `message` column of the `notifications` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        message -> Text,
        /// The `notification_type` column of the `notifications` table.
        ///
        /// Its SQL type is `NotificationType`.
        ///
        /// (Automatically generated by Diesel.)
        notification_type -> NotificationType,
        /// The `priority` column of the `notifications` table.
        ///
        /// Its SQL type is `NotificationPriority`.
        ///
        /// (Automatically generated by Diesel.)
        priority -> NotificationPriority,
        /// The `is_read` column of the `notifications` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_read -> Bool,
        /// The `delivery_status` column of the `notifications` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        delivery_status -> Nullable<Varchar>,
        /// The `delivered_at` column of the `notifications` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        delivered_at -> Nullable<Timestamptz>,
        /// The `created_at` column of the `notifications` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `expires_at` column of the `notifications` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Nullable<Timestamptz>,
        /// The `metadata` column of the `notifications` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        metadata -> Nullable<Jsonb>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Representation of the `security_events` table.
    ///
    /// (Automatically generated by Diesel.)
    security_events (id) {
        /// The `id` column of the `security_events` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `event_type` column of the `security_events` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        event_type -> Varchar,
        /// The `severity` column of the `security_events` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 20]
        severity -> Varchar,
        /// The `user_id` column of the `security_events` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        user_id -> Nullable<Varchar>,
        /// The `ip_address` column of the `security_events` table.
        ///
        /// Its SQL type is `Nullable<Inet>`.
        ///
        /// (Automatically generated by Diesel.)
        ip_address -> Nullable<Inet>,
        /// The `request_path` column of the `security_events` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        request_path -> Nullable<Text>,
        /// The `event_data` column of the `security_events` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        event_data -> Nullable<Jsonb>,
        /// The `risk_score` column of the `security_events` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        risk_score -> Nullable<Int4>,
        /// The `blocked` column of the `security_events` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        blocked -> Nullable<Bool>,
        /// The `timestamp` column of the `security_events` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        timestamp -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;

    /// Representation of the `sessions` table.
    ///
    /// (Automatically generated by Diesel.)
    sessions (id) {
        /// The `id` column of the `sessions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `user_id` column of the `sessions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `access_token` column of the `sessions` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        access_token -> Text,
        /// The `expires_at` column of the `sessions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Timestamptz,
        /// The `provider` column of the `sessions` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        provider -> Nullable<Varchar>,
        /// The `session_token` column of the `sessions` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        session_token -> Nullable<Text>,
        /// The `user_agent` column of the `sessions` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        user_agent -> Nullable<Text>,
        /// The `ip_address` column of the `sessions` table.
        ///
        /// Its SQL type is `Nullable<Inet>`.
        ///
        /// (Automatically generated by Diesel.)
        ip_address -> Nullable<Inet>,
        /// The `is_active` column of the `sessions` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_active -> Bool,
        /// The `created_at` column of the `sessions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;
    use super::sql_types::AdminModule;

    /// Representation of the `user_admin_roles` table.
    ///
    /// (Automatically generated by Diesel.)
    user_admin_roles (id) {
        /// The `id` column of the `user_admin_roles` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `firebase_uid` column of the `user_admin_roles` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 128]
        firebase_uid -> Varchar,
        /// The `module_code` column of the `user_admin_roles` table.
        ///
        /// Its SQL type is `AdminModule`.
        ///
        /// (Automatically generated by Diesel.)
        module_code -> AdminModule,
        /// The `granted_by` column of the `user_admin_roles` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 128]
        granted_by -> Nullable<Varchar>,
        /// The `expires_at` column of the `user_admin_roles` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Nullable<Timestamptz>,
        /// The `is_active` column of the `user_admin_roles` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        is_active -> Nullable<Bool>,
        /// The `created_at` column of the `user_admin_roles` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Nullable<Timestamptz>,
        /// The `updated_at` column of the `user_admin_roles` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::pg::sql_types::*;
    use super::sql_types::PackageTier;
    use super::sql_types::UserRole;

    /// Representation of the `users` table.
    ///
    /// (Automatically generated by Diesel.)
    users (id) {
        /// The `id` column of the `users` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `firebase_uid` column of the `users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 128]
        firebase_uid -> Varchar,
        /// The `email` column of the `users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        email -> Varchar,
        /// The `display_name` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        display_name -> Nullable<Varchar>,
        /// The `name` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        name -> Nullable<Varchar>,
        /// The `avatar_url` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        avatar_url -> Nullable<Text>,
        /// The `package_tier` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<PackageTier>`.
        ///
        /// (Automatically generated by Diesel.)
        package_tier -> Nullable<PackageTier>,
        /// The `email_verified` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        email_verified -> Nullable<Bool>,
        /// The `is_active` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        is_active -> Nullable<Bool>,
        /// The `last_login_at` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        last_login_at -> Nullable<Timestamptz>,
        /// The `created_at` column of the `users` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `users` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// The `role` column of the `users` table.
        ///
        /// Its SQL type is `UserRole`.
        ///
        /// (Added for role support)
        role -> UserRole,
    }
}

diesel::joinable!(audit_logs -> sessions (session_id));
diesel::joinable!(firebase_sessions -> users (user_id));
diesel::joinable!(notification_preferences -> users (user_id));
diesel::joinable!(notifications -> users (user_id));
diesel::joinable!(sessions -> users (user_id));

diesel::allow_tables_to_appear_in_same_query!(
    admin_modules,
    admin_role_audit,
    audit_logs,
    eps_growth_analytics,
    firebase_sessions,
    notification_preferences,
    notifications,
    security_events,
    sessions,
    user_admin_roles,
    users,
);
