apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: epsx-base

resources:
  - namespace.yaml
  - configmaps/
  - secrets/
  - storage/
  - statefulsets/
  - deployments/
  - services/
  - ingress/

commonLabels:
  app.kubernetes.io/name: epsx
  app.kubernetes.io/component: backend
  app.kubernetes.io/managed-by: kustomize

configMapGenerator:
  - name: epsx-env
    envs:
      - ../../../environments/production.env

secretGenerator:
  - name: epsx-secrets
    envs:
      - ../../../environments/.secrets.production

replicas:
  - name: backend
    count: 3
  - name: frontend
    count: 2
  - name: admin-frontend
    count: 1

images:
  - name: backend
    newName: epsx-backend
    newTag: latest
  - name: frontend
    newName: epsx-frontend
    newTag: latest
  - name: admin-frontend
    newName: epsx-admin-frontend
    newTag: latest