export interface Feature {
  id: string;
  name: string;
  desc: string;
  route: string;
  screenshots: string[];
  category: string;
}

export const CATEGORIES = [
  'Dashboard',
  'Wallet Management',
  'Access Control',
  'Subscriptions',
  'Notifications',
  'Developer Portal',
  'Analytics',
  'System',
] as const;

export const FEATURES: Feature[] = [
  // Dashboard
  { id: 'admin-dashboard', name: 'Admin Home', desc: 'The admin home page displays key platform metrics at a glance: total registered users, monthly revenue, active wallet count, and API call volume. Summary cards provide quick insight into platform health.', route: '/', screenshots: ['admin-dashboard'], category: 'Dashboard' },
  { id: 'admin-dashboard-page', name: 'Dashboard Detail', desc: 'The detailed dashboard page shows interactive charts for user growth, revenue trends, and API usage over time. An activity feed lists recent admin actions and system events in chronological order.', route: '/dashboard', screenshots: ['admin-dashboard-page'], category: 'Dashboard' },
  { id: 'admin-auth', name: 'Admin Auth', desc: 'The admin authentication page presents Web3 wallet connection for admin portal access. Only wallets with admin-level permissions can authenticate, with RainbowKit providing the wallet selection UI.', route: '/auth', screenshots: ['admin-auth'], category: 'Dashboard' },
  { id: 'admin-access-denied', name: 'Access Denied', desc: 'This page appears when an authenticated admin attempts to access a route requiring higher permissions. It displays the denied resource and suggests requesting elevated access from a super admin.', route: '/access-denied', screenshots: ['admin-access-denied'], category: 'Dashboard' },
  { id: 'admin-unauthorized', name: 'Unauthorized', desc: 'This page is shown when a user visits the admin portal without any authentication session. It prompts the user to connect their wallet and sign in to proceed.', route: '/unauthorized', screenshots: ['admin-unauthorized'], category: 'Dashboard' },
  { id: 'admin-request-access', name: 'Request Access', desc: 'The request access form allows unauthenticated or low-privilege users to submit a request for admin portal access. The form collects the wallet address and a justification message for review by existing admins.', route: '/request-access', screenshots: ['admin-request-access'], category: 'Dashboard' },

  // Wallet Management
  { id: 'admin-wallet-management', name: 'Wallet Hub', desc: 'The central wallet management dashboard provides a high-level overview of all registered wallets. It shows total wallet count, active vs inactive breakdown, and navigation links to detailed wallet views.', route: '/wallet-management', screenshots: ['admin-wallet-management'], category: 'Wallet Management' },
  { id: 'admin-wallet-detail', name: 'Wallet Detail', desc: 'The individual wallet detail page shows the wallet address, current balance, transaction history, and assigned permissions. Admin can view the wallet\'s subscription status, credit balance, and recent activity.', route: '/wallet-management/[address]', screenshots: ['admin-wallet-detail'], category: 'Wallet Management' },
  { id: 'admin-wallets-default', name: 'Wallets List', desc: 'The default wallets list view shows all registered wallets in a searchable, filterable table. Each row displays the wallet address, status badge, platform, registration date, and action buttons.', route: '/wallet-management/wallets', screenshots: ['admin-wallets-default'], category: 'Wallet Management' },
  { id: 'admin-wallets-search', name: 'Search Wallets', desc: 'Admin types "0x742" into the search input above the wallets table. The list filters in real-time to show only wallet addresses matching the partial query, with the search text visible in the input field.', route: '/wallet-management/wallets', screenshots: ['admin-wallets-search'], category: 'Wallet Management' },
  { id: 'admin-wallets-filter-status', name: 'Filter by Status', desc: 'Admin clicks the Status filter and selects "Active" to narrow the wallet list. Only wallets with active status are shown, and the filter control displays the selected status value.', route: '/wallet-management/wallets', screenshots: ['admin-wallets-filter-status'], category: 'Wallet Management' },
  { id: 'admin-wallets-filter-platform', name: 'Filter by Platform', desc: 'Admin clicks the Platform filter to select a specific platform. The wallet list narrows to show only wallets registered on the chosen platform, with the active filter reflected in the dropdown.', route: '/wallet-management/wallets', screenshots: ['admin-wallets-filter-platform'], category: 'Wallet Management' },
  { id: 'admin-wallets-edit', name: 'Edit Wallet', desc: 'Admin clicks the Edit button on a wallet row to open the edit modal or inline editor. The UI shows editable fields for wallet metadata, status toggles, and platform assignment with Save/Cancel actions.', route: '/wallet-management/wallets', screenshots: ['admin-wallets-edit'], category: 'Wallet Management' },
  { id: 'admin-wallet-disable', name: 'Disable Wallet', desc: 'The wallet disable confirmation page shows the target wallet address and warns about the consequences of disabling. Admin must confirm the action before the wallet is deactivated across all platform services.', route: '/wallet-management/wallets/[address]/disable', screenshots: ['admin-wallet-disable'], category: 'Wallet Management' },
  { id: 'admin-wallet-activity', name: 'Wallet Activity', desc: 'The wallet activity log displays a chronological feed of actions across all wallets including logins, transactions, permission changes, and API calls. Each entry shows the wallet, action type, and timestamp.', route: '/wallet-management/activity', screenshots: ['admin-wallet-activity'], category: 'Wallet Management' },
  { id: 'admin-wallet-credits', name: 'Wallet Credits', desc: 'The wallet credits page shows credit balances across all wallets in a sortable table. Each row displays the wallet address, current balance, total earned, total spent, and last transaction date.', route: '/wallet-management/credits', screenshots: ['admin-wallet-credits'], category: 'Wallet Management' },

  // Access Control
  { id: 'admin-access-overview', name: 'Access Overview', desc: 'The access control overview shows a summary of all permission policies and role assignments across the platform. Cards display total policies, active assignments, and links to manage permissions and plans.', route: '/wallet-management/access', screenshots: ['admin-access-overview'], category: 'Access Control' },
  { id: 'admin-access-permissions', name: 'Access Permissions', desc: 'The granular permissions page lists all available platform permissions in IAM format (e.g., "admin:users:manage"). Admin can assign or revoke individual permissions per wallet with toggle controls.', route: '/wallet-management/access/permissions', screenshots: ['admin-access-permissions'], category: 'Access Control' },
  { id: 'admin-access-plans', name: 'Access Plans', desc: 'The access plans page shows all permission plans as cards, each with a name, description, and count of grouped features. Plans bundle multiple permissions together for easy assignment to wallets.', route: '/wallet-management/access/plans', screenshots: ['admin-access-plans'], category: 'Access Control' },
  { id: 'admin-access-plan-detail', name: 'Plan Detail', desc: 'The individual plan detail page shows the plan configuration including its name, description, bundled permissions list, and currently assigned wallets. Admin can edit the plan or manage wallet assignments.', route: '/wallet-management/access/plans/[planId]', screenshots: ['admin-access-plan-detail'], category: 'Access Control' },

  // Subscriptions
  { id: 'admin-subscription-detail', name: 'Subscription Detail', desc: 'The subscription detail page shows a specific subscription\'s status, assigned wallet, plan tier, start and expiration dates, payment history, and renewal settings. Admin can modify or cancel the subscription.', route: '/subscriptions/[id]', screenshots: ['admin-subscription-detail'], category: 'Subscriptions' },
  { id: 'admin-subscription-new', name: 'New Subscription Form', desc: 'The empty new subscription form presents input fields for wallet address, plan selection dropdown, and access configuration. All fields are in their default empty state, ready for admin to fill in.', route: '/subscriptions/new', screenshots: ['admin-subscription-new'], category: 'Subscriptions' },
  { id: 'admin-subscription-new-filled', name: 'Subscription Form Filled', desc: 'Admin has filled in the subscription form with a wallet address (0x742d...) and selected a plan from the dropdown. The form shows populated fields with the wallet address entered and plan selection made.', route: '/subscriptions/new', screenshots: ['admin-subscription-new-filled'], category: 'Subscriptions' },
  { id: 'admin-subscription-new-external', name: 'External Access Context', desc: 'Admin selects the External access type option on the subscription form. The UI updates to show external access-specific fields and configuration options, changing the form context from internal to external.', route: '/subscriptions/new', screenshots: ['admin-subscription-new-external'], category: 'Subscriptions' },
  { id: 'admin-plan-new', name: 'New Plan', desc: 'The new plan creation form presents fields for plan name, description, pricing tiers, and feature checkboxes. Admin configures the plan details before submitting to create a new subscription offering.', route: '/subscriptions/plans/new', screenshots: ['admin-plan-new'], category: 'Subscriptions' },
  { id: 'admin-plan-edit', name: 'Edit Plan', desc: 'The plan edit form loads an existing plan\'s configuration into editable fields. Admin can modify the name, pricing, features, and availability. Current subscriber count is shown to indicate the impact of changes.', route: '/subscriptions/plans/[id]/edit', screenshots: ['admin-plan-edit'], category: 'Subscriptions' },

  // Notifications
  { id: 'admin-notifications', name: 'Notifications List', desc: 'The admin notification list shows all sent and scheduled notifications with type badges, recipient counts, delivery dates, and status indicators. Each row provides quick access to view or edit the notification.', route: '/notifications', screenshots: ['admin-notifications'], category: 'Notifications' },
  { id: 'admin-notification-create', name: 'Create Notification', desc: 'The empty notification creation form shows input fields for title, message body, type selector, priority level, and recipient targeting. All fields are in their default state ready for admin to compose a new notification.', route: '/notifications/create', screenshots: ['admin-notification-create'], category: 'Notifications' },
  { id: 'admin-notification-create-filled', name: 'Notification Form Filled', desc: 'Admin has filled the notification form with a title ("System Maintenance Notice"), a detailed message body, and selected type and priority options. The form shows all populated fields ready for review and submission.', route: '/notifications/create', screenshots: ['admin-notification-create-filled'], category: 'Notifications' },
  { id: 'admin-notification-manage', name: 'Manage Notifications', desc: 'The notification management page allows admin to edit, delete, and reschedule existing notifications. Each notification shows its current status, delivery stats, and action buttons for modification.', route: '/notifications/manage', screenshots: ['admin-notification-manage'], category: 'Notifications' },

  // Developer Portal
  { id: 'admin-developer-portal', name: 'Developer Portal', desc: 'The admin developer portal overview displays all API keys, their usage statistics, rate limit status, and module access. Summary cards show total API calls, active keys, and links to key creation and documentation.', route: '/developer-portal', screenshots: ['admin-developer-portal'], category: 'Developer Portal' },
  { id: 'admin-api-key-create', name: 'Create API Key', desc: 'The API key creation form presents fields for key name, permission scope selection, rate limit configuration, and expiration settings. Admin configures access controls before generating the new API key.', route: '/developer-portal/api-keys/create', screenshots: ['admin-api-key-create'], category: 'Developer Portal' },
  { id: 'admin-api-docs', name: 'API Documentation', desc: 'The interactive API documentation browser shows available endpoints grouped by domain module. Each endpoint displays the HTTP method, path, description, request/response schemas, and testable code examples.', route: '/docs/api', screenshots: ['admin-api-docs'], category: 'Developer Portal' },

  // Analytics
  { id: 'admin-analytics', name: 'Admin Analytics', desc: 'The admin analytics dashboard presents platform-wide metrics with charts for user registrations, revenue trends, API performance, and active wallet growth. Time range selectors allow filtering data by period.', route: '/analytics', screenshots: ['admin-analytics'], category: 'Analytics' },

  // System
  { id: 'admin-profile', name: 'Admin Profile', desc: 'The admin profile page displays the administrator\'s wallet address, role, assigned permissions, and session information. Account metadata includes registration date, last login, and total admin actions performed.', route: '/profile', screenshots: ['admin-profile'], category: 'System' },
  { id: 'admin-settings', name: 'General Settings', desc: 'The general settings tab shows platform-wide configuration options including site name, default language, timezone, and maintenance mode toggle. Changes apply globally across the admin portal.', route: '/settings', screenshots: ['admin-settings'], category: 'System' },
  { id: 'admin-settings-appearance', name: 'Appearance Settings', desc: 'Admin clicks the Appearance tab in settings to reveal theme and visual customization options. The UI shows theme selection (dark/light), accent color picker, and layout density preferences.', route: '/settings', screenshots: ['admin-settings-appearance'], category: 'System' },
  { id: 'admin-settings-notifications', name: 'Notification Settings', desc: 'Admin clicks the Notifications tab in settings to configure notification delivery preferences. Toggle switches control email alerts, push notifications, and in-app notification channels with frequency options.', route: '/settings', screenshots: ['admin-settings-notifications'], category: 'System' },
  { id: 'admin-settings-security', name: 'Security Settings', desc: 'Admin clicks the Security tab in settings to view session management and access controls. Options include session timeout duration, IP allowlisting, two-factor authentication settings, and active session list.', route: '/settings', screenshots: ['admin-settings-security'], category: 'System' },
  { id: 'admin-audit-log', name: 'Audit Log', desc: 'The audit log displays a chronological security trail of all admin actions. Each entry shows the actor wallet, action type, affected resource, timestamp, and IP address in a sortable table.', route: '/audit-log', screenshots: ['admin-audit-log'], category: 'System' },
  { id: 'admin-audit-log-search', name: 'Search Audit Log', desc: 'Admin types "wallet" into the audit log search input. The log filters to show only entries containing the search term in the action description or resource field, with the query visible in the input.', route: '/audit-log', screenshots: ['admin-audit-log-search'], category: 'System' },
  { id: 'admin-audit-log-category', name: 'Audit Log Category', desc: 'Admin clicks a category filter tab (e.g., "Auth" or "Admin") above the audit log table. The log narrows to show only entries of the selected category, with the active tab appearing in its highlighted state.', route: '/audit-log', screenshots: ['admin-audit-log-category'], category: 'System' },
  { id: 'admin-payments', name: 'Payments', desc: 'The admin payments page shows a complete transaction history across all platform users. Each row displays the payer wallet, amount, payment method, transaction hash, date, and status badge.', route: '/payments', screenshots: ['admin-payments'], category: 'System' },
  { id: 'admin-affiliates', name: 'Affiliates', desc: 'The affiliate management page displays all affiliate partners with their referral codes, conversion counts, commission earnings, and payout status. Admin can activate, deactivate, or adjust affiliate terms.', route: '/affiliates', screenshots: ['admin-affiliates'], category: 'System' },
  { id: 'admin-debug-auth', name: 'Debug Auth', desc: 'The debug authentication page shows the current admin session details including JWT token claims, decoded permissions array, session expiration, and raw cookie values for troubleshooting auth issues.', route: '/debug/auth', screenshots: ['admin-debug-auth'], category: 'System' },
];
