-- Security Alerts and Webhooks Infrastructure
-- Migration 010: Real-time security alerting system with notification channels

-- Security Alert Rules Configuration
CREATE TABLE security_alert_rules (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    description TEXT,
    category VARCHAR(50) NOT NULL CHECK (category IN (
        'AUTHENTICATION', 'AUTHORIZATION', 'BRUTE_FORCE', 
        'INJECTION', 'PRIVILEGE_ESCALATION', 'DATA_BREACH',
        'ANOMALY', 'PERFORMANCE', 'SYSTEM'
    )),
    severity VARCHAR(20) NOT NULL CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    
    -- Rule configuration as JSONB for flexibility
    conditions JSONB NOT NULL, -- Rule conditions and thresholds
    aggregation_window_minutes INTEGER DEFAULT 5,
    threshold_value NUMERIC NOT NULL,
    threshold_operator VARCHAR(10) NOT NULL CHECK (threshold_operator IN ('>', '>=', '<', '<=', '=', '!=')),
    
    -- Rule status and metadata
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_by VARCHAR(255),
    last_modified_by VARCHAR(255),
    
    -- Rate limiting to prevent alert spam
    cooldown_minutes INTEGER DEFAULT 15,
    max_alerts_per_hour INTEGER DEFAULT 10,
    
    -- Additional configuration
    tags JSONB DEFAULT '[]',
    custom_fields JSONB DEFAULT '{}',
    
    CONSTRAINT unique_rule_name UNIQUE (name)
);

-- Security Alerts Generated by Rules
CREATE TABLE security_alerts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    rule_id UUID REFERENCES security_alert_rules(id) ON DELETE CASCADE,
    
    -- Alert identification
    title VARCHAR(500) NOT NULL,
    description TEXT,
    severity VARCHAR(20) NOT NULL CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    category VARCHAR(50) NOT NULL,
    
    -- Alert status and lifecycle
    status VARCHAR(20) DEFAULT 'ACTIVE' CHECK (status IN (
        'ACTIVE', 'ACKNOWLEDGED', 'RESOLVED', 'SUPPRESSED', 'ESCALATED'
    )),
    
    -- Timing information
    triggered_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    acknowledged_at TIMESTAMP WITH TIME ZONE,
    resolved_at TIMESTAMP WITH TIME ZONE,
    
    -- Associated data
    event_data JSONB NOT NULL, -- Related security events and context
    affected_entities JSONB DEFAULT '{}', -- Users, IPs, sessions affected
    correlation_id VARCHAR(255), -- For grouping related alerts
    
    -- Assignment and resolution
    assigned_to VARCHAR(255),
    acknowledged_by VARCHAR(255),
    resolved_by VARCHAR(255),
    resolution_notes TEXT,
    
    -- Alert metrics
    trigger_count INTEGER DEFAULT 1,
    escalation_level INTEGER DEFAULT 0,
    
    -- Additional metadata
    source_ip INET,
    user_id VARCHAR(255),
    session_id VARCHAR(255),
    custom_fields JSONB DEFAULT '{}',
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Webhook Endpoints Configuration
CREATE TABLE webhook_endpoints (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    url TEXT NOT NULL,
    
    -- Webhook configuration
    http_method VARCHAR(10) DEFAULT 'POST' CHECK (http_method IN ('POST', 'PUT', 'PATCH')),
    content_type VARCHAR(100) DEFAULT 'application/json',
    
    -- Authentication
    auth_type VARCHAR(20) DEFAULT 'HMAC' CHECK (auth_type IN ('NONE', 'BASIC', 'BEARER', 'HMAC', 'CUSTOM')),
    auth_config JSONB DEFAULT '{}', -- Stores auth credentials/config
    
    -- Headers and payload customization
    custom_headers JSONB DEFAULT '{}',
    payload_template JSONB, -- Template for webhook payload
    
    -- Retry configuration
    retry_attempts INTEGER DEFAULT 3,
    retry_backoff_seconds INTEGER DEFAULT 60,
    timeout_seconds INTEGER DEFAULT 30,
    
    -- Filtering
    alert_severity_filter VARCHAR(50)[], -- Only send for specific severities
    alert_category_filter VARCHAR(50)[], -- Only send for specific categories
    
    -- Status and health
    is_active BOOLEAN DEFAULT true,
    last_success_at TIMESTAMP WITH TIME ZONE,
    last_failure_at TIMESTAMP WITH TIME ZONE,
    failure_count INTEGER DEFAULT 0,
    health_status VARCHAR(20) DEFAULT 'HEALTHY' CHECK (health_status IN ('HEALTHY', 'DEGRADED', 'FAILED')),
    
    -- Metadata
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_by VARCHAR(255),
    
    CONSTRAINT unique_webhook_name UNIQUE (name)
);

-- Notification Channels Configuration
CREATE TABLE notification_channels (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    channel_type VARCHAR(50) NOT NULL CHECK (channel_type IN (
        'WEBHOOK', 'EMAIL', 'SLACK', 'DISCORD', 'PAGERDUTY', 'SMS', 'TEAMS'
    )),
    
    -- Channel configuration
    config JSONB NOT NULL, -- Channel-specific configuration
    
    -- Filtering and routing
    alert_severity_filter VARCHAR(50)[], -- Only notify for specific severities
    alert_category_filter VARCHAR(50)[], -- Only notify for specific categories
    time_restrictions JSONB, -- When to send notifications
    
    -- Rate limiting
    rate_limit_per_minute INTEGER DEFAULT 10,
    rate_limit_per_hour INTEGER DEFAULT 60,
    
    -- Status
    is_active BOOLEAN DEFAULT true,
    last_used_at TIMESTAMP WITH TIME ZONE,
    
    -- Metadata
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    CONSTRAINT unique_channel_name UNIQUE (name)
);

-- Notification Delivery Tracking
CREATE TABLE notification_deliveries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    alert_id UUID REFERENCES security_alerts(id) ON DELETE CASCADE,
    channel_id UUID REFERENCES notification_channels(id) ON DELETE SET NULL,
    webhook_id UUID REFERENCES webhook_endpoints(id) ON DELETE SET NULL,
    
    -- Delivery details
    delivery_method VARCHAR(50) NOT NULL,
    recipient VARCHAR(500),
    
    -- Status tracking
    status VARCHAR(20) DEFAULT 'PENDING' CHECK (status IN (
        'PENDING', 'SENT', 'DELIVERED', 'FAILED', 'RETRYING'
    )),
    
    -- Timing
    scheduled_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    sent_at TIMESTAMP WITH TIME ZONE,
    delivered_at TIMESTAMP WITH TIME ZONE,
    
    -- Error handling
    attempt_count INTEGER DEFAULT 0,
    max_attempts INTEGER DEFAULT 3,
    last_error TEXT,
    
    -- Delivery metadata
    request_id VARCHAR(255),
    response_code INTEGER,
    response_body TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Alert Acknowledgment and Comments
CREATE TABLE alert_comments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    alert_id UUID REFERENCES security_alerts(id) ON DELETE CASCADE,
    
    -- Comment details
    comment_text TEXT NOT NULL,
    comment_type VARCHAR(20) DEFAULT 'COMMENT' CHECK (comment_type IN (
        'COMMENT', 'ACKNOWLEDGMENT', 'RESOLUTION', 'ESCALATION', 'STATUS_CHANGE'
    )),
    
    -- Author information
    author VARCHAR(255) NOT NULL,
    author_role VARCHAR(100),
    
    -- Metadata
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_internal BOOLEAN DEFAULT false -- Internal vs public comments
);

-- Alert Escalation Rules
CREATE TABLE alert_escalation_rules (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    
    -- Escalation conditions
    severity VARCHAR(20) NOT NULL,
    category VARCHAR(50),
    unacknowledged_minutes INTEGER NOT NULL,
    
    -- Escalation actions
    escalate_to_severity VARCHAR(20) CHECK (escalate_to_severity IN ('MEDIUM', 'HIGH', 'CRITICAL')),
    notify_channels UUID[], -- Array of notification channel IDs
    assign_to VARCHAR(255),
    
    -- Rule configuration
    is_active BOOLEAN DEFAULT true,
    priority INTEGER DEFAULT 100,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Alert Suppression Rules
CREATE TABLE alert_suppressions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    
    -- Suppression criteria
    alert_rule_id UUID REFERENCES security_alert_rules(id) ON DELETE CASCADE,
    conditions JSONB NOT NULL, -- Conditions for suppression
    
    -- Suppression window
    start_time TIMESTAMP WITH TIME ZONE,
    end_time TIMESTAMP WITH TIME ZONE,
    
    -- Recurring suppression
    is_recurring BOOLEAN DEFAULT false,
    recurrence_pattern JSONB, -- For recurring suppressions
    
    -- Status
    is_active BOOLEAN DEFAULT true,
    
    -- Metadata
    reason TEXT,
    created_by VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Alert Correlation and Grouping
CREATE TABLE alert_correlations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    correlation_id VARCHAR(255) NOT NULL,
    
    -- Correlation details
    alert_ids UUID[] NOT NULL,
    correlation_type VARCHAR(50) NOT NULL CHECK (correlation_type IN (
        'TIME_BASED', 'IP_BASED', 'USER_BASED', 'SESSION_BASED', 'PATTERN_BASED'
    )),
    
    -- Correlation metadata
    root_cause_alert_id UUID,
    correlation_score NUMERIC(5,4),
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    CONSTRAINT unique_correlation UNIQUE (correlation_id)
);

-- Indexes for optimal performance
CREATE INDEX idx_security_alert_rules_category ON security_alert_rules(category);
CREATE INDEX idx_security_alert_rules_severity ON security_alert_rules(severity);
CREATE INDEX idx_security_alert_rules_active ON security_alert_rules(is_active);

CREATE INDEX idx_security_alerts_rule_id ON security_alerts(rule_id);
CREATE INDEX idx_security_alerts_status ON security_alerts(status);
CREATE INDEX idx_security_alerts_severity ON security_alerts(severity);
CREATE INDEX idx_security_alerts_category ON security_alerts(category);
CREATE INDEX idx_security_alerts_triggered_at ON security_alerts(triggered_at);
CREATE INDEX idx_security_alerts_correlation ON security_alerts(correlation_id);
CREATE INDEX idx_security_alerts_user_id ON security_alerts(user_id);
CREATE INDEX idx_security_alerts_source_ip ON security_alerts(source_ip);

CREATE INDEX idx_webhook_endpoints_active ON webhook_endpoints(is_active);
CREATE INDEX idx_webhook_endpoints_health ON webhook_endpoints(health_status);

CREATE INDEX idx_notification_channels_type ON notification_channels(channel_type);
CREATE INDEX idx_notification_channels_active ON notification_channels(is_active);

CREATE INDEX idx_notification_deliveries_alert_id ON notification_deliveries(alert_id);
CREATE INDEX idx_notification_deliveries_status ON notification_deliveries(status);
CREATE INDEX idx_notification_deliveries_scheduled_at ON notification_deliveries(scheduled_at);

CREATE INDEX idx_alert_comments_alert_id ON alert_comments(alert_id);
CREATE INDEX idx_alert_comments_created_at ON alert_comments(created_at);

CREATE INDEX idx_alert_escalation_rules_active ON alert_escalation_rules(is_active);
CREATE INDEX idx_alert_suppressions_active ON alert_suppressions(is_active);

-- Composite indexes for common query patterns
CREATE INDEX idx_alerts_status_severity_created ON security_alerts(status, severity, triggered_at DESC);
CREATE INDEX idx_deliveries_status_scheduled ON notification_deliveries(status, scheduled_at);

-- Full-text search indexes
CREATE INDEX idx_security_alerts_title_fts ON security_alerts USING gin(to_tsvector('english', title));
CREATE INDEX idx_security_alerts_description_fts ON security_alerts USING gin(to_tsvector('english', description));

-- Triggers for automatic timestamp updates
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_security_alert_rules_updated_at BEFORE UPDATE ON security_alert_rules FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_security_alerts_updated_at BEFORE UPDATE ON security_alerts FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_webhook_endpoints_updated_at BEFORE UPDATE ON webhook_endpoints FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_notification_channels_updated_at BEFORE UPDATE ON notification_channels FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_notification_deliveries_updated_at BEFORE UPDATE ON notification_deliveries FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_alert_escalation_rules_updated_at BEFORE UPDATE ON alert_escalation_rules FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_alert_suppressions_updated_at BEFORE UPDATE ON alert_suppressions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Insert default alert rules
INSERT INTO security_alert_rules (name, description, category, severity, conditions, threshold_value, threshold_operator, cooldown_minutes) VALUES
('Brute Force Detection', 'Alert on multiple failed login attempts from single IP', 'BRUTE_FORCE', 'HIGH', '{"event_type": "MULTIPLE_FAILED_LOGINS", "time_window": 300}', 5, '>=', 30),
('Privilege Escalation Attempt', 'Alert on attempts to escalate privileges', 'PRIVILEGE_ESCALATION', 'CRITICAL', '{"event_type": "PRIVILEGE_ESCALATION_ATTEMPT"}', 1, '>=', 5),
('Geographic Anomaly', 'Alert on logins from unusual geographic locations', 'ANOMALY', 'MEDIUM', '{"event_type": "GEOGRAPHIC_ANOMALY_DETECTED"}', 1, '>=', 60),
('Multiple Account Lockouts', 'Alert when multiple accounts are locked in short time', 'AUTHENTICATION', 'HIGH', '{"event_type": "ACCOUNT_LOCKED", "time_window": 600}', 3, '>=', 20),
('Suspicious API Usage', 'Alert on unusual API usage patterns', 'ANOMALY', 'MEDIUM', '{"event_type": "UNUSUAL_API_USAGE_PATTERN"}', 1, '>=', 30),
('Database Injection Attempt', 'Alert on potential SQL injection attempts', 'INJECTION', 'CRITICAL', '{"event_type": "SQL_INJECTION_ATTEMPT"}', 1, '>=', 0),
('Mass Data Access', 'Alert on bulk data access operations', 'DATA_BREACH', 'HIGH', '{"event_type": "BULK_DATA_ACCESS", "time_window": 300}', 100, '>=', 15);

-- Insert default notification channels
INSERT INTO notification_channels (name, channel_type, config, alert_severity_filter) VALUES
('Critical Alerts Webhook', 'WEBHOOK', '{"url": "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK", "format": "slack"}', ARRAY['CRITICAL']),
('Security Team Email', 'EMAIL', '{"recipients": ["security@epsx.io"], "smtp_config": {"host": "smtp.gmail.com", "port": 587}}', ARRAY['HIGH', 'CRITICAL']),
('PagerDuty Critical', 'PAGERDUTY', '{"integration_key": "YOUR_PAGERDUTY_KEY", "service_key": "YOUR_SERVICE_KEY"}', ARRAY['CRITICAL']);

COMMENT ON TABLE security_alert_rules IS 'Configuration for security alert rules with flexible conditions and thresholds';
COMMENT ON TABLE security_alerts IS 'Generated security alerts with full lifecycle tracking';
COMMENT ON TABLE webhook_endpoints IS 'Webhook endpoint configurations with retry logic and health monitoring';
COMMENT ON TABLE notification_channels IS 'Multi-channel notification configuration for alerts';
COMMENT ON TABLE notification_deliveries IS 'Tracking of notification delivery attempts and results';
COMMENT ON TABLE alert_comments IS 'Comments and notes on security alerts for collaboration';
COMMENT ON TABLE alert_escalation_rules IS 'Rules for automatic alert escalation based on conditions';
COMMENT ON TABLE alert_suppressions IS 'Temporary or scheduled suppression of specific alerts';
COMMENT ON TABLE alert_correlations IS 'Correlation and grouping of related security alerts';