"""Run against the ignored Pay browser fixture on loopback :43127.
Requires the built real Dioxus WASM/server assets; never contacts production.
"""
import json,subprocess,time,pathlib
PREFIX=['agent-browser','--session','epsx-pay-fullstack']
pathlib.Path("target/pay-fullstack-evidence").mkdir(parents=True,exist_ok=True)
checks=[]
def command(*args):
 p=subprocess.run(PREFIX+list(args),text=True,capture_output=True,timeout=40)
 if p.returncode:raise RuntimeError(p.stdout+p.stderr)
 return p.stdout.strip()
def evaluate(js):return json.loads(command('eval',js))
def check(name,condition):
 if not condition:raise AssertionError(name)
 checks.append(name)
def find(role,name,action,*args):return command('find','role',role,action,'--name',name,*args)
def field(name,value):command('find','label',name,'fill',value)
def ready(text):command('wait','--text',text)
command('open','http://127.0.0.1:43127/dashboard')
command('wait','--fn','document.querySelector(".epsx-merchant") !== null')
time.sleep(1)
command('eval','sessionStorage.clear();window.__payDocument="preserved";window.__payErrors=[];window.addEventListener("error",e=>window.__payErrors.push(e.message)); true')
dark=evaluate('!!document.querySelector(".epsx-merchant.dark")')
find('button','Toggle theme','click')
command('wait','--fn',f'!!document.querySelector(".epsx-merchant.dark") === {str(not dark).lower()}')
check('hydrated theme event',True)
find('link','Settings','click');ready('Shop details')
check('internal navigation keeps document',evaluate('window.__payDocument === "preserved"'))
check('theme persists across navigation',evaluate(f'!!document.querySelector(".epsx-merchant.dark") === {str(not dark).lower()}'))
field('Shop name','Hydrated merchant');find('button','Save shop name','click');ready('Saved.')
check('typed mutation updates page without reload',evaluate('document.querySelector(".md-topbar").textContent.includes("Hydrated merchant") && window.__payDocument === "preserved"'))
field('Key name','Browser fixture');find('button','Create API key','click');ready('fixture_only_secret');find('button','I saved it','click')
check('one-time secret dismissed',evaluate('!document.body.textContent.includes("fixture_only_secret")'))
find('link','Packages','click');ready('Your catalog')
field('Package name','Reactive package');field('USDT price (optional)','7.50');field('Service duration in days (optional)','14');field('Description and service terms','Browser fixture only');find('button','Save package','click');ready('Reactive package')
check('catalog form is reactive',evaluate('document.querySelector(".md-products").textContent.includes("Reactive package") && window.__payDocument === "preserved"'))
command('select','select[aria-label="Environment"]','live');command('wait','--url','**environment=live')
check('environment updates URL without reload',evaluate('window.__payDocument === "preserved"'))
command('back');command('wait','--url','**environment=test')
check('history restores environment',evaluate('document.querySelector("select[aria-label=Environment]").value === "test"'))
find('link','View storefront ↗','click');ready('Choose a package')
command('find','first','article.md-product button','click');command('wait','--url','**/checkout/cs_fixture*');ready('QR / Transfer')
command('wait','--fn','document.querySelector(".pay-qr").naturalWidth > 0')
check('payment QR image loads',True)
check('checkout palette applies to Dioxus root',evaluate('getComputedStyle(document.querySelector(".epsx-checkout")).getPropertyValue("--pay-bg").trim().length > 0'))
check('checkout navigation stays hydrated',evaluate('window.__payDocument === "preserved"'))
find('button','Connect wallet','click')
command('eval','window.__sent=0;window.ethereum={request:async({method})=>{if(method==="eth_requestAccounts"||method==="eth_accounts")return ["0x1111111111111111111111111111111111111111"];if(method==="eth_chainId")return "0x7a69";if(method==="eth_sendTransaction"){window.__sent++;return "0x"+"a".repeat(64)};if(method==="eth_getTransactionReceipt")return null;throw Error("Unexpected mock method "+method)}};true')
find('button','MetaMask','click');ready('Connected wallet');find('button','Pay','click');ready('Transaction submitted:')
check('mock wallet transaction submits once',evaluate('window.__sent === 1'))
find('button','Pay','click');ready('Transaction submitted:')
check('duplicate click reuses stored transaction hash',evaluate('window.__sent === 1'))
check('submitted hash is not rendered as paid',evaluate('!document.body.textContent.includes("Payment received") && document.body.textContent.includes("awaiting_payment")'))
command('eval','sessionStorage.removeItem("epsx.checkout.transfer.cs_fixture");const original=window.ethereum.request;window.ethereum.request=async(r)=>{if(r.method==="eth_sendTransaction")throw Error("User rejected fixture transaction");return original(r)};true')
find('button','Pay','click');ready('User rejected fixture transaction')
check('wallet rejection leaves checkout usable',evaluate('window.__sent === 1 && !document.body.textContent.includes("Payment received")'))
command('eval','const rejected=window.ethereum.request;window.ethereum.request=async(r)=>{if(r.method==="eth_chainId")return "0x38";if(r.method==="wallet_switchEthereumChain")throw Error("User rejected fixture network switch");return rejected(r)};true')
find('button','Pay','click');ready('User rejected fixture network switch')
check('chain mismatch prevents sending',evaluate('window.__sent === 1'))
# Clear mock errors from visual review with the QR tab.
find('button','QR / Transfer','click')
for width,height in [(320,900),(390,844),(1440,1000)]:
 command('set','viewport',str(width),str(height))
 check(f'checkout does not overflow at {width}px',evaluate('document.documentElement.scrollWidth <= innerWidth'))
 command('eval','scrollTo(0,0);true')
 command('screenshot',str(pathlib.Path(f'target/pay-fullstack-evidence/checkout-{width}.png').resolve()))
check('no runtime errors after hydration',evaluate('window.__payErrors.length === 0'))
pathlib.Path('target/pay-fullstack-evidence/checks.json').write_text(json.dumps(checks,indent=2))
print(json.dumps(checks,indent=2))
